#!/usr/bin/env bash
# SESSION_NOTES-S224-through-S221.md.verify.sh — the losslessness proof for this shard.
#
# Generated by Session 228 (the THIRD trim). Re-runnable, read-only, exits non-zero on failure.
#
#   bash <this>              prove the third trim was lossless AND landed where it was declared
#   bash <this> --self-test  prove this proof can FAIL (28 mutants; exit 2 if any survives)
#
# Descended from Session 224's SESSION_NOTES-S220-through-S217.md.verify.sh, itself descended from
# Session 222's SESSION_NOTES-through-S216.md.verify.sh — read those for the rationale behind L0-L3
# and L4. Shards are WRITE-ONCE: this proof pins ITS OWN cut key and does not re-prove the earlier
# shards' cuts. Run all three.
#
# THREE ASSERTIONS ARE NEW HERE, and all three exist because an adversarial review of this trim
# found them missing. Every one of those findings was REFUTED by its verifier — on the ground that
# it broke no stated rule, falsified no written claim and lost no data — while each verifier
# separately confirmed the MECHANICS ("mechanically reproduced", "the mechanics are accurate").
# That split is the known signature of a finding worth acting on anyway (PROJECT_LEARNINGS #100),
# and it is how the ancestor's L4 came to exist. The refutations were right that nothing was
# broken. They were arguing about severity, not fact.
#
#   L5 (ROUTING) — the placement table, clause by clause. The ancestor had no such assertion at
#      all; the first version written this session parsed only the INTEGERS, and a probe showed a
#      table whose numbers were right and whose FILENAMES were swapped passed silently. That is the
#      whole failure L5 exists to remove, so L5 now parses `**<bounds>** -> `<file>`` pairs out of
#      all three copies of the table (live pointer block, shard banner, CLAUDE.md), requires each
#      copy to equal the declared ROUTING exactly, requires ROUTING to partition the session-id
#      space with no gap and no overlap, requires its shard clause and its live clause to match the
#      cut key — and then anchors every clause against reality by opening the file it names and
#      checking that file's actual record ids fall inside its bounds. That last check is what
#      catches a boundary moved consistently everywhere, which no self-consistent declaration can.
#
#      DELIBERATE SCOPE WIDENING. The ancestor says it "says nothing about the S216 or S220 shards."
#      This proof publishes a table that NAMES them, so it owes a check that the table is right. It
#      still does not re-prove their cuts.
#
#      TWO CONSEQUENCES WORTH KNOWING BEFORE YOU ARE SURPRISED BY THEM. (a) CLAUDE.md must carry
#      the canonical table AND be part of the trim commit, or this proof is red from the first run.
#      That is the point: the highest-traffic copy of the routing table is now load-bearing rather
#      than aspirational. (b) Like every other assertion here, L5 reads CLAUDE.md AT THE TRIM
#      COMMIT. It checks the table as AUTHORED; it does not police later edits to CLAUDE.md, and
#      claiming otherwise would be the overclaim this file exists to avoid. L7 is the one exception,
#      and only for the one artifact that is genuinely forbidden to change.
#
#   L6 (BANNER) — the shard's banner pinned byte-for-byte to a declared constant, the shard-side
#      analogue of what L2 has always done for the live front matter. Until now the banner was the
#      one part of the shard that was neither frozen nor checked, while asserting in its own text
#      that "Provenance is proved here, not asserted." A probe rewrote its headline to claim a
#      different session range and every assertion stayed green.
#
#   L7 (WRITE-ONCE) — the shard on disk today is still the bytes this proof was written about.
#      Everything else reads git history at the trim commit, so once that commit exists the suite
#      describes a historical state: delete the shard outright and the proof still prints "still
#      present, in the right file" and exits 0. Verified on the COMMITTED ancestor, not in
#      simulation — move S220's shard aside and its proof exits 0.
#
#      L7 IS DELIBERATELY ASYMMETRIC, and the asymmetry is the whole design. It compares only the
#      SHARD, never the live ledger. A verifier for the review made the decisive objection: force
#      the ancestor down a worktree-reading branch and it goes RED today, because the live file has
#      legitimately changed since its cut — "the proof red forever with zero data loss", which is
#      the exact shape CLAUDE.md's "Two commits, always" bullet names as the thing to avoid. That
#      objection is correct and it kills the obvious implementation. It does not touch this one:
#      the live file is SUPPOSED to change and is read from history; the shard is write-once and
#      must never change, so comparing it against its own committed blob can only go red if the
#      write-once rule was actually broken. Before this, that rule had no enforcement anywhere.
#
# MEASURED COVERAGE, so the next author does not have to re-derive it, and so nobody mistakes
# eight assertions for eight independent opinions. Neuter one at a time and re-run --self-test;
# what then survives is what that assertion alone was catching:
#
#     for A in L0 L1 L2 L3 L4 L5 L6 L7; do sed "s|^    fails += $A(.*|    pass|" <this> > /tmp/n.sh
#       echo "$A: $(bash /tmp/n.sh --self-test | grep SURVIVED)"; done
#
#     L0 (none)  L1 (none)  L2 M10-M13  L3 (none)  L4 (none)  L5 M16-M24  L6 M25,M26  L7 M27,M28
#
# So the three assertions this cut ADDS are each load-bearing alone, which is what CLAUDE.md's rule
# asks for. Four are not, and saying so is the point:
#
#   * L0, L1 and L3 overlap by construction and always have — L1 is the primary byte detector and
#     L3 is per-record naming layered on top of it, so a mutant falsifies both or neither.
#   * L4 was uniquely load-bearing when this file was first written this session, and STOPPED being
#     so when L5/4 was added: checking that each routed file's real record ids fall inside its
#     clause catches a whole-record boundary shift too (M14 -> the shard would hold Session 225;
#     M15 -> the live file would hold 224). L4 is kept anyway. It states the cut key directly
#     instead of inferring it, its failure message names the retained and archived sides, and an
#     assertion is not deadweight merely because a later, broader one happens to subsume it.
#
# This suite proves L0/L1/L3/L4 are jointly SUFFICIENT with the rest, not individually NECESSARY.
#
# The grammar is FROZEN into this file on purpose: a later change to the trim design must not
# silently change what THIS shard's proof means.
set -euo pipefail
exec python3 - "$@" <<'PYEOF'
import re, subprocess, sys
from collections import Counter

LIVE   = "SESSION_NOTES.md"
SHARD  = "docs/architecture-history/SESSION_NOTES-S224-through-S221.md"
CLAUDE = "CLAUDE.md"
ARCHIVE_DIR = "docs/architecture-history/"

# ---- the declared grammar (inherited unchanged; see the S216 shard's proof for why each clause) --
RECORD_START = re.compile(r"^### What Session (\S+) Did$")
FOOTER_MODE  = "none"     # ASSERTED by L0, not "don't look"
TRANSFORM    = None       # no rebase: the archived span is a pure byte slice
REGEN        = ()         # no regenerated front-matter fields — declared-empty, not unchecked

# `\S+` not `\d+`; `Did$` anchored; column-0 match. This cut's span contains NO duplicate heading
# and NO fenced block at all. Neither is special-cased anyway: both would ride inside the byte
# spans, and the fence-aware scan is kept because removing a clause that happens to be unexercised
# on one span is how a grammar rots. `\S+` still matters here for a second reason: L5 opens the
# S216 shard, whose ids include `20B` and `20A`, and a `\d+` grammar would merge them.

# ---- the declared CUT KEY. Hand-supplied, never read back from the artifacts (that would be
#      circular). L4 holds the records against it; L5 holds the prose routing tables against it. ----
CUT_RETAINED = ("228", "227", "226", "225")
CUT_ARCHIVED = ("224", "223", "222", "221")

# ---- the declared ROUTING table: (lower, upper, file). None means open on that side. Every copy
#      of this table in prose must parse to exactly this, and this must agree with the cut key AND
#      with what the named files actually contain. ----
ROUTING = (
    (None, 216,  "SESSION_NOTES-through-S216.md"),
    (217,  220,  "SESSION_NOTES-S220-through-S217.md"),
    (221,  224,  "SESSION_NOTES-S224-through-S221.md"),
    (225,  None, "SESSION_NOTES.md"),
)

POINTER = """**Third trim (Session 228). Archived Sessions 224 → 221 — 4 record headings, 891 lines** into
[`docs/architecture-history/SESSION_NOTES-S224-through-S221.md`](docs/architecture-history/SESSION_NOTES-S224-through-S221.md)
— same shape, same newest-on-top order, frozen and byte-for-byte unedited. **This live file now
holds Sessions 228 → 225 only** — four sessions, the floor `CLAUDE.md` sets. Its proof is
[`SESSION_NOTES-S224-through-S221.md.verify.sh`](docs/architecture-history/SESSION_NOTES-S224-through-S221.md.verify.sh):
the five inherited assertions plus **L5** (the table below, clause by clause — the numbers against
the cut key, the filenames against what those files actually hold), **L6** (the shard's banner
pinned byte-for-byte) and **L7** (that shard still being, on disk today, the bytes the proof was
written about — the only enforcement `write-once` has ever had).

**Three shards exist now, and none is a prefix of any other.** To place Session N, open the file
this table names. **This block is the authority**, and these four clauses are machine-checked here,
in the shard's banner, and in `CLAUDE.md`:

**N ≤ 216** → `SESSION_NOTES-through-S216.md`; **217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;
**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`; **N ≥ 225** → `SESSION_NOTES.md`.

`grep` the shards; `Read` none of them. **Shards stay write-once** — a fourth trim writes a fourth
file; it never appends to one of these three.

**A copy of that table inside a write-once file goes stale at the next cut and cannot be repaired.**
The S220 shard's banner still says *"the live ledger when N ≥ 221"*, which this trim falsified; its
proof predates L5 and will never notice. Treat every shard banner as a snapshot of its own cut. Two
further copies live outside every proof — `README.md`'s repo map and the shard-naming rule in
`docs/methodology/PROJECT_CONVENTIONS.md` — and a trim that leaves either one alone ships a lie.

**The two blocks below are frozen at the SECOND and FIRST trims and describe THOSE cuts.** This
trim falsified exactly two sentences of the second trim's block — its claim about which sessions
this live file holds, and its whole routing paragraph — and rewrote both as declared substitutions
the proof checks by exact equality. Every other byte of that block is original, and the first
trim's block is untouched. Each earlier proof reads its artifacts from the commit that added its
own shard, so this trim cannot disturb either; both were re-run green at this cut, and a session
that doubts that should run them rather than reason about it.

"""

BANNER = """# Session Notes — archive shard: Sessions 224 → 221

**Frozen. Write-once. Do not edit this file.** It holds the record byte spans that the third trim
(Session 228, 2026-08-20) removed from `SESSION_NOTES.md`: Sessions 224 → 221 — four record
headings, 891 lines — in the same newest-on-top order, byte-for-byte unedited.

**This shard is the third of three, and the newest of them.** No shard is a prefix of another, and
none is authoritative alone. Session N lives in:

**N ≤ 216** → `SESSION_NOTES-through-S216.md`; **217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;
**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`; **N ≥ 225** → `SESSION_NOTES.md`.

**That table is a snapshot of the cut that wrote it.** A routing table inside a write-once file
cannot be repaired when the next trim lands, so the pointer block in `SESSION_NOTES.md` is the
authority and this is a convenience copy. The hazard is not hypothetical: the S220 shard's banner
still says *"the live ledger when N ≥ 221"*, which this trim falsified, and its proof has no
assertion that could ever notice. Ours does — L5 checks this copy against the cut key and against
what the named files actually contain — but only as of this cut.

**`grep` this file; do not `Read` it.** At 933 lines it sits under the 2,000-line agent read
cap today — but that cap truncates in silence, with no error and no missing-data marker, and no
fleet tooling watches this path (the dashboard's `READ_CAP_WATCHED` is an exact-path set that does
not contain it). That size is final: shards are write-once, so a fourth trim creates a fourth file
rather than growing this one.

**Provenance is proved here, not asserted.** Run `SESSION_NOTES-S224-through-S221.md.verify.sh`,
beside this file. It re-derives L0/L1/L2/L3 and the L4 the second trim introduced, and adds three
assertions this cut introduces: **L5**, the routing table above and the pointer block's copy of it,
checked clause by clause — numbers against the cut key, filenames against what those files actually
hold; **L6**, this banner pinned byte-for-byte, because until now every word of it was unverified
prose; and **L7**, the only enforcement `write-once` has ever had — that this file on disk today is
still the bytes the proof was written about. Under `--self-test` it mutates the artifacts twenty-eight
ways and fails if any mutation goes uncaught. Do not believe this paragraph — run it.

**Cutting is by byte position, never by authorship.** Session 224's handoff evaluation is filed
inside Session 225's record, because this ledger files an evaluation under its author — so that
evaluation stayed behind in the live file while Session 224's own record came here. The same seam
brought Session 220's evaluation INTO this file, inside Session 221's record, out of the live file
where the second trim had left it. Expect this at every boundary, in both directions.

---

"""

# The ONLY edits to pre-existing front matter. Exact, uniquely anchored, checked by equality.
FRONT_SUBST = (
    ("— same shape, same newest-on-top order, frozen and byte-for-byte unedited. **This live file now\n"
     "holds Sessions 224 → 221 only** — four sessions, the floor `CLAUDE.md` sets. Its proof is\n",
     "— same shape, same newest-on-top order, frozen and byte-for-byte unedited. At that second cut\n"
     "this live file was left holding Sessions 224 → 221 — four sessions, the floor `CLAUDE.md`\n"
     "sets; the third trim above has since cut it again. Its proof is\n"),
    ("**Two shards exist now, and neither is a prefix of the other.** To place Session N: **N ≤ 216** →\n"
     "the S216 shard; **217 ≤ N ≤ 220** → the S220 shard; **N ≥ 221** → below, in this file. `grep` both;\n"
     "`Read` neither. **Shards are write-once** — a third trim writes a third file, it does not append.\n",
     "**Two shards existed at that cut, and neither was a prefix of the other.** The routing table that\n"
     "stood here named only those two and sent everything newer to this live file; the third trim\n"
     "falsified every clause of it, and the table above replaces it. `grep` the shards; `Read` none.\n"
     "**Shards are write-once** — a third trim writes a third file, it does not append.\n"),
)

MISSING = object()      # L7: the shard is absent from the working tree
NA      = object()      # L7: inapplicable — the trim is not committed yet

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, check=True).stdout.strip()


def blob(ref):
    r = subprocess.run(["git", "show", ref], capture_output=True, cwd=ROOT)
    if r.returncode:
        sys.exit("cannot read %s: %s" % (ref, r.stderr.decode("utf-8", "replace").strip()))
    return r.stdout.decode("utf-8")          # bytes -> str; never $(...) which eats trailing newlines


def worktree(rel):
    with open("%s/%s" % (ROOT, rel), encoding="utf-8", newline="") as fh:
        return fh.read()


def scan(lines):
    inside = False
    for i, raw in enumerate(lines):
        s = raw.rstrip("\r\n")
        if s.startswith("```") or s.startswith("~~~"):
            yield i, s, inside
            inside = not inside
            continue
        yield i, s, inside


def zones(text):
    """-> (front, [record, ...], lines). A record is a heading-delimited BYTE SPAN, never a session."""
    lines = text.splitlines(keepends=True)
    st = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)]
    if not st:
        return text, [], lines
    front = "".join(lines[:st[0]])
    bounds = st + [len(lines)]
    return front, ["".join(lines[a:b]) for a, b in zip(st, bounds[1:])], lines


def label(rec):
    for ln in rec.splitlines():
        if ln.strip():
            return ln.strip()[:90]
    return "(empty record)"


def ids(recs):
    """The session id captured from each record's own heading line, in order."""
    return tuple(RECORD_START.match(r.splitlines()[0]).group(1) for r in recs)


def declared(before_front):
    """The front matter this trim is ALLOWED to produce, before the pointer is inserted."""
    for old, new in FRONT_SUBST:
        before_front = before_front.replace(old, new, 1)
    return before_front


# One canonical clause shape, so all three copies of the table parse with one regex. Bounds AND
# destination in a single match: parsing them separately is what let the first version of L5 check
# the numbers of a table whose filenames were swapped.
ROUTE_CLAUSE = re.compile(r"\*\*(?:(\d+) ≤ N ≤ (\d+)|N ≤ (\d+)|N ≥ (\d+))\*\* → `([^`]+)`")


def parse_table(text):
    out = []
    for a, b, le, ge, dest in ROUTE_CLAUSE.findall(text):
        if a:
            out.append((int(a), int(b), dest))
        elif le:
            out.append((None, int(le), dest))
        else:
            out.append((int(ge), None, dest))
    return tuple(out)


_ID_CACHE = {}


def numeric_ids(dest, after, shard, sha):
    """The numeric session ids actually present in the file `dest` names. LIVE and SHARD come from
    the artifacts already in hand so a mutant can move them; the earlier shards are read once from
    the same commit as everything else. Non-numeric ids (`20B`, `20A`) are dropped, and a
    destination that yields none is reported rather than passing vacuously."""
    if dest == LIVE:
        text = after
    elif dest.endswith(SHARD.rsplit("/", 1)[1]):
        text = shard
    else:
        key = (dest, sha)
        if key not in _ID_CACHE:
            path = ARCHIVE_DIR + dest
            try:
                _ID_CACHE[key] = blob("%s:%s" % (sha, path)) if sha else worktree(path)
            except SystemExit:
                _ID_CACHE[key] = None
        text = _ID_CACHE[key]
        if text is None:
            return None
    return sorted(int(i) for i in ids(zones(text)[1]) if i.isdigit())


# =====================================================================================
# The assertions. Each returns a list of failure strings; empty == holds.
# =====================================================================================

def L0(name, text):
    """footer_mode='none' asserted: no standalone `---` after the last record start may carry
    content below it. In a newest-on-top ledger the footer sits exactly where an oldest-first cut
    takes from, so 'none' must mean 'I looked', not 'I did not look'."""
    front, recs, lines = zones(text)
    if not recs:
        return ["L0 %s: no records found — grammar mismatch" % name]
    last = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)][-1]
    out = []
    for i, s, ins in scan(lines):
        if not ins and i > last and s.strip() == "---":
            tail = "".join(lines[i + 1:])
            if tail.strip():
                out.append("L0 %s: trailing file-scoped block at line %d (%d B): %.400s"
                           % (name, i + 1, len(tail.encode()), tail))
    return out


def L1(before_recs, after_recs, shard_recs):
    """Concatenation identity scoped to the RECORDS zone. Operand order is load-bearing: this
    ledger is newest-on-top and the cut takes from the bottom, so retained precedes archived. No
    invert step — TRANSFORM is None, which makes this the strongest form. This is the PRIMARY
    byte-level detector; L3 adds per-record naming on top of it, and L4-L7 see what both are
    blind to."""
    got = "".join(after_recs) + "".join(shard_recs)
    want = "".join(before_recs)
    if got == want:
        return []
    i = next((n for n, (a, b) in enumerate(zip(got, want)) if a != b), min(len(got), len(want)))
    return ["L1: records-zone concatenation differs at character %d "
            "(retained+archived %d B vs before %d B)"
            % (i, len(got.encode()), len(want.encode()))]


def L2(before_front, after_front, shard_front, shard_recs, pointer):
    out = []
    # (a) footer half — inapplicable when FOOTER_MODE == "none"; say so, never claim it held.
    # (b) front-matter half. b1 is exact and subsumes b2; b2 and b3 still run because b1 is
    #     SKIPPED when the pointer is absent, and b3 is independent of all of it.
    for k, (old, _new) in enumerate(FRONT_SUBST, 1):
        if before_front.count(old) != 1:
            out.append("L2/b0 SUBSTITUTION %d NOT UNIQUELY ANCHORED: its source text occurs %d "
                       "times in the before front matter (want exactly 1) — the declaration has "
                       "gone stale against the file it claims to describe" % (k, before_front.count(old)))
    want_front = declared(before_front)
    if pointer not in after_front:
        out.append("L2_POINTER_MISSING: the declared pointer block is not in the live front matter "
                   "verbatim — a severed record set with no pointer to its shard")
    else:
        residue = after_front.replace(pointer, "", 1)
        if residue != want_front:
            i = next((n for n, (a, b) in enumerate(zip(residue, want_front)) if a != b),
                     min(len(residue), len(want_front)))
            out.append("L2/b1 CONFINEMENT: live front matter changed beyond the declared pointer "
                       "insertion + the %d declared substitutions; first divergence at character "
                       "%d (%d B residue vs %d B declared)"
                       % (len(FRONT_SUBST), i, len(residue.encode()), len(want_front.encode())))
    after_set = set(after_front.splitlines())
    for ln in want_front.splitlines():
        if ln.strip() and ln not in after_set:      # exact membership, never substring (BL-28)
            out.append("L2/b2 SURVIVAL: front-matter line vanished: %r" % ln[:120])
    body = shard_front + "".join(shard_recs)
    for ln in before_front.splitlines():
        s = ln.strip()
        if len(s) > 24 and s in body:
            out.append("L2/b3 NO-LEAK: front-matter line leaked into the shard: %r" % s[:120])
    return out


def L3(before_recs, after_recs, shard_recs):
    """Per-record partition by identity, ORDER and byte-equality. The injected set is MEASURED from
    record content, never baked in as a generation-time constant — that constant is why 5 of the 20
    proofs shipped across this fleet fail with zero data loss."""
    have = Counter(after_recs) + Counter(shard_recs)
    before_c = Counter(before_recs)
    absent = list((before_c - have).elements())
    added = list((have - before_c).elements())
    out = []
    for r in absent:
        out.append("L3 MISSING: a record from `before` is in neither artifact "
                   "(dropped, or edited so its original bytes exist nowhere): %s" % label(r))
    for r in added:
        # Project strengthening: this design forbids bundling any record edit into the trim commit
        # (three commits, by rule — claim, trim, close-out), so a non-zero added count means the
        # rule was broken. Deliberate divergence from the canonical tool, which downgraded this to
        # a note in v1.2.0 because the canonical repo bundles by practice.
        out.append("L3 ADDED: a record exists that was not in `before` — the trim commit "
                   "bundled a record edit: %s" % label(r))
    if not absent and not added:
        rebuilt, pool = [], Counter(added)
        for r in after_recs + shard_recs:
            if pool[r]:
                pool[r] -= 1
                continue
            rebuilt.append(r)
        bad = [i for i, (a, b) in enumerate(zip(before_recs, rebuilt)) if a != b]
        if bad or len(rebuilt) != len(before_recs):
            out.append("L3 ORDER: records out of order at indices %s" % bad[:12])
    return out


def L4(after_recs, shard_recs):
    """The cut point itself. L1 and L3 are blind to a whole-record boundary shift because it
    preserves concatenation, multiset membership and order simultaneously. This compares each side
    against the HAND-DECLARED cut key; reading the key back out of the artifacts would make it a
    restatement rather than an assertion."""
    out = []
    got_a, got_s = ids(after_recs), ids(shard_recs)
    if got_a != CUT_RETAINED:
        out.append("L4 CUT/retained: the live file holds Sessions %s; the declared cut key says %s"
                   % (list(got_a), list(CUT_RETAINED)))
    if got_s != CUT_ARCHIVED:
        out.append("L4 CUT/archived: the shard holds Sessions %s; the declared cut key says %s"
                   % (list(got_s), list(CUT_ARCHIVED)))
    return out


def L5(after_front, shard_front, claude, after, shard, sha, routing):
    """Routing coherence — see header note. Everything above is about BYTES. This is about the
    sentence a human acts on: which file to open for Session N. Five layers, because each catches
    something the others cannot."""
    out = []
    lo_a, hi_a = min(map(int, CUT_ARCHIVED)), max(map(int, CUT_ARCHIVED))
    lo_r = min(map(int, CUT_RETAINED))
    shard_base = SHARD.rsplit("/", 1)[1]

    # (1) every prose copy of the table must parse to exactly the declaration — bounds AND file.
    for who, text in (("live pointer", after_front), ("shard banner", shard_front),
                      ("CLAUDE.md", claude)):
        got = parse_table(text)
        if got != routing:
            out.append("L5/1 %s: its routing table parses to %s; the declaration says %s"
                       % (who, list(got), list(routing)))

    # (2) the declaration must partition the session-id space: one open below, one open above,
    #     contiguous in between, no gap and no overlap.
    below = [c for c in routing if c[0] is None]
    above = [c for c in routing if c[1] is None]
    if len(below) != 1 or len(above) != 1 or routing[0][0] is not None or routing[-1][1] is not None:
        out.append("L5/2 shape: want exactly one open-below clause first and one open-above clause "
                   "last; got %d and %d in %s" % (len(below), len(above), list(routing)))
    else:
        edge = routing[0][1]
        for lo, hi, dest in routing[1:-1]:
            if lo != edge + 1:
                out.append("L5/2 %s at %d-%d (`%s`): the preceding clause ends at %d"
                           % ("GAP" if lo > edge + 1 else "OVERLAP", lo, hi, dest, edge))
            edge = hi
        if routing[-1][0] != edge + 1:
            out.append("L5/2 %s between the last range (ends %d) and `N >= %d` (`%s`)"
                       % ("GAP" if routing[-1][0] > edge + 1 else "OVERLAP", edge,
                          routing[-1][0], routing[-1][2]))

    # (3) the clause naming THIS shard must be exactly this cut's archived span, and the clause
    #     naming the live ledger must open exactly at this cut's retained floor.
    mine = [c for c in routing if c[2] == shard_base]
    live = [c for c in routing if c[2] == LIVE]
    if len(mine) != 1 or mine[0][:2] != (lo_a, hi_a):
        out.append("L5/3 shard clause: the table routes %s to `%s`; this cut archived Sessions "
                   "%d-%d" % ([c[:2] for c in mine], shard_base, lo_a, hi_a))
    if len(live) != 1 or live[0][:2] != (lo_r, None):
        out.append("L5/3 live clause: the table routes %s to `%s`; this cut retained Sessions "
                   "%d and up" % ([c[:2] for c in live], LIVE, lo_r))

    # (4) THE ANCHOR AGAINST REALITY. A declaration can be wrong in a way that is perfectly
    #     self-consistent — move a boundary in every copy at once and (1)-(3) all still hold. So
    #     open each file the table names and check what is actually in it.
    for lo, hi, dest in routing:
        found = numeric_ids(dest, after, shard, sha)
        if found is None:
            out.append("L5/4 `%s`: the table routes Sessions %s-%s here and the file cannot be "
                       "read" % (dest, lo, hi))
            continue
        if not found:
            out.append("L5/4 `%s`: no numeric session ids found — the check would pass vacuously"
                       % dest)
            continue
        stray = [n for n in found if (lo is not None and n < lo) or (hi is not None and n > hi)]
        if stray:
            out.append("L5/4 `%s`: routed Sessions %s-%s, but it actually contains %s (ids %d-%d)"
                       % (dest, lo, hi, stray[:8], found[0], found[-1]))
    return out


def L6(shard_front, banner):
    """The shard banner, pinned byte-for-byte — the shard-side analogue of L2/b1. Without it the
    banner is the one part of the shard that is neither frozen nor checked, while its own text says
    provenance is proved here."""
    if shard_front == banner:
        return []
    i = next((n for n, (a, b) in enumerate(zip(shard_front, banner)) if a != b),
             min(len(shard_front), len(banner)))
    return ["L6 BANNER: the shard's banner is not the declared text; first divergence at character "
            "%d (%d B in the shard vs %d B declared)"
            % (i, len(shard_front.encode()), len(banner.encode()))]


def L7(sha, shard_blob, disk):
    """Write-once, enforced. Everything else reads history at the trim commit, so the suite stays
    green through any later truncation or deletion of the shard. Asymmetric on purpose: the live
    ledger is SUPPOSED to change and is never compared this way.

    Applicability is decided by `disk` ALONE and never by `sha`. That is not a style choice: tying
    it to `sha` forced the self-test to invent a fake commit id so M27/M28 could be reachable
    before the trim was committed, and that fake id then made every ancestor-shard read in L5/4
    fail — so all 28 mutants were "caught", most of them for the wrong reason. A self-test that
    reports the right verdict via the wrong assertion is the failure this whole file exists to
    make impossible."""
    if disk is NA:
        return []                      # not committed yet; the run banner says so rather than
                                       # letting silence read as a pass
    if disk is MISSING:
        return ["L7 WRITE-ONCE: the shard is GONE from the working tree. Every assertion above "
                "still passes because they read git history at the trim commit — this one is the "
                "reason you found out."]
    if disk != shard_blob:
        i = next((n for n, (a, b) in enumerate(zip(disk, shard_blob)) if a != b),
                 min(len(disk), len(shard_blob)))
        return ["L7 WRITE-ONCE: the shard on disk is not the shard committed at %s; first "
                "divergence at character %d (%d B on disk vs %d B committed). Shards are "
                "write-once; this file was edited after its trim."
                % (sha[:7] if sha else "the trim commit", i,
                   len(disk.encode()), len(shard_blob.encode()))]
    return []


def check(before, after, shard, claude, sha, disk, decl=None):
    d = {"POINTER": POINTER, "BANNER": BANNER, "ROUTING": ROUTING}
    if decl:
        d.update(decl)
    bf, br, _ = zones(before)
    af, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    fails = []
    fails += L0("before", before) + L0("after", after) + L0("shard", shard)
    fails += L1(br, ar, sr)
    fails += L2(bf, af, sf, sr, d["POINTER"])
    fails += L3(br, ar, sr)
    fails += L4(ar, sr)
    fails += L5(af, sf, claude, after, shard, sha, d["ROUTING"])
    fails += L6(sf, d["BANNER"])
    fails += L7(sha, shard, disk)
    return fails, (br, ar, sr)


# =====================================================================================
def artifacts():
    sha = subprocess.run(["git", "log", "--diff-filter=A", "-1", "--format=%H", "--", SHARD],
                         capture_output=True, text=True, cwd=ROOT).stdout.strip()
    if sha:
        try:
            disk = worktree(SHARD)
        except OSError:
            disk = MISSING
        return (blob("%s^:%s" % (sha, LIVE)), blob("%s:%s" % (sha, LIVE)),
                blob("%s:%s" % (sha, SHARD)), blob("%s:%s" % (sha, CLAUDE)),
                "the trim commit %s" % sha[:7], sha, disk)
    return (blob("HEAD:%s" % LIVE), worktree(LIVE), worktree(SHARD), worktree(CLAUDE),
            "HEAD vs the working tree (trim not yet committed)", None, NA)


def self_test(before, after, shard, claude, sha):
    _, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    purpose = next(ln for ln in zones(before)[0].splitlines() if ln.startswith("**Purpose:**"))

    def sub_in_shard(o, n, count=1):
        assert o in shard, "self-test fixture missing: %r" % o[:40]
        return shard.replace(o, n, count)

    assert "−" in "".join(sr), "self-test fixture missing: no U+2212 in the archived span"
    assert "−" not in sf, "fixture broken: M9 must mutate a RECORD, not the shard banner"

    # Every clause a mutant rewrites must be unambiguous in every text that carries it.
    CL216  = "**N ≤ 216** → `SESSION_NOTES-through-S216.md`"
    CL220  = "**217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`"
    CL224  = "**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`"
    CLLIVE = "**N ≥ 225** → `SESSION_NOTES.md`"
    for cl in (CL216, CL220, CL224, CLLIVE):
        for name, text in (("POINTER", POINTER), ("BANNER", BANNER),
                           ("live file", after), ("shard", shard), ("CLAUDE.md", claude)):
            assert text.count(cl) == 1, ("self-test fixture %r occurs %d times in %s (want 1)"
                                         % (cl[:28], text.count(cl), name))

    def rewrite(pairs, texts):
        """Apply the same clause rewrites to every text that carries the table."""
        out = []
        for t in texts:
            for o, n in pairs:
                t = t.replace(o, n, 1)
            out.append(t)
        return out

    # --- L5 fixtures. Each rewrites the DECLARATION and the artifact together, so the assertion
    #     that pins them by equality (L2 for the pointer, L6 for the banner) stays satisfied and
    #     L5 is the only one left able to object.
    m16_b, m16_s = rewrite([(CLLIVE, "**N ≥ 221** → `SESSION_NOTES.md`")], [BANNER, shard])
    m17_b, m17_s = rewrite([(CL224, "**220 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`")],
                           [BANNER, shard])
    m18_p, m18_a = rewrite([(CLLIVE, "**N ≥ 221** → `SESSION_NOTES.md`")], [POINTER, after])
    m19_p, m19_a = rewrite([(CL224, "**222 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`")],
                           [POINTER, after])
    swap = [(CL220, "**217 ≤ N ≤ 220** → `SESSION_NOTES-S224-through-S221.md`"),
            (CL224, "**221 ≤ N ≤ 224** → `SESSION_NOTES-S220-through-S217.md`")]
    m20_b, m20_s = rewrite(swap, [BANNER, shard])
    m21_p, m21_a = rewrite(swap, [POINTER, after])

    # M22/M23 rewrite ROUTING as well, so even the declaration is self-consistent.
    short = [(CL224, "**221 ≤ N ≤ 223** → `SESSION_NOTES-S224-through-S221.md`"),
             (CLLIVE, "**N ≥ 224** → `SESSION_NOTES.md`")]
    m22_p, m22_b, m22_a, m22_s, m22_c = rewrite(short, [POINTER, BANNER, after, shard, claude])
    m22_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 223, "SESSION_NOTES-S224-through-S221.md"),
             (224, None, "SESSION_NOTES.md"))
    front = [(CL216, "**N ≤ 100** → `SESSION_NOTES-through-S216.md`"),
             (CL220, "**101 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`")]
    m23_p, m23_b, m23_a, m23_s, m23_c = rewrite(front, [POINTER, BANNER, after, shard, claude])
    m23_r = ((None, 100, "SESSION_NOTES-through-S216.md"),
             (101, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 224, "SESSION_NOTES-S224-through-S221.md"),
             (225, None, "SESSION_NOTES.md"))

    # M14/M15 move ONE WHOLE RECORD across the boundary. ar[-1] is the oldest retained record and
    # sr[0] the newest archived one, so both mutants keep the newest-on-top order intact — which is
    # exactly why L1 and L3 cannot see them and L4 must.
    m14_after, m14_shard = after.replace(ar[-1], "", 1), sf + ar[-1] + "".join(sr)
    m15_after, m15_shard = after + sr[0], shard.replace(sr[0], "", 1)

    SAME = object()          # the mutant's own shard, i.e. an untampered working tree
    mutants = [
        ("M1  last byte of the shard's last record deleted", before, after, shard[:-1], claude, None, SAME),
        ("M2  one whole archived record deleted", before, after, shard.replace(sr[2], "", 1), claude, None, SAME),
        ("M3  one character flipped inside an archived record", before, after,
         sub_in_shard(sr[2], sr[2].replace("e", "3", 1)), claude, None, SAME),
        ("M4  one character flipped inside a retained record", before,
         after.replace(ar[-1], ar[-1].replace("e", "3", 1), 1), shard, claude, None, SAME),
        ("M5  two adjacent archived records swapped", before, after,
         sub_in_shard(sr[1] + sr[2], sr[2] + sr[1]), claude, None, SAME),
        ("M6  a front-matter line moved from the live file into the shard banner", before,
         after.replace(purpose + "\n", "", 1),
         shard.replace("---\n\n### What Session", purpose + "\n\n---\n\n### What Session", 1),
         claude, None, SAME),
        ("M7  a trailing file-scoped block appended below the shard's last record", before, after,
         shard + "\n---\n\ntrailing paragraph\n", claude, None, SAME),
        ("M8  the pointer block dropped from the live front matter", before,
         after.replace(POINTER, "", 1), shard, claude, None, SAME),
        ("M9  U+2212 silently normalised to ASCII '-' in an archived record", before, after,
         sub_in_shard("−", "-"), claude, None, SAME),
        ("M10 declared substitution 1 not applied (stale 'holds Sessions 224 → 221 only')", before,
         after.replace(FRONT_SUBST[0][1], FRONT_SUBST[0][0], 1), shard, claude, None, SAME),
        ("M11 declared substitution 2 not applied (stale two-shard routing paragraph)", before,
         after.replace(FRONT_SUBST[1][1], FRONT_SUBST[1][0], 1), shard, claude, None, SAME),
        ("M12 an UNDECLARED extra front-matter edit alongside the declared ones", before,
         after.replace("this paragraph is the only warning there is.",
                       "this paragraph is the only warning there was.", 1), shard, claude, None, SAME),
        ("M13 a substitution's anchor absent from `before` (declaration gone stale)",
         before.replace(FRONT_SUBST[0][0], "REPLACED BY AN EARLIER EDIT\n", 1), after, shard,
         claude, None, SAME),
        ("M14 cut shifted: the oldest RETAINED record moved into the shard", before,
         m14_after, m14_shard, claude, None, SAME),
        ("M15 cut shifted: the newest ARCHIVED record kept in the live file", before,
         m15_after, m15_shard, claude, None, SAME),
        ("M16 banner + its declaration agree on a stale `N ≥ 221`", before, after, m16_s,
         claude, {"BANNER": m16_b}, SAME),
        ("M17 banner + its declaration agree on a 220-224 range (overlaps the S220 shard)", before,
         after, m17_s, claude, {"BANNER": m17_b}, SAME),
        ("M18 pointer + its declaration agree on a stale `N ≥ 221`", before, m18_a, shard,
         claude, {"POINTER": m18_p}, SAME),
        ("M19 pointer + its declaration agree on a 222-224 range (Session 221 unroutable)", before,
         m19_a, shard, claude, {"POINTER": m19_p}, SAME),
        ("M20 banner: numbers untouched, the S220/S224 FILENAMES swapped", before, after, m20_s,
         claude, {"BANNER": m20_b}, SAME),
        ("M21 pointer: numbers untouched, the S220/S224 FILENAMES swapped", before, m21_a, shard,
         claude, {"POINTER": m21_p}, SAME),
        ("M22 every copy AND the declaration agree this shard holds 221-223", before, m22_a, m22_s,
         m22_c, {"POINTER": m22_p, "BANNER": m22_b, "ROUTING": m22_r}, SAME),
        ("M23 every copy AND the declaration move the S216/S220 frontier to 100/101", before,
         m23_a, m23_s, m23_c, {"POINTER": m23_p, "BANNER": m23_b, "ROUTING": m23_r}, SAME),
        ("M24 CLAUDE.md's copy of the table left stale", before, after, shard,
         claude.replace(CLLIVE, "**N ≥ 221** → `SESSION_NOTES.md`", 1), None, SAME),
        ("M25 the shard's banner headline claims a different session range", before, after,
         sub_in_shard("archive shard: Sessions 224 → 221", "archive shard: Sessions 220 → 217"),
         claude, None, SAME),
        ("M26 an extra paragraph inserted into the shard's banner", before, after,
         sub_in_shard("---\n\n### What Session", "\nInserted later by someone helpful.\n\n---\n\n### What Session"),
         claude, None, SAME),
        ("M27 the shard TRUNCATED on disk after the trim commit", before, after, shard, claude,
         None, shard[:20000]),
        ("M28 the shard DELETED from the working tree after the trim commit", before, after, shard,
         claude, None, MISSING),
    ]
    bad = []
    for name, b, a, s, c, decl, disk in mutants:
        # A mutant that does not name a disk state gets an untampered one: its own shard.
        d = s if disk is SAME else disk
        # The REAL sha, never a stand-in: L5/4 reads the ancestor shards through it, and a fake
        # one makes every one of them unreadable — which would "catch" all 28 mutants by breaking
        # the proof rather than by detecting the mutation. L7 stays reachable regardless because
        # its applicability comes from `d`, not from `sha`.
        fails, _ = check(b, a, s, c, sha, d, decl)
        if not fails:
            bad.append(name)
            print("  SURVIVED  %s" % name)
        else:
            # EVERY assertion that fires, not just the first: it must stay visible which assertion
            # is doing the work. A reader who thinks L3 is an independent second opinion on L1 is
            # mistaken — and M14-M28 are the fifteen that prove L4, L5, L6 and L7 are not either.
            codes = sorted({f.split(":")[0].split(" (")[0] for f in fails})
            print("  caught    %-72s -> %s" % (name, ", ".join(codes)))
    if bad:
        print("\nSELF-TEST FAILED: %d mutant(s) survived. This proof cannot be trusted." % len(bad))
        sys.exit(2)
    print("\nSELF-TEST OK: all %d mutants caught. Losing a byte fails this proof; so does editing"
          % len(mutants))
    print("one, skipping either declared correction, making an undeclared one, letting a")
    print("declaration go stale, sliding the cut point by one record, mis-stating where a session")
    print("lives even when every copy agrees, editing the shard's banner, or touching the shard")
    print("on disk after the commit that froze it.")


before, after, shard, claude, source, sha, disk = artifacts()

if "--self-test" in sys.argv:
    print("--self-test: mutating the artifacts and asserting each mutation is caught.\n")
    self_test(before, after, shard, claude, sha)
    sys.exit(0)

fails, (br, ar, sr) = check(before, after, shard, claude, sha, disk)
have = Counter(ar) + Counter(sr)
added = len(list((have - Counter(br)).elements()))

print("source : %s" % source)
print("grammar: heading /^### What Session \\S+ Did$/ ; footer_mode=none (asserted) ; transform=none")
print("records: %d before = %d retained + %d archived; added by the trim commit: %d"
      % (len(br), len(ar), len(sr), added))
print("cut key: retained %s | archived %s   (hand-declared, checked by L4 and L5)"
      % (list(CUT_RETAINED), list(CUT_ARCHIVED)))
print("routing: %d clauses, checked in 3 copies (live pointer, shard banner, CLAUDE.md) and"
      % len(ROUTING))
print("         anchored against the record ids actually in each file it names")
print("front  : pointer insertion + %d declared substitutions, all checked by exact equality"
      % len(FRONT_SUBST))
print("checked: L0, L1, L2/front-matter, L3, L4, L5, L6, L7    "
      "<- L2/footer absent: inapplicable, no footer zone")
if sha is None:
    print("         L7 inapplicable: the trim is not committed yet, so there is no frozen blob to")
    print("         compare the working tree against. It becomes live at the trim commit.")

if fails:
    print("\nFAIL for %s:" % SHARD)
    for f in fails:
        print("  " + f)
    sys.exit(1)

print("\nOK: %s hold for %s" % ("L0-L7" if sha else "L0-L6 (L7 inapplicable)", SHARD))
print("    Every byte of the pre-trim records zone is still present, in the right file, unedited,")
print("    in order, and on the declared side of the declared boundary; all three copies of the")
print("    routing table agree with that boundary AND with what the files they name contain; and")
print("    the shard's banner is the declared text.")
if sha:
    print("    The shard on disk is still the shard that was committed at %s." % sha[:7])
else:
    print("    NOTHING is claimed about the shard on disk: L7 has no frozen blob to compare it")
    print("    against until the trim is committed. Re-run after committing.")
print("    It says NOTHING about whether the boundary was WISELY chosen, nor whether")
print("    any record's content is true — a human reads that once. It does not re-prove the S216")
print("    or S220 cuts: each has its own proof, pinned to its own cut key and its own commit.")
print("    Run those two as well. A green proof never --self-test'ed proves less than it appears to.")
PYEOF
