#!/usr/bin/env bash
# SESSION_NOTES-S220-through-S217.md.verify.sh — the losslessness proof for this shard.
#
# Generated by Session 224 (the SECOND trim). Re-runnable, read-only, exits non-zero on failure.
#
#   bash <this>              prove the second trim was lossless AND landed where it was declared
#   bash <this> --self-test  prove this proof can FAIL (15 mutants; exit 2 if any survives)
#
# Descended from Session 222's SESSION_NOTES-through-S216.md.verify.sh, which is the file to read
# for the full rationale behind L0-L3. Shards are WRITE-ONCE: this proof pins ITS OWN cut key and
# says nothing about the S216 shard, whose proof pins commit a9510ca and is unaffected by this
# trim. Neither proof subsumes the other. Run both.
#
# THREE THINGS DIFFER FROM THE ANCESTOR, and each was forced by an adversarial review of this trim:
#
#   1. L2 admits TWO DECLARED FRONT-MATTER SUBSTITUTIONS (FRONT_SUBST) alongside the pointer
#      insertion; the ancestor allowed insertion only. Not convenience: the S216 pointer block
#      asserted "This live file holds Sessions 222 -> 217 only" AND that Session 216's handoff
#      evaluation "stayed here" — this trim falsified both (Session 217's record, which carries
#      that evaluation, is now in THIS shard). Leaving either would park a false present-tense
#      claim in the front matter of the file every session reads first, which is the defect class
#      the whole apparatus exists to prevent. So both are corrected, and both corrections are
#      DECLARED and checked by exact equality rather than waved through. Applying neither fails
#      (M10/M11); making an undeclared edit as well fails (M12); losing the anchor fails (M13).
#
#   2. L4 is NEW, and it pins the CUT POINT. L0-L3 prove the move was lossless; they are blind BY
#      CONSTRUCTION to where the boundary sits. Move one whole record across it and concatenation,
#      multiset membership and order are all preserved — L1 and L3 cannot see it. The ancestor
#      concedes this in its closing text ("says NOTHING about whether the cut point was well
#      chosen") and leaves the whole question to a human. L4 mechanises the half a machine can
#      decide: not whether the cut is WISE, but whether it is where this trim SAID it would be.
#      M14/M15 shift the boundary in each direction and are caught by L4 alone — which is the
#      evidence that L4 is not redundant with L1.
#
#   3. M9 is a U+2212 -> ASCII-hyphen normalisation rather than the ancestor's mojibake repair,
#      because this archived span contains no mojibake fixture. Same property — an invisible,
#      well-intentioned Unicode "cleanup" of archived bytes must fail this proof — using a
#      character pair that is visually identical in most fonts, which is strictly harder.
#
# The grammar is FROZEN into this file on purpose: a later change to the trim design must not
# silently change what THIS shard's proof means.
set -euo pipefail
exec python3 - "$@" <<'PYEOF'
import re, subprocess, sys
from collections import Counter

LIVE  = "SESSION_NOTES.md"
SHARD = "docs/architecture-history/SESSION_NOTES-S220-through-S217.md"

# ---- the declared grammar (inherited from the S216 shard's proof; see it for why each clause) ----
RECORD_START = re.compile(r"^### What Session (\S+) Did$")
FOOTER_MODE  = "none"     # ASSERTED by L0, not "don't look"
TRANSFORM    = None       # no rebase: the archived span is a pure byte slice
REGEN        = ()         # no regenerated front-matter fields — declared-empty, not unchecked

# `\S+` not `\d+`; `Did$` anchored; column-0 match. This cut's span contains a DUPLICATE heading
# pair (Session 218 appears twice, one a zero-body Phase-1B stub) and one balanced fenced block
# inside Session 217's record. Neither is special-cased — both ride inside the byte spans, and the
# fence-aware scan keeps the shard's fence parity identical to the live file's because the shard
# banner contributes no column-0 fence.

# ---- the declared CUT KEY. Hand-supplied, never read back from the artifacts (that would be
#      circular). This is what makes L4 an assertion rather than a restatement. ----
CUT_RETAINED = ("224", "223", "222", "221")
CUT_ARCHIVED = ("220", "219", "218", "218", "217")

POINTER = """**Second trim (Session 224). Archived Sessions 220 → 217 — 5 record headings, 774 lines** into
[`docs/architecture-history/SESSION_NOTES-S220-through-S217.md`](docs/architecture-history/SESSION_NOTES-S220-through-S217.md)
— same shape, same newest-on-top order, frozen and byte-for-byte unedited. **This live file now
holds Sessions 224 → 221 only** — four sessions, the floor `CLAUDE.md` sets. Its proof is
[`SESSION_NOTES-S220-through-S217.md.verify.sh`](docs/architecture-history/SESSION_NOTES-S220-through-S217.md.verify.sh):
four inherited assertions plus an L4 pinning the cut point, its own key, its own `--self-test`.

**Two shards exist now, and neither is a prefix of the other.** To place Session N: **N ≤ 216** →
the S216 shard; **217 ≤ N ≤ 220** → the S220 shard; **N ≥ 221** → below, in this file. `grep` both;
`Read` neither. **Shards are write-once** — a third trim writes a third file, it does not append.

**The block immediately below is frozen at the FIRST trim and describes THAT cut, not this one.**
This trim falsified exactly two of its sentences and rewrote both, as declared substitutions the
proof checks by exact equality; every other byte of that block is original. They were: its claim
that this live file holds Sessions 222 → 217, and its claim that Session 216's handoff evaluation
"stayed here" — Session 217's record, which carries that evaluation, is now in the S220 shard. That
block's own proof reads its artifacts from commit `a9510ca`, so this trim cannot disturb it; it
still runs green today, and a session that doubts that should run it rather than reason about it.

"""

# The ONLY edits to pre-existing front matter. Exact, uniquely anchored, checked by equality.
FRONT_SUBST = (
    ("— same format, same newest-on-top order, frozen, byte-for-byte unedited. This live file holds\n"
     "Sessions 222 → 217 only.\n",
     "— same format, same newest-on-top order, frozen, byte-for-byte unedited. At that first cut this\n"
     "live file was left holding Sessions 222 → 217; the second trim above has since cut it again.\n"),
    ("not by authorship:** Session 216's own handoff evaluation stayed here, inside Session 217's record,\n"
     "because this file files an evaluation under its author. Expect that seam at every trim boundary.\n",
     "not by authorship:** Session 216's own handoff evaluation is filed inside Session 217's record,\n"
     "because this file files an evaluation under its author. Expect that seam at every trim boundary.\n"),
)

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, check=True).stdout.strip()


def blob(ref):
    r = subprocess.run(["git", "show", ref], capture_output=True, cwd=ROOT)
    if r.returncode:
        sys.exit("cannot read %s: %s" % (ref, r.stderr.decode("utf-8", "replace").strip()))
    return r.stdout.decode("utf-8")          # bytes -> str; never $(...) which eats trailing newlines


def worktree(rel):
    with open("%s/%s" % (ROOT, rel), encoding="utf-8", newline="") as fh:
        return fh.read()


def scan(lines):
    inside = False
    for i, raw in enumerate(lines):
        s = raw.rstrip("\r\n")
        if s.startswith("```") or s.startswith("~~~"):
            yield i, s, inside
            inside = not inside
            continue
        yield i, s, inside


def zones(text):
    """-> (front, [record, ...], lines). A record is a heading-delimited BYTE SPAN, never a session."""
    lines = text.splitlines(keepends=True)
    st = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)]
    if not st:
        return text, [], lines
    front = "".join(lines[:st[0]])
    bounds = st + [len(lines)]
    return front, ["".join(lines[a:b]) for a, b in zip(st, bounds[1:])], lines


def label(rec):
    for ln in rec.splitlines():
        if ln.strip():
            return ln.strip()[:90]
    return "(empty record)"


def ids(recs):
    """The session id captured from each record's own heading line, in order."""
    return tuple(RECORD_START.match(r.splitlines()[0]).group(1) for r in recs)


def declared(before_front):
    """The front matter this trim is ALLOWED to produce, before the pointer is inserted."""
    for old, new in FRONT_SUBST:
        before_front = before_front.replace(old, new, 1)
    return before_front


# =====================================================================================
# The assertions. Each returns a list of failure strings; empty == holds.
# =====================================================================================

def L0(name, text):
    """footer_mode='none' asserted: no standalone `---` after the last record start may carry
    content below it. In a newest-on-top ledger the footer sits exactly where an oldest-first cut
    takes from, so 'none' must mean 'I looked', not 'I did not look'."""
    front, recs, lines = zones(text)
    if not recs:
        return ["L0 %s: no records found — grammar mismatch" % name]
    last = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)][-1]
    out = []
    for i, s, ins in scan(lines):
        if not ins and i > last and s.strip() == "---":
            tail = "".join(lines[i + 1:])
            if tail.strip():
                out.append("L0 %s: trailing file-scoped block at line %d (%d B): %.400s"
                           % (name, i + 1, len(tail.encode()), tail))
    return out


def L1(before_recs, after_recs, shard_recs):
    """Concatenation identity scoped to the RECORDS zone. Operand order is load-bearing: this
    ledger is newest-on-top and the cut takes from the bottom, so retained precedes archived. No
    invert step — TRANSFORM is None, which makes this the strongest form. This is the PRIMARY
    byte-level detector; L3 mostly adds per-record naming on top of it, and L4 sees what both
    are blind to."""
    got = "".join(after_recs) + "".join(shard_recs)
    want = "".join(before_recs)
    if got == want:
        return []
    i = next((n for n, (a, b) in enumerate(zip(got, want)) if a != b), min(len(got), len(want)))
    return ["L1: records-zone concatenation differs at character %d "
            "(retained+archived %d B vs before %d B)"
            % (i, len(got.encode()), len(want.encode()))]


def L2(before_front, after_front, shard_front, shard_recs):
    out = []
    # (a) footer half — inapplicable when FOOTER_MODE == "none"; say so, never claim it held.
    # (b) front-matter half. b1 is exact and subsumes b2; b2 and b3 still run because b1 is
    #     SKIPPED when the pointer is absent, and b3 is independent of all of it.
    for k, (old, _new) in enumerate(FRONT_SUBST, 1):
        if before_front.count(old) != 1:
            out.append("L2/b0 SUBSTITUTION %d NOT UNIQUELY ANCHORED: its source text occurs %d "
                       "times in the before front matter (want exactly 1) — the declaration has "
                       "gone stale against the file it claims to describe" % (k, before_front.count(old)))
    want_front = declared(before_front)
    if POINTER not in after_front:
        out.append("L2_POINTER_MISSING: the declared pointer block is not in the live front matter "
                   "verbatim — a severed record set with no pointer to its shard")
    else:
        residue = after_front.replace(POINTER, "", 1)
        if residue != want_front:
            i = next((n for n, (a, b) in enumerate(zip(residue, want_front)) if a != b),
                     min(len(residue), len(want_front)))
            out.append("L2/b1 CONFINEMENT: live front matter changed beyond the declared pointer "
                       "insertion + the %d declared substitutions; first divergence at character "
                       "%d (%d B residue vs %d B declared)"
                       % (len(FRONT_SUBST), i, len(residue.encode()), len(want_front.encode())))
    after_set = set(after_front.splitlines())
    for ln in want_front.splitlines():
        if ln.strip() and ln not in after_set:      # exact membership, never substring (BL-28)
            out.append("L2/b2 SURVIVAL: front-matter line vanished: %r" % ln[:120])
    body = shard_front + "".join(shard_recs)
    for ln in before_front.splitlines():
        s = ln.strip()
        if len(s) > 24 and s in body:
            out.append("L2/b3 NO-LEAK: front-matter line leaked into the shard: %r" % s[:120])
    return out


def L3(before_recs, after_recs, shard_recs):
    """Per-record partition by identity, ORDER and byte-equality. The injected set is MEASURED from
    record content, never baked in as a generation-time constant — that constant is why 5 of the 20
    proofs shipped across this fleet fail with zero data loss."""
    have = Counter(after_recs) + Counter(shard_recs)
    before_c = Counter(before_recs)
    absent = list((before_c - have).elements())
    added = list((have - before_c).elements())
    out = []
    for r in absent:
        out.append("L3 MISSING: a record from `before` is in neither artifact "
                   "(dropped, or edited so its original bytes exist nowhere): %s" % label(r))
    for r in added:
        # Project strengthening: this design forbids bundling any record edit into the trim commit
        # (three commits, by rule — claim, trim, close-out), so a non-zero added count means the
        # rule was broken. Deliberate divergence from the canonical tool, which downgraded this to
        # a note in v1.2.0 because the canonical repo bundles by practice.
        out.append("L3 ADDED: a record exists that was not in `before` — the trim commit "
                   "bundled a record edit: %s" % label(r))
    if not absent and not added:
        rebuilt, pool = [], Counter(added)
        for r in after_recs + shard_recs:
            if pool[r]:
                pool[r] -= 1
                continue
            rebuilt.append(r)
        bad = [i for i, (a, b) in enumerate(zip(before_recs, rebuilt)) if a != b]
        if bad or len(rebuilt) != len(before_recs):
            out.append("L3 ORDER: records out of order at indices %s" % bad[:12])
    return out


def L4(after_recs, shard_recs):
    """The cut point itself — see header note 2. L1 and L3 are blind to a whole-record boundary
    shift because it preserves concatenation, multiset membership and order simultaneously. This
    compares each side against the HAND-DECLARED cut key above; reading the key back out of the
    artifacts would make it a restatement rather than an assertion."""
    out = []
    got_a, got_s = ids(after_recs), ids(shard_recs)
    if got_a != CUT_RETAINED:
        out.append("L4 CUT/retained: the live file holds Sessions %s; the declared cut key says %s"
                   % (list(got_a), list(CUT_RETAINED)))
    if got_s != CUT_ARCHIVED:
        out.append("L4 CUT/archived: the shard holds Sessions %s; the declared cut key says %s"
                   % (list(got_s), list(CUT_ARCHIVED)))
    return out


def check(before, after, shard):
    bf, br, _ = zones(before)
    af, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    fails = []
    fails += L0("before", before) + L0("after", after) + L0("shard", shard)
    fails += L1(br, ar, sr)
    fails += L2(bf, af, sf, sr)
    fails += L3(br, ar, sr)
    fails += L4(ar, sr)
    return fails, (br, ar, sr)


# =====================================================================================
def artifacts():
    sha = subprocess.run(["git", "log", "--diff-filter=A", "-1", "--format=%H", "--", SHARD],
                         capture_output=True, text=True, cwd=ROOT).stdout.strip()
    if sha:
        return (blob("%s^:%s" % (sha, LIVE)), blob("%s:%s" % (sha, LIVE)),
                blob("%s:%s" % (sha, SHARD)), "the trim commit %s" % sha[:7])
    return (blob("HEAD:%s" % LIVE), worktree(LIVE), worktree(SHARD),
            "HEAD vs the working tree (trim not yet committed)")


def self_test(before, after, shard):
    _, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    purpose = next(ln for ln in zones(before)[0].splitlines() if ln.startswith("**Purpose:**"))

    def sub_in_shard(o, n, count=1):
        assert o in shard, "self-test fixture missing: %r" % o[:40]
        return shard.replace(o, n, count)

    assert "−" in "".join(sr), "self-test fixture missing: no U+2212 in the archived span"

    # M14/M15 move ONE WHOLE RECORD across the boundary. ar[-1] is the oldest retained record and
    # sr[0] the newest archived one, so both mutants keep the newest-on-top order intact — which is
    # exactly why L1 and L3 cannot see them and L4 must.
    m14_after, m14_shard = after.replace(ar[-1], "", 1), sf + ar[-1] + "".join(sr)
    m15_after, m15_shard = after + sr[0], shard.replace(sr[0], "", 1)

    mutants = [
        ("M1  last byte of the shard's last record deleted", before, after, shard[:-1]),
        ("M2  one whole archived record deleted", before, after, shard.replace(sr[2], "", 1)),
        ("M3  one character flipped inside an archived record", before, after,
         sub_in_shard(sr[2], sr[2].replace("e", "3", 1))),
        ("M4  one character flipped inside a retained record", before,
         after.replace(ar[-1], ar[-1].replace("e", "3", 1), 1), shard),
        ("M5  two adjacent archived records swapped", before, after,
         sub_in_shard(sr[1] + sr[2], sr[2] + sr[1])),
        ("M6  a front-matter line moved from the live file into the shard banner", before,
         after.replace(purpose + "\n", "", 1), shard.replace("---\n\n### What Session",
                                                             purpose + "\n\n---\n\n### What Session", 1)),
        ("M7  a trailing file-scoped block appended below the shard's last record", before, after,
         shard + "\n---\n\ntrailing paragraph\n"),
        ("M8  the pointer block dropped from the live front matter", before,
         after.replace(POINTER, "", 1), shard),
        ("M9  U+2212 silently normalised to ASCII '-' in an archived record", before, after,
         sub_in_shard("−", "-")),
        # --- the four that falsify THIS proof's declared-substitution divergence ---
        ("M10 declared substitution 1 not applied (stale 'holds Sessions 222 → 217')", before,
         after.replace(FRONT_SUBST[0][1], FRONT_SUBST[0][0], 1), shard),
        ("M11 declared substitution 2 not applied (stale 'stayed here')", before,
         after.replace(FRONT_SUBST[1][1], FRONT_SUBST[1][0], 1), shard),
        ("M12 an UNDECLARED extra front-matter edit alongside the declared ones", before,
         after.replace("this paragraph is the only warning there is.",
                       "this paragraph is the only warning there was.", 1), shard),
        ("M13 a substitution's anchor absent from `before` (declaration gone stale)",
         before.replace(FRONT_SUBST[0][0], "REPLACED BY AN EARLIER EDIT\n", 1), after, shard),
        # --- the two that falsify L4; L1 and L3 are blind to both by construction ---
        ("M14 cut shifted: the oldest RETAINED record moved into the shard", before,
         m14_after, m14_shard),
        ("M15 cut shifted: the newest ARCHIVED record kept in the live file", before,
         m15_after, m15_shard),
    ]
    bad = []
    for name, b, a, s in mutants:
        fails, _ = check(b, a, s)
        if not fails:
            bad.append(name)
            print("  SURVIVED  %s" % name)
        else:
            # EVERY assertion that fires, not just the first: it must stay visible which assertion
            # is doing the work. A reader who thinks L3 is an independent second opinion on L1 is
            # mistaken — and M14/M15 are the pair that proves L4 is NOT in that position.
            codes = sorted({f.split(":")[0].split(" (")[0] for f in fails})
            print("  caught    %-66s -> %s" % (name, ", ".join(codes)))
    if bad:
        print("\nSELF-TEST FAILED: %d mutant(s) survived. This proof cannot be trusted." % len(bad))
        sys.exit(2)
    print("\nSELF-TEST OK: all %d mutants caught. Losing a byte fails this proof; so does editing"
          % len(mutants))
    print("one, skipping either declared correction, making an undeclared one, letting a")
    print("declaration go stale, or sliding the cut point by a single record in either direction.")


before, after, shard, source = artifacts()

if "--self-test" in sys.argv:
    print("--self-test: mutating the artifacts and asserting each mutation is caught.\n")
    self_test(before, after, shard)
    sys.exit(0)

fails, (br, ar, sr) = check(before, after, shard)
have = Counter(ar) + Counter(sr)
added = len(list((have - Counter(br)).elements()))

print("source : %s" % source)
print("grammar: heading /^### What Session \\S+ Did$/ ; footer_mode=none (asserted) ; transform=none")
print("records: %d before = %d retained + %d archived; added by the trim commit: %d"
      % (len(br), len(ar), len(sr), added))
print("cut key: retained %s | archived %s   (hand-declared, checked by L4)"
      % (list(CUT_RETAINED), list(CUT_ARCHIVED)))
print("front  : pointer insertion + %d declared substitutions, all checked by exact equality"
      % len(FRONT_SUBST))
print("checked: L0, L1, L2/front-matter, L3, L4    "
      "<- L2/footer absent: inapplicable, no footer zone")

if fails:
    print("\nFAIL for %s:" % SHARD)
    for f in fails:
        print("  " + f)
    sys.exit(1)

print("\nOK: L0, L1, L2/front-matter, L3, L4 hold for %s" % SHARD)
print("    Every byte of the pre-trim records zone is still present, in the right file,")
print("    unedited, in order, and on the declared side of the declared boundary. It says")
print("    NOTHING about whether that boundary was WISELY chosen, nor whether any record's")
print("    content is true — a human reads that once. It says nothing about the S216 shard")
print("    either: that shard has its own proof, pinned to its own cut key. Run that one too.")
print("    A green proof that has never been --self-test'ed proves less than it appears to.")
PYEOF
