#!/usr/bin/env bash
# SESSION_NOTES-through-S216.md.verify.sh — the losslessness proof for this shard.
#
# Generated by Session 222. Re-runnable, read-only, exits non-zero on failure.
#
#   bash <this>              prove the trim was lossless
#   bash <this> --self-test  prove this proof can FAIL (9 mutants; exit 2 if any survives)
#
# It re-derives everything from git (or, before the trim is committed, from HEAD vs the
# working tree). It never trusts a stored digest and it never trusts the partition that
# produced the trim — every assertion runs against RE-PARSED artifacts, which is the
# defect the canonical trimmer caught in its own first build: asserting over
# records[:k] ++ records[k:] == records is an identity that can never fire, and it
# printed three OKs while dropping a record.
#
# WHY FOUR ASSERTIONS AND NOT ONE WHOLE-FILE CHECKSUM
#   The manual whole-file-identity procedure this replaces PASSED while a paragraph was
#   permanently lost — moving a paragraph out of the live file into the shard is exactly
#   byte-preserving under concatenation. And an unscoped whole-file check is not merely
#   weak here, it is UNSATISFIABLE: the live file gained a pointer block and the shard
#   gained a banner, so no whole-file identity can hold. Hence:
#
#     L0  footer declaration      — is there a trailing file-scoped block we would have lost?
#     L1  concatenation identity, scoped to the RECORDS zone   — is every record byte still somewhere?
#     L2  zone pinning            — is every byte still in the RIGHT file?
#     L3  record partition, per record, by identity+order+bytes — a pure move, or a move plus an edit?
#
# The grammar is FROZEN into this file on purpose: a later change to the trim design must
# not silently change what THIS shard's proof means.
set -euo pipefail
exec python3 - "$@" <<'PYEOF'
import re, subprocess, sys
from collections import Counter

LIVE  = "SESSION_NOTES.md"
SHARD = "docs/architecture-history/SESSION_NOTES-through-S216.md"

# ---- the declared grammar (the LedgerSpec this ledger would carry, supplied by hand) ----
RECORD_START = re.compile(r"^### What Session (\S+) Did$")
FOOTER_MODE  = "none"     # ASSERTED by L0, not "don't look"
TRANSFORM    = None       # no ../../ rebase: the archived span is a pure byte slice
REGEN        = ()         # no regenerated front-matter fields — declared-empty, not unchecked

# `\S+` not `\d+`: a `\d+` capture merges Sessions 20B+20A into one record.
# `Did$` anchored: without it, seven `### What Session N should do` headings become
# phantom records. Column-0 match: nine prose/backtick/blockquote mentions are excluded.

POINTER = """**Archived Sessions 216 → 1 — 206 record headings, 24,564 lines** into
[`docs/architecture-history/SESSION_NOTES-through-S216.md`](docs/architecture-history/SESSION_NOTES-through-S216.md)
— same format, same newest-on-top order, frozen, byte-for-byte unedited. This live file holds
Sessions 222 → 217 only.

**`grep` that shard; never `Read` it.** It is 24,564 lines — an agent `Read` truncates at 2,000
lines with no error and no missing-data marker, which is the defect this archive exists to remove.
Nothing watches the shard for that (`methodology_dashboard.py`'s `READ_CAP_WATCHED` is an exact-path
set holding only `SESSION_NOTES.md`, `CHANGELOG.md`, `HANDOFFS.md` and the backlog locations), so
this paragraph is the only warning there is.

**Losslessness is proved, not asserted.** Run
[`docs/architecture-history/SESSION_NOTES-through-S216.md.verify.sh`](docs/architecture-history/SESSION_NOTES-through-S216.md.verify.sh)
— it re-derives L0 (footer declaration), L1 (records-zone concatenation), L2 (zone pinning) and L3
(record partition) from git, and exits non-zero on failure; `--self-test` proves the proof itself can
fail. Do not trust this sentence, and do not trust a digest — run it. **The cut is by byte position,
not by authorship:** Session 216's own handoff evaluation stayed here, inside Session 217's record,
because this file files an evaluation under its author. Expect that seam at every trim boundary.

"""

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, check=True).stdout.strip()


def blob(ref):
    r = subprocess.run(["git", "show", ref], capture_output=True, cwd=ROOT)
    if r.returncode:
        sys.exit("cannot read %s: %s" % (ref, r.stderr.decode("utf-8", "replace").strip()))
    return r.stdout.decode("utf-8")          # bytes -> str; never $(...) which eats trailing newlines


def worktree(rel):
    with open("%s/%s" % (ROOT, rel), encoding="utf-8", newline="") as fh:
        return fh.read()


def scan(lines):
    inside = False
    for i, raw in enumerate(lines):
        s = raw.rstrip("\r\n")
        if s.startswith("```") or s.startswith("~~~"):
            yield i, s, inside
            inside = not inside
            continue
        yield i, s, inside


def zones(text):
    """-> (front, [record, ...], lines). A record is a heading-delimited BYTE SPAN, never a session."""
    lines = text.splitlines(keepends=True)
    st = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)]
    if not st:
        return text, [], lines
    front = "".join(lines[:st[0]])
    bounds = st + [len(lines)]
    return front, ["".join(lines[a:b]) for a, b in zip(st, bounds[1:])], lines


def label(rec):
    for ln in rec.splitlines():
        if ln.strip():
            return ln.strip()[:90]
    return "(empty record)"


# =====================================================================================
# The four assertions. Each returns a list of failure strings; empty == holds.
# =====================================================================================

def L0(name, text):
    """footer_mode='none' asserted: no standalone `---` after the last record start may
    carry content below it. In a newest-on-top ledger the footer sits exactly where an
    oldest-first cut takes from, so 'none' must mean 'I looked', not 'I did not look'."""
    front, recs, lines = zones(text)
    if not recs:
        return ["L0 %s: no records found — grammar mismatch" % name]
    last = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)][-1]
    out = []
    for i, s, ins in scan(lines):
        if not ins and i > last and s.strip() == "---":
            tail = "".join(lines[i + 1:])
            if tail.strip():
                out.append("L0 %s: trailing file-scoped block at line %d (%d B): %.400s"
                           % (name, i + 1, len(tail.encode()), tail))
    return out


def L1(before_recs, after_recs, shard_recs):
    """Concatenation identity scoped to the RECORDS zone. Operand order is load-bearing:
    this ledger is newest-on-top and the cut takes from the bottom, so retained precedes
    archived. No invert step — TRANSFORM is None, which makes this the strongest form."""
    got = "".join(after_recs) + "".join(shard_recs)
    want = "".join(before_recs)
    if got == want:
        return []
    i = next((n for n, (a, b) in enumerate(zip(got, want)) if a != b), min(len(got), len(want)))
    return ["L1: records-zone concatenation differs at character %d "
            "(retained+archived %d B vs before %d B)"
            % (i, len(got.encode()), len(want.encode()))]


def L2(before_front, after_front, shard_front, shard_recs):
    out = []
    # (a) footer half — inapplicable when FOOTER_MODE == "none"; say so, never claim it held.
    # (b) front-matter half, three unconditional clauses.
    if POINTER not in after_front:
        out.append("L2_POINTER_MISSING: the declared pointer block is not in the live front matter "
                   "verbatim — a severed record set with no pointer to its shard")
    else:
        residue = after_front.replace(POINTER, "", 1)
        if residue != before_front:
            out.append("L2/b1 CONFINEMENT: live front matter changed beyond the declared pointer "
                       "insertion (%d B residue vs %d B before)"
                       % (len(residue.encode()), len(before_front.encode())))
    after_set = set(after_front.splitlines())
    for ln in before_front.splitlines():
        if ln.strip() and ln not in after_set:      # exact membership, never substring (BL-28)
            out.append("L2/b2 SURVIVAL: front-matter line vanished: %r" % ln[:120])
    body = shard_front + "".join(shard_recs)
    for ln in before_front.splitlines():
        s = ln.strip()
        if len(s) > 24 and s in body:
            out.append("L2/b3 NO-LEAK: front-matter line leaked into the shard: %r" % s[:120])
    return out


def L3(before_recs, after_recs, shard_recs):
    """Per-record partition by identity, ORDER and byte-equality. The injected set is
    MEASURED from record content, never baked in as a generation-time constant — that
    constant is why 5 of the 20 proofs shipped across this fleet fail with zero data loss."""
    have = Counter(after_recs) + Counter(shard_recs)
    before_c = Counter(before_recs)
    absent = list((before_c - have).elements())
    added = list((have - before_c).elements())
    out = []
    for r in absent:
        out.append("L3 MISSING: a record from `before` is in neither artifact "
                   "(dropped, or edited so its original bytes exist nowhere): %s" % label(r))
    for r in added:
        # Project strengthening: this design forbids bundling any record edit into the trim
        # commit (two commits, by rule), so a non-zero added count means the rule was broken.
        out.append("L3 ADDED: a record exists that was not in `before` — the trim commit "
                   "bundled a record edit: %s" % label(r))
    if not absent and not added:
        rebuilt, pool = [], Counter(added)
        for r in after_recs + shard_recs:
            if pool[r]:
                pool[r] -= 1
                continue
            rebuilt.append(r)
        bad = [i for i, (a, b) in enumerate(zip(before_recs, rebuilt)) if a != b]
        if bad or len(rebuilt) != len(before_recs):
            out.append("L3 ORDER: records out of order at indices %s" % bad[:12])
    return out


def check(before, after, shard):
    bf, br, _ = zones(before)
    af, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    fails = []
    fails += L0("before", before) + L0("after", after) + L0("shard", shard)
    fails += L1(br, ar, sr)
    fails += L2(bf, af, sf, sr)
    fails += L3(br, ar, sr)
    return fails, (br, ar, sr)


# =====================================================================================
def artifacts():
    sha = subprocess.run(["git", "log", "--diff-filter=A", "-1", "--format=%H", "--", SHARD],
                         capture_output=True, text=True, cwd=ROOT).stdout.strip()
    if sha:
        return (blob("%s^:%s" % (sha, LIVE)), blob("%s:%s" % (sha, LIVE)),
                blob("%s:%s" % (sha, SHARD)), "the trim commit %s" % sha[:7])
    return (blob("HEAD:%s" % LIVE), worktree(LIVE), worktree(SHARD),
            "HEAD vs the working tree (trim not yet committed)")


def self_test(before, after, shard):
    _, ar, _ = zones(after)
    _, sr, _ = zones(shard)
    sf, _, _ = zones(shard)
    purpose = next(ln for ln in zones(before)[0].splitlines() if ln.startswith("**Purpose:**"))

    def sub_in_shard(old, new, count=1):
        assert old in shard, "self-test fixture missing: %r" % old[:40]
        return shard.replace(old, new, count)

    mutants = [
        ("M1 last byte of the shard's last record deleted", before, after, shard[:-1]),
        ("M2 one whole archived record deleted", before, after, shard.replace(sr[5], "", 1)),
        ("M3 one character flipped inside an archived record", before, after,
         sub_in_shard(sr[5], sr[5].replace("e", "3", 1))),
        ("M4 one character flipped inside a retained record", before,
         after.replace(ar[-1], ar[-1].replace("e", "3", 1), 1), shard),
        ("M5 two adjacent archived records swapped", before, after,
         sub_in_shard(sr[5] + sr[6], sr[6] + sr[5])),
        ("M6 a front-matter line moved from the live file into the shard banner", before,
         after.replace(purpose + "\n", "", 1), shard.replace("---\n\n### What Session",
                                                             purpose + "\n\n---\n\n### What Session", 1)),
        ("M7 a trailing file-scoped block appended below the shard's last record", before, after,
         shard + "\n---\n\ntrailing paragraph\n"),
        ("M8 the pointer block dropped from the live front matter", before,
         after.replace(POINTER, "", 1), shard),
        ("M9 the deliberate mojibake normalised", before, after,
         sub_in_shard("âŠ‚", "⊂")),
    ]
    bad = []
    for name, b, a, s in mutants:
        fails, _ = check(b, a, s)
        if not fails:
            bad.append(name)
            print("  SURVIVED  %s" % name)
        else:
            # EVERY assertion that fires, not just the first: it must stay visible that L1
            # is the primary byte-level detector and L3 mostly adds per-record naming on top
            # of it. A reader who thinks L3 is an independent second opinion is mistaken.
            codes = sorted({f.split(":")[0].split(" (")[0] for f in fails})
            print("  caught    %-62s -> %s" % (name, ", ".join(codes)))
    if bad:
        print("\nSELF-TEST FAILED: %d mutant(s) survived. This proof cannot be trusted." % len(bad))
        sys.exit(2)
    print("\nSELF-TEST OK: all %d mutants caught. Losing a byte fails this proof; so does editing one."
          % len(mutants))


before, after, shard, source = artifacts()

if "--self-test" in sys.argv:
    print("--self-test: mutating the artifacts and asserting each mutation is caught.\n")
    self_test(before, after, shard)
    sys.exit(0)

fails, (br, ar, sr) = check(before, after, shard)
have = Counter(ar) + Counter(sr)
added = len(list((have - Counter(br)).elements()))

print("source : %s" % source)
print("grammar: heading /^### What Session \\S+ Did$/ ; footer_mode=none (asserted) ; transform=none")
print("records: %d before = %d retained + %d archived; added by the trim commit: %d"
      % (len(br), len(ar), len(sr), added))
print("checked: L0, L1, L2/front-matter, L3        "
      "<- L2/footer absent: inapplicable, no footer zone")

if fails:
    print("\nFAIL for %s:" % SHARD)
    for f in fails:
        print("  " + f)
    sys.exit(1)

print("\nOK: L0, L1, L2/front-matter, L3 hold for %s" % SHARD)
print("    Every byte of the pre-trim records zone is still present, in the right file,")
print("    unedited, and in order. This says NOTHING about whether the cut point was")
print("    well chosen or whether any record's content is true — a human reads that once.")
print("    A green proof that has never been --self-test'ed proves less than it appears to.")
PYEOF
