#!/usr/bin/env bash
# SESSION_NOTES-S235-through-S232.md.verify.sh — the losslessness proof for this shard.
#
# Generated by Session 239 (the SIXTH trim). Re-runnable, read-only, exits non-zero on failure.
#
#   bash <this>              prove the sixth trim was lossless AND landed where it was declared
#   bash <this> --self-test  prove this proof can FAIL (68 mutants; exit 2 if any survives)
#
# Descended from Session 235's SESSION_NOTES-S231-through-S228.md.verify.sh, itself descended from
# Session 231's, Session 228's, Session 224's and Session 222's — read those for the rationale
# behind L0-L3, L4, L5-L7, L8-L9 and L10-L11. Shards are WRITE-ONCE: this proof pins ITS OWN cut key
# and does not re-prove the earlier shards' cuts. Run all six.
#
# NOTHING INHERITED IS NARROWED OR WEAKENED HERE. The fifth trim narrowed L2/b3 to the banner and
# attached a condition to that narrowing: b3 is safe in the banner-only form ONLY while TRANSFORM
# is None and L1 is present and evaluated. Both hold at this cut (TRANSFORM is None below; L1 runs
# in check()), so the narrowed form is carried forward unchanged. A trim that ever needs a rebase
# must restore b3's records half in the same commit.
#
# ONE ASSERTION IS NEW HERE, and the hole it closes was this lineage's own.
#
#   L12 (ARITHMETIC) — every number a trim states about the SIZE of its own artifacts, derived from
#      those artifacts and held against the prose that states it.
#
#      THE HOLE WAS MEASURED, NOT SUSPECTED. The fifth trim's pointer block says "4 record headings,
#      918 lines"; its banner says "At 976 lines it sits under the 2,000-line agent read cap";
#      BACKLOG.md says "(976 lines)". All three are CORRECT — re-measured while writing this file:
#      that shard is 976 lines, 918 of them records, 4 headings. But grep its proof for either
#      number and every hit is inside a string literal: POINTER, BANNER, and one L8 required string.
#      L2/b1 pins the pointer against a declaration the same author wrote; L6 pins the banner the
#      same way; L8 checks that BACKLOG.md contains the declared characters. Not one of them
#      compares a figure to the artifact. A trim that typed 918 where the truth was 981 would have
#      shipped that in three files at once, green.
#
#      IT IS THE FAILURE CLASS THIS PROJECT REPORTS MOST. Five consecutive sessions before this one
#      self-assessed a numeral typed instead of derived (PROJECT_LEARNINGS #105, #146, #148, #152).
#      A proof lineage that mechanises byte identity to twelve assertions and leaves its own
#      arithmetic to prose has automated the part it was already good at.
#
#      TWO INDEPENDENT HALVES, the same shape L11 uses. The NUMERIC half measures the artifacts and
#      holds them against hand-declared integers (SIZES). The PROSE half holds those integers
#      against the formatted figures that actually appear in the live pointer block, the shard's
#      banner, README.md, BACKLOG.md and CLAUDE.md — ten claims across five texts, in two formats,
#      because this project's prose writes small counts as words ("four record headings") and large
#      ones as digits ("1,057 lines"). Declaring the integers and the prose separately is what keeps
#      each arm independently reachable; deriving one from the other would collapse nine mutants
#      into one.
#
#      ONE NUMBER IN SIZES IS DECLARED AND NOT MEASURED, and saying so is part of the assertion.
#      READ_CAP (2,000) is a property of the agent harness, not of any file in this repository;
#      nothing here can measure it. L12/cap therefore asserts the SHARD is under the declared cap —
#      which is the claim the banner actually makes — and never that the cap itself is right.
#
#      THE MUTANT COUNT IS CHECKED THE SAME WAY, and it is not decoration: the banner tells a reader
#      how thorough --self-test is, and a reader who believes "67" while the file ships 12 has been
#      misled by exactly the mechanism L12 exists to stop. SIZES carries the declared count, the
#      prose half finds it in the banner, and the self-test asserts it equals len(mutants).
#
#      THIS ASSERTION CAUGHT ITS OWN AUTHOR TWICE BEFORE IT SHIPPED, which is the only reason
#      to trust it. The first green run printed "10 prose claims" a few lines under a header
#      that said nine, and the arm loop shipped `retained_records` with no mutant of its own.
#      A typed count and an unreachable arm — the two defects this file exists to make
#      impossible — both in the file that introduces the fix. Neither was reasoned out: the
#      run printed the first and the neuter loop printed the second.
#
# ONE ASSERTION WAS CONSIDERED AND REJECTED, and the measurement is why. CLAUDE.md, this file's
# banner and the pointer block all state in bold that no shard name is a prefix of another, and
# nothing checks it. An L13 was drafted. It was dropped because NO MUTANT CAN REACH IT: every
# rename that creates a prefix or substring relation either points a routing clause at a file that
# cannot be read (L5/4 fires) or points two clauses at one file whose ids then fall outside one of
# their ranges (L5/4 again), and a rename that touches only the declaration is caught by L8/set.
# Shipping an assertion no mutant reaches is the exact defect this lineage has now found three
# times (L2/b0 in the second trim, L5/2 in the third, four more arms in an adversarial sweep of the
# fourth). It is recorded here so the seventh trim does not rediscover the idea and ship it.
#
# MEASURED COVERAGE — every line below was produced by running the loops, not by predicting them.
# Neuter one assertion at a time and re-run --self-test; what survives is what it ALONE catches:
#
#     for A in L0 L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12; do
#       sed "s|^    fails += $A(.*|    pass|" <this> > /tmp/n.sh
#       echo "$A: $(bash /tmp/n.sh --self-test | grep SURVIVED)"; done
#
#     L0 (none)   L1 (none)*  L2 M10,M12-M15,M40,M51   L3 (none)   L4 (none)   L5 M18-M26,
#     M38,M39,M47,M52   L6 M27   L7 M29,M30   L8 M31-M34,M41,M43-M46,M50   L9 M35-M37,M48
#     L10 M53-M55   L11 M56-M59   L12 M60-M68
#
#     * L1's blank entry is NOT a licence to remove it. L3 and L4 happen to catch every mutant L1
#       catches, so nothing depends on L1 ALONE — but L1 is the assertion the fifth trim's
#       narrowing of L2/b3 rests on, and b3's records half is dead only while L1 runs and
#       TRANSFORM is None. Read '(none)' here as 'overlapped', never as 'removable'.
#
# THAT LOOP IS NOT ENOUGH, and this lineage has proved it four times now: the SECOND trim shipped
# L2/b0 reachable by no mutant, the THIRD shipped L5/2's partition arm, an adversarial sweep of the
# FOURTH found four more — and at THIS trim the arm sweep below found two of its own, both in the
# assertion this trim introduces. An assertion is a handful of separate `if`s; neutering the whole
# function cannot tell you that one of those `if`s has never fired. So neuter one `if` at a time as
# well. All 42 arms were swept that way here. The mutant each arm alone catches:
#
#     L2/b3 M51          L5/1 M18-M23,M26     L5/2 shape M47      L5/2 loop M39
#     L5/4 stray M25     L5/4 unread M52      L8/required M50     L8/forbidden M44
#     L8/set M45,M46     L9/no-add M48        L9/missing M36      L9/differs M35,M37
#     L10/no-freeze M53  L10/missing M54      L10/differs M55     L11/fire M56
#     L11/target M57     L11/floor M58        L11/declared M59
#     L12/numeric M60,M61,M62,M68             L12/cap M63
#     L12/prose-literal M65,M66               L12/prose-figure M64,M67
#
# TWO OF THIS TRIM'S OWN ARMS FAILED THAT SWEEP ON THE FIRST TRY, and the fix was a mutant both
# times, never a weakened assertion:
#   * L2/b3 LOST ITS ONLY MUTANT TO L12. The fifth trim's M51 APPENDS a front-matter line to the
#     banner, which under this proof also changes the shard's line count — so L12/shard_total
#     caught it and b3 was left unreachable. M51 now REPLACES a banner line instead, keeping the
#     count identical. A narrowed assertion whose one mutant is stolen by a NEW assertion is
#     retired in silence; that is how an arm dies, and only the loop can tell you it happened.
#   * L12/cap HAD NO MUTANT AT ALL. Moving the declared cap alone also falsifies the banner's
#     prose figure, so L12/prose caught it first. M63 now mis-states the cap CONSISTENTLY —
#     declaration, banner and declared literal together — which is both the isolating mutation and
#     the realistic one.
#
# TWELVE ARMS HAVE NO UNIQUELY-CATCHING MUTANT, and saying which — and why — is more useful than
# inventing contrived ones. This list is MEASURED; do not trust it after editing anything:
#
#   * L0/empty — no artifact mutation can reach it. Emptying a records zone moves bytes, so L1, L3
#     and L4 fire first. It guards a GRAMMAR break, which is not expressible as a mutation of the
#     artifacts. It is a guard rail, and that is the honest name.
#   * L2/b0 — M14, M15 and M40 fire it, but each also breaks b1 and b2, so none depends on it.
#     Kept anyway, because b0 NAMES the cause where b1 only shows bytes. (The fourth trim's header
#     claimed a unique mutant for it; that was measurably false and the fifth trim said so.)
#   * L2/pointer, L2/b1, L2/b2 — mutually covering. M8 trips pointer and L5/1; M10, M12-M15 and
#     M40 trip b1 and b2 together.
#   * L3/MISSING, L3/ADDED, L3/ORDER — subsumed by L1 and L4 on every mutation available here.
#   * L4/retained, L4/archived — subsumed by L5/4 since the third trim added it, as that trim said.
#     Kept: L4 states the cut key directly instead of inferring it, and names both sides on failure.
#   * L5/2 final junction — STRUCTURALLY subsumed: it is the junction between the shard clause and
#     the live clause, and L5/3 pins both exactly, so no single-clause mutation can reach it.
#   * L5/3 shard, L5/3 live — M24 also trips L5/4.
#   * L5/4 vacuous — mutually covering with L5/4 unreadable for a None result.
#   * L8/unreadable and L12/prose-unreadable — MUTUALLY COVERING ACROSS TWO ASSERTIONS, which is
#     weaker than within one, and no mutation available here can separate them: M49 makes
#     README.md unreadable and both fire. L12's only nullable texts ARE L8's four files — its
#     other two, the live pointer and the shard banner, come from the artifacts and can never be
#     None. So the pair is honestly unseparable rather than merely unmutated. If a future trim
#     gives L12 a text L8 does not read, that stops being true and this arm needs its own mutant.
#
# The grammar is FROZEN into this file on purpose: a later change to the trim design must not
# silently change what THIS shard's proof means.
set -euo pipefail
exec python3 - "$@" <<'PYEOF'
import re, subprocess, sys
from collections import Counter

LIVE   = "SESSION_NOTES.md"
SHARD  = "docs/architecture-history/SESSION_NOTES-S235-through-S232.md"
CLAUDE = "CLAUDE.md"
ARCHIVE_DIR = "docs/architecture-history/"

# ---- the declared grammar (inherited unchanged; see the S216 shard's proof for why each clause) --
RECORD_START = re.compile(r"^### What Session (\S+) Did$")
FOOTER_MODE  = "none"     # ASSERTED by L0, not "don't look"
TRANSFORM    = None       # no rebase: the archived span is a pure byte slice
REGEN        = ()         # no regenerated front-matter fields — declared-empty, not unchecked

# `\S+` not `\d+`; `Did$` anchored; column-0 match. This cut's archived span contains NO duplicate
# heading and NO fenced block (measured: 4 headings, 0 fence lines). The RETAINED span, unusually,
# contains TWO near-empty records — Session 239's own Phase 1B stub and Session 238's abandoned
# claim — and neither is special-cased: a record is a byte span, so a stub rides through L1, L3 and
# L4 exactly as a 300-line record does. `\S+` still matters because L5 opens the S216 shard, whose
# ids include `20B` and `20A`, and a `\d+` grammar would merge them.

# ---- the declared CUT KEY. Hand-supplied, never read back from the artifacts (that would be
#      circular). L4 holds the records against it; L5 holds the prose routing tables against it. ----
CUT_RETAINED = ("239", "238", "237", "236")
CUT_ARCHIVED = ("235", "234", "233", "232")

# ---- the declared ROUTING table: (lower, upper, file). None means open on that side. Every copy
#      of this table in prose must parse to exactly this, and this must agree with the cut key AND
#      with what the named files actually contain. ----
ROUTING = (
    (None, 216,  "SESSION_NOTES-through-S216.md"),
    (217,  220,  "SESSION_NOTES-S220-through-S217.md"),
    (221,  224,  "SESSION_NOTES-S224-through-S221.md"),
    (225,  227,  "SESSION_NOTES-S227-through-S225.md"),
    (228,  231,  "SESSION_NOTES-S231-through-S228.md"),
    (232,  235,  "SESSION_NOTES-S235-through-S232.md"),
    (236,  None, "SESSION_NOTES.md"),
)

# ---- L8's files, and what this trim declares must (and must not) be true of each. The required
#      strings are hand-declared; the shard-name set is derived from ROUTING above.
#
#      THE LIST WAS RE-DERIVED, NOT COPIED, and this time the sweep returned NOTHING NEW — which is
#      a result worth writing down rather than a formality skipped. `git grep -l 'SESSION_NOTES-'`
#      returns nine files: these four, SESSION_NOTES.md itself (L2 and L5 read it), and FOUR the
#      fifth trim's sweep never named — CHANGELOG.md, PROJECT_LEARNINGS.md,
#      docs/architecture-history/evolution-page-plan.md and docs/planning/repository-rename.md.
#      NONE of the four is declared, and declaring any of them would have shipped a falsehood:
#        * CHANGELOG.md and evolution-page-plan.md match only on the phrase `SESSION_NOTES-as-
#          rationale`, which is not a filename. The sweep STRING over-matches; the refined form
#          `git grep -l 'SESSION_NOTES-[A-Za-z0-9-]*\.md'` drops both, and the seventh trim should
#          use it.
#        * PROJECT_LEARNINGS.md (rows 35, 39, 42, 126) and repository-rename.md (:211, :299, :1256)
#          cite shard filenames inside FROZEN HISTORICAL statements — "all 58 such headings moved
#          to SESSION_NOTES-through-S216.md", a rename-era inventory, a grep receipt. Each was true
#          when written and is true now. None states how many shards exist. And L8/set requires a
#          declared file to name the WHOLE shard set, so declaring either would have turned a
#          correct record RED for the crime of being about one shard.
#      That is the fifth trim's own rule — sweep for the class, never trust the list — applied and
#      returning nothing. Sweep again at the seventh trim rather than trusting this paragraph. ----
README      = "README.md"
CONVENTIONS = "docs/methodology/PROJECT_CONVENTIONS.md"
BACKLOG     = "BACKLOG.md"
REACH = (
    (README,
     ("  SESSION_NOTES-S235-through-S232.md    # frozen SESSION_NOTES records, Sessions 235->232 (grep it; do not Read it)\n",
      "older in the six shards above"),
     ("older in the five shards above",)),
    # README.md's "L9 (write-once for all four shards)" comment is NOT declared here and is NOT
    # stale — it describes what the FOURTH trim's proof does, and that proof guards four shards.
    # A count word is stale only if it is a claim about the present. Inherited unchanged from the
    # fifth trim, which recorded the same reasoning after its sweep flagged the same line.
    (CONVENTIONS,
     ("**Six instances so far**",
      "`SESSION_NOTES-S235-through-S232.md` (Session 239, Sessions 235→232)"),
     ("**Five instances so far**",)),
    (BACKLOG,
     ("there are now **six** unwatched shards",
      "Session 239 a sixth**",
      "the five newer ones read whole today"),
     ("there are now **five** unwatched shards",
      "Session 235 a fifth** (933, 790 and 976 lines)",
      "the four newer ones read whole today")),
    # BACKLOG.md's two SIZE figures for this shard are deliberately NOT declared here. They are
    # L12/prose's, and a string that both assertions read gives L12 no mutant of its own.
    (CLAUDE,
     ("there are SIX, and a lookup must consult all of them",
      "**Trimmed six times (Sessions 222, 224, 228, 231, 235, 239):**",
      "Retired records live in **six** write-once shards",
      "grep *all six*",
      "### `SESSION_NOTES.md` is trimmed (Sessions 222, 224, 228, 231, 235, 239)\n",
      "(The five newer shards are under the 2,000-line cap today; that is luck, not protection.)",
      "Session 239 added **L12**",
      "Copy all of L0–L12 forward",
      "all four are falsified and none may be repaired"),
     ("there are FIVE", "Trimmed five times", "**five** write-once shards", "grep *all five*",
      "is trimmed (Sessions 222, 224, 228, 231, 235)\n",
      "(The four newer shards are under the 2,000-line cap today",
      "Copy all of L0–L11 forward",
      "all three are falsified and none may be repaired")),
)
# The negative lookahead is load-bearing: without it this matches the `.md` PREFIX inside
# `...-S224-through-S221.md.verify.sh`, so README.md — which lists a shard and its proof on two
# lines — could lose a shard's own repo-map line and still yield the complete name set. Measured
# during the fourth trim's review; M46 is the mutant that catches it.
SHARD_NAME = re.compile(r"SESSION_NOTES-[A-Za-z0-9-]*\.md(?!\.verify)")

# ---- L9's scope: every shard OLDER than this one. Each is compared against the blob committed at
#      the commit that added IT, never at this trim's commit. ----
ANCESTORS = tuple(ARCHIVE_DIR + d for _lo, _hi, d in ROUTING
                  if d != LIVE and d != SHARD.rsplit("/", 1)[1])

# ---- L10's scope: every ancestor shard's PROOF, and the commit each was frozen at. HAND-DECLARED,
#      because no commit git can derive means "the session that wrote this proof ended" — see the
#      fifth trim's header. Four are inherited unchanged. The fifth, `a7512cb`, is the S231 proof's
#      own add-commit: MEASURED here, not assumed — `git log -- <that proof>` prints exactly one
#      commit, so unlike the S227 proof (which its own session amended at close-out) its add-blob
#      and its disk bytes are the same file. ----
ANCESTOR_PROOFS = (
    (ARCHIVE_DIR + "SESSION_NOTES-through-S216.md.verify.sh",
     "a9510ca58ffeb76fef274d848733e3c636d0048b"),
    (ARCHIVE_DIR + "SESSION_NOTES-S220-through-S217.md.verify.sh",
     "07e1ab93317019607a4699dd6a2c96b9900e6e7c"),
    (ARCHIVE_DIR + "SESSION_NOTES-S224-through-S221.md.verify.sh",
     "e4ca9441a1ae2c6df3192050754bc2284e92f444"),
    (ARCHIVE_DIR + "SESSION_NOTES-S227-through-S225.md.verify.sh",
     "e314449fe63374452626335444d3e0be92e840c4"),
    (ARCHIVE_DIR + "SESSION_NOTES-S231-through-S228.md.verify.sh",
     "a7512cb96cb80b23f3ebeeb7a660acfde4068913"),
)

# ---- L11's declaration: the retention rule this trim exists to satisfy, as `CLAUDE.md` states it.
#      Inherited unchanged — this cut did not touch the numbers. The integers and the prose are
#      declared SEPARATELY on purpose; see the fifth trim's header. ----
POLICY = (1500, 1050, 4,
          ("Fire a new trim when the live file exceeds **1,500 lines**",
           "cut back to **≤1,050 lines**",
           "never retain fewer than **4** sessions"))

# ---- L12's declaration. SIZES holds the integers; SIZE_PROSE holds the formatted claims and names
#      which measurement each must carry. `mutants` is the count --self-test ships, which the
#      self-test itself asserts against len(mutants).
#      Measurements: archived_headings, archived_lines, shard_total are read off the artifacts;
#      retained_records off the live file; read_cap is DECLARED (nothing here can measure the agent
#      read cap) and is used only to assert the shard sits under it. ----
SIZES = {
    "archived_headings": 4,
    "archived_lines":    1004,
    "shard_total":       1057,
    "retained_records":  4,
    "read_cap":          2000,
    "mutants":           68,
}
WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
         7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve"}
# (which text, the literal that must appear in it, "num"|"word", the measurements it must carry)
SIZE_PROSE = (
    ("live pointer", "4 record headings, 1,004 lines", "num",
     ("archived_headings", "archived_lines")),
    ("live pointer", "only** — four records", "word", ("retained_records",)),
    ("shard banner", "Sessions 235 → 232 — four record", "word", ("archived_headings",)),
    ("shard banner", "headings, 1,004 lines", "num", ("archived_lines",)),
    ("shard banner", "At 1,057 lines it sits under the 2,000-line agent read", "num",
     ("shard_total", "read_cap")),
    ("shard banner", "mutates the artifacts 68 ways", "num", ("mutants",)),
    (README, "newest 4 sessions", "num", ("retained_records",)),
    (BACKLOG, "`SESSION_NOTES-S235-through-S232.md` (1,057 lines)", "num", ("shard_total",)),
    (BACKLOG, "976 and 1,057 lines", "num", ("shard_total",)),
    (CLAUDE, "(235→232, 1,057 lines)", "num", ("shard_total",)),
)

POINTER = r"""**Sixth trim (Session 239). Archived Sessions 235 → 232 — 4 record headings, 1,004 lines** into
[`docs/architecture-history/SESSION_NOTES-S235-through-S232.md`](docs/architecture-history/SESSION_NOTES-S235-through-S232.md)
— same shape, same newest-on-top order, frozen and byte-for-byte unedited. **This live file now
holds Sessions 239 → 236 only** — four records, the floor `CLAUDE.md` sets. Its proof is
[`SESSION_NOTES-S235-through-S232.md.verify.sh`](docs/architecture-history/SESSION_NOTES-S235-through-S232.md.verify.sh):
the twelve assertions inherited from the fifth trim, none of them narrowed or weakened, plus
**L12** — every number this trim states about the size of its own artifacts, derived from the
artifacts and held against the prose that states it.

**L12 exists because the fifth trim's own figures were checked by nothing, and this is the defect
this project reports most.** That trim's pointer block says *"4 record headings, 918 lines"*, its
banner says *"At 976 lines it sits under the 2,000-line agent read cap"*, and `BACKLOG.md` says
*"(976 lines)"*. **All three are correct** — re-measured at this cut: 976 lines, 918 of them
records. But nothing compared any of them to the artifact. They are literal text, pinned by L2/b1
and L6 against a declaration the same author wrote, so a trim that typed the wrong figure would
have shipped it green in three places at once — and five consecutive sessions have now
self-reported a numeral typed instead of derived. L12 measures the archived heading count, the
archived line count and the shard's total line count; holds all three against hand-declared
integers; asserts the shard is under the read cap it claims to be under; and holds those integers
against the formatted numbers that actually appear in this block, in the shard's banner, in
`README.md` and in `BACKLOG.md`. Two independent halves, six arms, nine mutants.

**Six shards exist now, and none is a prefix of any other.** To place Session N, open the file
this table names. **This block is the authority**, and these seven clauses are machine-checked here,
in the shard's banner, and in `CLAUDE.md`:

**N ≤ 216** → `SESSION_NOTES-through-S216.md`; **217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;
**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`; **225 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`;
**228 ≤ N ≤ 231** → `SESSION_NOTES-S231-through-S228.md`; **232 ≤ N ≤ 235** → `SESSION_NOTES-S235-through-S232.md`;
**N ≥ 236** → `SESSION_NOTES.md`.

`grep` the shards; `Read` none of them. **Shards stay write-once** — a seventh trim writes a
seventh file; it never appends to one of these six.

**Four shard banners are stale now, and none may be repaired.** The S220 shard's still says *"the
live ledger when N ≥ 221"*; the S224 shard's still routes Sessions 225 and up to this file; the
S227 shard's routes Sessions 228 and up here too; and the S231 shard's — which predicted in its own
text that it would join them "at the sixth trim" — now has. All four were true at their own cut.
The S220 proof predates L5; the S224, S227 and S231 proofs have L5 but read their artifacts at
their own trim commits, so none of the four can notice, and ours will join them at the seventh
trim. **A shard banner is a snapshot of its own cut; this block is the authority.**

**The sweep was re-run and found no new copy — which is a result, not a formality.**
`git grep -l 'SESSION_NOTES-'` returns nine files: the four L8 already reads, this one, and **four
that are new since the fifth trim swept** — `CHANGELOG.md`, `PROJECT_LEARNINGS.md`,
`docs/architecture-history/evolution-page-plan.md` and `docs/planning/repository-rename.md`.
**None of the four is a copy of the shard census, and declaring any of them would have shipped a
falsehood.** `CHANGELOG.md` and the evolution plan match only on the phrase
`SESSION_NOTES-as-rationale`, which is not a filename — the sweep string over-matches, and
`git grep -l 'SESSION_NOTES-[A-Za-z0-9-]*\.md'` drops both. The other two cite shard filenames
inside frozen historical statements that were true when written and are true now, and neither says
how many shards exist; because `L8/set` requires a declared file to name the *whole* set, declaring
either would have turned a correct record red. That is the fifth trim's own rule — sweep for the
class, never trust the list — applied and, this time, returning nothing. **Sweep again at the
seventh trim rather than trusting this paragraph either.**

**The five blocks below are frozen at the FIFTH, FOURTH, THIRD, SECOND and FIRST trims and describe
THOSE cuts.** This trim falsified exactly three passages of the fifth trim's block — its claim about
which sessions this live file holds, its whole routing paragraph, and its count of how many shard
banners are stale — and rewrote all three as declared substitutions the proof checks by exact
equality. Every other byte of that block is original, and the fourth, third, second and first
trims' blocks are untouched. Each earlier proof reads its artifacts from the commit that added its
own shard, so this trim cannot disturb any of them; all five were re-run green at this cut, and a
session that doubts that should run them rather than reason about it.

"""


BANNER = """# Session Notes — archive shard: Sessions 235 → 232

**Frozen. Write-once. Do not edit this file.** It holds the record byte spans that the sixth trim
(Session 239, 2026-08-24) removed from `SESSION_NOTES.md`: Sessions 235 → 232 — four record
headings, 1,004 lines — in the same newest-on-top order, byte-for-byte unedited.

**This shard is the sixth of six, and the newest of them.** No shard is a prefix of another, and
none is authoritative alone. Session N lives in:

**N ≤ 216** → `SESSION_NOTES-through-S216.md`;
**217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;
**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`;
**225 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`;
**228 ≤ N ≤ 231** → `SESSION_NOTES-S231-through-S228.md`;
**232 ≤ N ≤ 235** → `SESSION_NOTES-S235-through-S232.md`;
**N ≥ 236** → `SESSION_NOTES.md`.

*(One clause per line, deliberately, inherited from the fourth trim's banner: the two-per-line wrap
the pointer block uses puts the first two clauses on a line byte-identical to the pre-trim front
matter's, and the proof's L2/b3 NO-LEAK assertion cannot tell that coincidence from a front-matter
line that leaked into this banner. It caught exactly that on the fourth trim's first run.)*

**That table is a snapshot of the cut that wrote it.** A routing table inside a write-once file
cannot be repaired when the next trim lands, so the pointer block in `SESSION_NOTES.md` is the
authority and this is a convenience copy. FOUR banners already prove the hazard rather than merely
warning of it: the S220 shard's still says *"the live ledger when N ≥ 221"*, the S224 shard's still
routes Sessions 225 and up to the live ledger, the S227 shard's does the same for Sessions 228 and
up, and the S231 shard's — which predicted its own staleness "at the sixth trim" — is now stale
exactly as predicted. All four were true when written. This one joins them at the seventh trim.

**`grep` this file; do not `Read` it.** At 1,057 lines it sits under the 2,000-line agent read
cap today — but that cap truncates in silence, with no error and no missing-data marker, and no
fleet tooling watches this path (the dashboard's `READ_CAP_WATCHED` is an exact-path set that does
not contain it). That size is final: shards are write-once, so a seventh trim creates a seventh
file rather than growing this one.

**Provenance is proved here, not asserted.** Run `SESSION_NOTES-S235-through-S232.md.verify.sh`,
beside this file. It re-derives L0-L11 from the fifth trim's proof — narrowing nothing, weakening
nothing — and adds **L12**, which holds every number this trim states about the size of its own
artifacts against a measurement of those artifacts. That hole was real and it was this lineage's
own: the fifth trim's three size figures were correct and checked by nothing, while the defect its
sessions self-report most often is a numeral typed instead of derived. Under `--self-test` this
proof mutates the artifacts 68 ways and fails if any mutation goes uncaught. Do not believe
this paragraph — run it.

**Cutting is by byte position, never by authorship.** Session 235's handoff evaluation is filed
inside Session 236's record, because this ledger files an evaluation under its author — so that
evaluation stayed behind in the live file while Session 235's own record came here. The same seam
brought Session 231's evaluation INTO this file, inside Session 232's record, out of the live file
where the fifth trim had left it. Expect this at every boundary, in both directions.

---

"""


# The ONLY edits to pre-existing front matter. Exact, uniquely anchored, checked by equality.
FRONT_SUBST = (
    ("""— same shape, same newest-on-top order, frozen and byte-for-byte unedited. **This live file now
holds Sessions 235 → 232 only** — four sessions, the floor `CLAUDE.md` sets. Its proof is
""",
     """— same shape, same newest-on-top order, frozen and byte-for-byte unedited. At that fifth cut
this live file was left holding Sessions 235 → 232 — four sessions, the floor `CLAUDE.md`
sets; the sixth trim above has since cut it again. Its proof is
"""),
    ("""**Five shards exist now, and none is a prefix of any other.** To place Session N, open the file
this table names. **This block is the authority**, and these six clauses are machine-checked here,
in the shard's banner, and in `CLAUDE.md`:

**N ≤ 216** → `SESSION_NOTES-through-S216.md`; **217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;
**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`; **225 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`;
**228 ≤ N ≤ 231** → `SESSION_NOTES-S231-through-S228.md`; **N ≥ 232** → `SESSION_NOTES.md`.

`grep` the shards; `Read` none of them. **Shards stay write-once** — a sixth trim writes a sixth
file; it never appends to one of these five.
""",
     """**Five shards existed at that cut, and none was a prefix of any other.** The routing table that
stood here named those five and sent every session from 232 up to this live file; the sixth trim
falsified that last clause — Sessions 235 → 232 are in a shard now — and the table above replaces
it. `grep` the shards; `Read` none. **Shards stay write-once** — a sixth trim wrote a sixth file;
it did not append to one of those five.
"""),
    ("""**Three shard banners are stale now, and none may be repaired.** The S220 shard's still says *"the
live ledger when N ≥ 221"*; the S224 shard's still routes Sessions 225 and up to this file; and the
S227 shard's — which predicted in its own text that it would "join them at the fifth trim" — now
has. All three were true at their own cut. The S220 proof predates L5; the S224 and S227 proofs have
L5 but read their artifacts at their own trim commits, so none of the three can notice, and ours
will join them at the sixth trim.""",
     """**Three shard banners were stale at that cut; four are now.** The S220 shard's still says *"the
live ledger when N ≥ 221"*; the S224 shard's still routes Sessions 225 and up to this file; the
S227 shard's does the same for Sessions 228 and up; and the S231 shard's own prediction that it
would join them "at the sixth trim" has come true. All four were true at their own cut. The S220
proof predates L5; the S224, S227 and S231 proofs have L5 but read their artifacts at their own
trim commits, so none of the four can notice."""),
)


MISSING = object()      # L7/L9/L10: the file is absent from the working tree
NA      = object()      # L7: inapplicable — the trim is not committed yet

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, check=True).stdout.strip()


def blob(ref):
    r = subprocess.run(["git", "show", ref], capture_output=True, cwd=ROOT)
    if r.returncode:
        sys.exit("cannot read %s: %s" % (ref, r.stderr.decode("utf-8", "replace").strip()))
    return r.stdout.decode("utf-8")          # bytes -> str; never $(...) which eats trailing newlines


def worktree(rel):
    with open("%s/%s" % (ROOT, rel), encoding="utf-8", newline="") as fh:
        return fh.read()


def added_at(rel):
    """The commit that ADDED `rel`, or "" if git does not know of one."""
    return subprocess.run(["git", "log", "--diff-filter=A", "-1", "--format=%H", "--", rel],
                          capture_output=True, text=True, cwd=ROOT).stdout.strip()


def scan(lines):
    inside = False
    for i, raw in enumerate(lines):
        s = raw.rstrip("\r\n")
        if s.startswith("```") or s.startswith("~~~"):
            yield i, s, inside
            inside = not inside
            continue
        yield i, s, inside


def zones(text):
    """-> (front, [record, ...], lines). A record is a heading-delimited BYTE SPAN, never a session."""
    lines = text.splitlines(keepends=True)
    st = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)]
    if not st:
        return text, [], lines
    front = "".join(lines[:st[0]])
    bounds = st + [len(lines)]
    return front, ["".join(lines[a:b]) for a, b in zip(st, bounds[1:])], lines


def label(rec):
    for ln in rec.splitlines():
        if ln.strip():
            return ln.strip()[:90]
    return "(empty record)"


def ids(recs):
    """The session id captured from each record's own heading line, in order."""
    return tuple(RECORD_START.match(r.splitlines()[0]).group(1) for r in recs)


def declared(before_front):
    """The front matter this trim is ALLOWED to produce, before the pointer is inserted."""
    for old, new in FRONT_SUBST:
        before_front = before_front.replace(old, new, 1)
    return before_front


# One canonical clause shape, so all three copies of the table parse with one regex. Bounds AND
# destination in a single match: parsing them separately is what let the third trim's first draft
# of L5 check the numbers of a table whose filenames were swapped.
ROUTE_CLAUSE = re.compile(r"\*\*(?:(\d+) ≤ N ≤ (\d+)|N ≤ (\d+)|N ≥ (\d+))\*\* → `([^`]+)`")


def parse_table(text):
    out = []
    for a, b, le, ge, dest in ROUTE_CLAUSE.findall(text):
        if a:
            out.append((int(a), int(b), dest))
        elif le:
            out.append((None, int(le), dest))
        else:
            out.append((int(ge), None, dest))
    return tuple(out)


_ID_CACHE = {}


def numeric_ids(dest, after, shard, sha):
    """The numeric session ids actually present in the file `dest` names. LIVE and SHARD come from
    the artifacts already in hand so a mutant can move them; the earlier shards are read once from
    the same commit as everything else. Non-numeric ids (`20B`, `20A`) are dropped, and a
    destination that yields none is reported rather than passing vacuously."""
    if dest == LIVE:
        text = after
    elif dest == SHARD.rsplit("/", 1)[1]:
        text = shard
    else:
        key = (dest, sha)
        if key not in _ID_CACHE:
            path = ARCHIVE_DIR + dest
            try:
                _ID_CACHE[key] = blob("%s:%s" % (sha, path)) if sha else worktree(path)
            except (SystemExit, OSError):
                _ID_CACHE[key] = None
        text = _ID_CACHE[key]
        if text is None:
            return None
    return sorted(int(i) for i in ids(zones(text)[1]) if i.isdigit())


# =====================================================================================
# The assertions. Each returns a list of failure strings; empty == holds.
# =====================================================================================

def L0(name, text):
    """footer_mode='none' asserted: no standalone `---` after the last record start may carry
    content below it. In a newest-on-top ledger the footer sits exactly where an oldest-first cut
    takes from, so 'none' must mean 'I looked', not 'I did not look'."""
    front, recs, lines = zones(text)
    if not recs:
        return ["L0 %s: no records found — grammar mismatch" % name]
    last = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)][-1]
    out = []
    for i, s, ins in scan(lines):
        if not ins and i > last and s.strip() == "---":
            tail = "".join(lines[i + 1:])
            if tail.strip():
                out.append("L0 %s: trailing file-scoped block at line %d (%d B): %.400s"
                           % (name, i + 1, len(tail.encode()), tail))
    return out


def L1(before_recs, after_recs, shard_recs):
    """Concatenation identity scoped to the RECORDS zone. Operand order is load-bearing: this
    ledger is newest-on-top and the cut takes from the bottom, so retained precedes archived. No
    invert step — TRANSFORM is None, which makes this the strongest form. This is the PRIMARY
    byte-level detector; L3 adds per-record naming on top of it, and L4-L12 see what both are
    blind to. It is ALSO what makes L2/b3's records half redundant — see the fifth trim's header,
    whose condition (TRANSFORM is None, L1 present) is re-checked at this cut and still holds."""
    got = "".join(after_recs) + "".join(shard_recs)
    want = "".join(before_recs)
    if got == want:
        return []
    i = next((n for n, (a, b) in enumerate(zip(got, want)) if a != b), min(len(got), len(want)))
    return ["L1: records-zone concatenation differs at character %d "
            "(retained+archived %d B vs before %d B)"
            % (i, len(got.encode()), len(want.encode()))]


def L2(before_front, after_front, shard_front, shard_recs, pointer):
    out = []
    # (a) footer half — inapplicable when FOOTER_MODE == "none"; say so, never claim it held.
    # (b) front-matter half. b1 is exact and subsumes b2; b2 and b3 still run because b1 is
    #     SKIPPED when the pointer is absent, and b3 is independent of all of it.
    for k, (old, _new) in enumerate(FRONT_SUBST, 1):
        if before_front.count(old) != 1:
            out.append("L2/b0 SUBSTITUTION %d NOT UNIQUELY ANCHORED: its source text occurs %d "
                       "times in the before front matter (want exactly 1) — the declaration has "
                       "gone stale against the file it claims to describe" % (k, before_front.count(old)))
    want_front = declared(before_front)
    if pointer not in after_front:
        out.append("L2_POINTER_MISSING: the declared pointer block is not in the live front matter "
                   "verbatim — a severed record set with no pointer to its shard")
    else:
        residue = after_front.replace(pointer, "", 1)
        if residue != want_front:
            i = next((n for n, (a, b) in enumerate(zip(residue, want_front)) if a != b),
                     min(len(residue), len(want_front)))
            out.append("L2/b1 CONFINEMENT: live front matter changed beyond the declared pointer "
                       "insertion + the %d declared substitutions; first divergence at character "
                       "%d (%d B residue vs %d B declared)"
                       % (len(FRONT_SUBST), i, len(residue.encode()), len(want_front.encode())))
    after_set = set(after_front.splitlines())
    for ln in want_front.splitlines():
        if ln.strip() and ln not in after_set:      # exact membership, never substring (BL-28)
            out.append("L2/b2 SURVIVAL: front-matter line vanished: %r" % ln[:120])
    # b3 NO-LEAK, narrowed to the BANNER by the fifth trim and carried forward unchanged. The
    # records half is pinned byte-for-byte by L1, so a front-matter line found there was already
    # there before the cut — history, not a leak — while the banner is new text L1 never sees and
    # L6 only compares against a declaration the same author wrote. `noleak_note()` prints what the
    # pre-narrowing predicate would have said, so nothing is hidden.
    for ln in before_front.splitlines():
        s = ln.strip()
        if len(s) > 24 and s in shard_front:
            out.append("L2/b3 NO-LEAK: front-matter line leaked into the shard's banner: %r" % s[:120])
    return out


def noleak_note(before_front, shard_recs):
    """NOT an assertion. The lines the pre-narrowing b3 would have flagged in the records half, so
    the narrowing hides nothing from a reader who wants to judge it."""
    body = "".join(shard_recs)
    return [(i, ln.strip()) for i, ln in enumerate(before_front.splitlines(), 1)
            if len(ln.strip()) > 24 and ln.strip() in body]


def L3(before_recs, after_recs, shard_recs):
    """Per-record partition by identity, ORDER and byte-equality. The injected set is MEASURED from
    record content, never baked in as a generation-time constant — that constant is why 5 of the 20
    proofs shipped across this fleet fail with zero data loss."""
    have = Counter(after_recs) + Counter(shard_recs)
    before_c = Counter(before_recs)
    absent = list((before_c - have).elements())
    added = list((have - before_c).elements())
    out = []
    for r in absent:
        out.append("L3 MISSING: a record from `before` is in neither artifact "
                   "(dropped, or edited so its original bytes exist nowhere): %s" % label(r))
    for r in added:
        # Project strengthening: this design forbids bundling any record edit into the trim commit
        # (three commits, by rule — claim, trim, close-out), so a non-zero added count means the
        # rule was broken. Deliberate divergence from the canonical tool, which downgraded this to
        # a note in v1.2.0 because the canonical repo bundles by practice.
        out.append("L3 ADDED: a record exists that was not in `before` — the trim commit "
                   "bundled a record edit: %s" % label(r))
    if not absent and not added:
        rebuilt, pool = [], Counter(added)
        for r in after_recs + shard_recs:
            if pool[r]:
                pool[r] -= 1
                continue
            rebuilt.append(r)
        bad = [i for i, (a, b) in enumerate(zip(before_recs, rebuilt)) if a != b]
        if bad or len(rebuilt) != len(before_recs):
            out.append("L3 ORDER: records out of order at indices %s" % bad[:12])
    return out


def L4(after_recs, shard_recs):
    """The cut point itself. L1 and L3 are blind to a whole-record boundary shift because it
    preserves concatenation, multiset membership and order simultaneously. This compares each side
    against the HAND-DECLARED cut key; reading the key back out of the artifacts would make it a
    restatement rather than an assertion."""
    out = []
    got_a, got_s = ids(after_recs), ids(shard_recs)
    if got_a != CUT_RETAINED:
        out.append("L4 CUT/retained: the live file holds Sessions %s; the declared cut key says %s"
                   % (list(got_a), list(CUT_RETAINED)))
    if got_s != CUT_ARCHIVED:
        out.append("L4 CUT/archived: the shard holds Sessions %s; the declared cut key says %s"
                   % (list(got_s), list(CUT_ARCHIVED)))
    return out


def L5(after_front, shard_front, claude, after, shard, sha, routing):
    """Routing coherence — see the third trim's proof for the full rationale. Everything above is
    about BYTES. This is about the sentence a human acts on: which file to open for Session N.
    Five layers, because each catches something the others cannot."""
    out = []
    lo_a, hi_a = min(map(int, CUT_ARCHIVED)), max(map(int, CUT_ARCHIVED))
    lo_r = min(map(int, CUT_RETAINED))
    shard_base = SHARD.rsplit("/", 1)[1]

    # (1) every prose copy of the table must parse to exactly the declaration — bounds AND file.
    for who, text in (("live pointer", after_front), ("shard banner", shard_front),
                      ("CLAUDE.md", claude)):
        got = parse_table(text)
        if got != routing:
            out.append("L5/1 %s: its routing table parses to %s; the declaration says %s"
                       % (who, list(got), list(routing)))

    # (2) the declaration must partition the session-id space: one open below, one open above,
    #     contiguous in between, no gap and no overlap.
    below = [c for c in routing if c[0] is None]
    above = [c for c in routing if c[1] is None]
    if len(below) != 1 or len(above) != 1 or routing[0][0] is not None or routing[-1][1] is not None:
        out.append("L5/2 shape: want exactly one open-below clause first and one open-above clause "
                   "last; got %d and %d in %s" % (len(below), len(above), list(routing)))
    else:
        edge = routing[0][1]
        for lo, hi, dest in routing[1:-1]:
            if lo != edge + 1:
                out.append("L5/2 %s at %d-%d (`%s`): the preceding clause ends at %d"
                           % ("GAP" if lo > edge + 1 else "OVERLAP", lo, hi, dest, edge))
            edge = hi
        if routing[-1][0] != edge + 1:
            out.append("L5/2 %s between the last range (ends %d) and `N >= %d` (`%s`)"
                       % ("GAP" if routing[-1][0] > edge + 1 else "OVERLAP", edge,
                          routing[-1][0], routing[-1][2]))

    # (3) the clause naming THIS shard must be exactly this cut's archived span, and the clause
    #     naming the live ledger must open exactly at this cut's retained floor.
    mine = [c for c in routing if c[2] == shard_base]
    live = [c for c in routing if c[2] == LIVE]
    if len(mine) != 1 or mine[0][:2] != (lo_a, hi_a):
        out.append("L5/3 shard clause: the table routes %s to `%s`; this cut archived Sessions "
                   "%d-%d" % ([c[:2] for c in mine], shard_base, lo_a, hi_a))
    if len(live) != 1 or live[0][:2] != (lo_r, None):
        out.append("L5/3 live clause: the table routes %s to `%s`; this cut retained Sessions "
                   "%d and up" % ([c[:2] for c in live], LIVE, lo_r))

    # (4) THE ANCHOR AGAINST REALITY. A declaration can be wrong in a way that is perfectly
    #     self-consistent — move a boundary in every copy at once and (1)-(3) all still hold. So
    #     open each file the table names and check what is actually in it.
    for lo, hi, dest in routing:
        found = numeric_ids(dest, after, shard, sha)
        if found is None:
            out.append("L5/4 `%s`: the table routes Sessions %s-%s here and the file cannot be "
                       "read" % (dest, lo, hi))
            continue
        if not found:
            out.append("L5/4 `%s`: no numeric session ids found — the check would pass vacuously"
                       % dest)
            continue
        stray = [n for n in found if (lo is not None and n < lo) or (hi is not None and n > hi)]
        if stray:
            out.append("L5/4 `%s`: routed Sessions %s-%s, but it actually contains %s (ids %d-%d)"
                       % (dest, lo, hi, stray[:8], found[0], found[-1]))
    return out


def L6(shard_front, banner):
    """The shard banner, pinned byte-for-byte — the shard-side analogue of L2/b1. Without it the
    banner is the one part of the shard that is neither frozen nor checked, while its own text says
    provenance is proved here."""
    if shard_front == banner:
        return []
    i = next((n for n, (a, b) in enumerate(zip(shard_front, banner)) if a != b),
             min(len(shard_front), len(banner)))
    return ["L6 BANNER: the shard's banner is not the declared text; first divergence at character "
            "%d (%d B in the shard vs %d B declared)"
            % (i, len(shard_front.encode()), len(banner.encode()))]


def L7(sha, shard_blob, disk):
    """Write-once, enforced, for THIS shard. Everything else reads history at the trim commit, so
    the suite stays green through any later truncation or deletion of it. Asymmetric on purpose:
    the live ledger is SUPPOSED to change and is never compared this way.

    Applicability is decided by `disk` ALONE and never by `sha` — see the third trim's proof for
    why a stand-in sha makes every mutant 'caught' for the wrong reason."""
    if disk is NA:
        return []                      # not committed yet; the run banner says so rather than
                                       # letting silence read as a pass
    if disk is MISSING:
        return ["L7 WRITE-ONCE: the shard is GONE from the working tree. Every assertion above "
                "still passes because they read git history at the trim commit — this one is the "
                "reason you found out."]
    if disk != shard_blob:
        i = next((n for n, (a, b) in enumerate(zip(disk, shard_blob)) if a != b),
                 min(len(disk), len(shard_blob)))
        return ["L7 WRITE-ONCE: the shard on disk is not the shard committed at %s; first "
                "divergence at character %d (%d B on disk vs %d B committed). Shards are "
                "write-once; this file was edited after its trim."
                % (sha[:7] if sha else "the trim commit", i,
                   len(disk.encode()), len(shard_blob.encode()))]
    return []


def L8(reach_texts, routing):
    """The copies that live outside every earlier proof. Both halves matter and neither subsumes
    the other: the hand-declared strings catch a stale COUNT WORD, which is prose and invisible to
    any derived check; the ROUTING-derived set catches a shard left out or a phantom one, without
    restating the list a second time and giving it a second chance to go stale.

    `routing` is the DECLARED table, taken from the same override L5 reads — never the module-level
    constant, which is the fourth trim's bug the fifth fixed and measured."""
    out = []
    want_names = {d for _lo, _hi, d in routing if d != LIVE}
    for path, required, forbidden in REACH:
        text = reach_texts.get(path)
        if text is None:
            out.append("L8 `%s`: unreadable, so no copy of the shard set in it can be checked"
                       % path)
            continue
        for s in required:
            if s not in text:
                out.append("L8/required `%s`: this trim declares it must contain %r and it does "
                           "not — the copy no earlier proof could reach is now stale" % (path, s[:90]))
        for s in forbidden:
            if s in text:
                out.append("L8/forbidden `%s`: it still contains %r, which this trim falsified"
                           % (path, s[:90]))
        got_names = set(SHARD_NAME.findall(text))
        if got_names != want_names:
            out.append("L8/set `%s`: it names shards %s; ROUTING names %s (missing %s; unknown %s)"
                       % (path, sorted(got_names), sorted(want_names),
                          sorted(want_names - got_names) or "none",
                          sorted(got_names - want_names) or "none"))
    return out


def L9(lineage):
    """Write-once for the WHOLE lineage, not just the shard this proof shipped with. Each ancestor
    is compared against the blob committed at the commit that ADDED it — its own commit, never this
    trim's — so this is applicable from the first run, before this trim is committed at all."""
    out = []
    for path, committed, disk in lineage:
        if committed is None:
            out.append("L9 `%s`: git knows no commit that added it, so there is nothing to hold "
                       "the working tree against" % path)
            continue
        if disk is MISSING:
            out.append("L9 WRITE-ONCE `%s`: GONE from the working tree. The routing table still "
                       "sends readers here and every byte assertion above still passes, because "
                       "they read history." % path)
            continue
        if disk != committed:
            i = next((n for n, (a, b) in enumerate(zip(disk, committed)) if a != b),
                     min(len(disk), len(committed)))
            out.append("L9 WRITE-ONCE `%s`: on disk it is not the file that was committed; first "
                       "divergence at character %d (%d B on disk vs %d B committed). Shards are "
                       "write-once — this one was edited after its own trim."
                       % (path, i, len(disk.encode()), len(committed.encode())))
    return out


def L10(provenance):
    """The ancestors' PROOFS, held against hand-declared freeze commits. L9 holds the shards
    because that is a precondition for running their proofs; this holds the proofs, which is the
    other one. A weakened ancestor proof is worse than a deleted one: it still exits 0."""
    out = []
    for path, freeze, committed, disk in provenance:
        if committed is None:
            out.append("L10 `%s`: the declared freeze commit %s does not hold this path, so there "
                       "is nothing to compare the working tree against — the declaration is wrong, "
                       "or the history was rewritten" % (path, freeze[:7]))
            continue
        if disk is MISSING:
            out.append("L10 PROVENANCE `%s`: GONE from the working tree. Its shard is still here "
                       "and L9 still passes on it; six banners and a routing table still tell "
                       "readers to run this proof, and there is nothing left to run." % path)
            continue
        if disk != committed:
            i = next((n for n, (a, b) in enumerate(zip(disk, committed)) if a != b),
                     min(len(disk), len(committed)))
            out.append("L10 PROVENANCE `%s`: on disk it is not the proof frozen at %s; first "
                       "divergence at character %d (%d B on disk vs %d B frozen). An ancestor "
                       "proof was edited after its session ended — if that edit weakened it, it "
                       "still exits 0."
                       % (path, freeze[:7], i, len(disk.encode()), len(committed.encode())))
    return out


def L11(before, after, after_recs, claude, policy):
    """The retention rule this cut exists to satisfy. L0-L10 all ask whether the trim was performed
    FAITHFULLY; none asks whether it was performed AT ALL. A one-record trim is perfectly lossless
    and leaves the file over the trigger that fired it."""
    trigger, target, floor, texts = policy
    out = []
    nb, na = len(before.splitlines()), len(after.splitlines())
    if nb <= trigger:
        out.append("L11/fire: the live file was %d lines before this cut; the declared trigger is "
                   "more than %d, so this trim should not have fired" % (nb, trigger))
    if na > target:
        out.append("L11/target: the live file is %d lines after this cut; the declared target is "
                   "at most %d — the cut was too shallow to solve the problem that fired it"
                   % (na, target))
    if len(after_recs) < floor:
        out.append("L11/floor: the live file retains %d records; the declared floor is %d — the "
                   "cut was too deep and took working context with it" % (len(after_recs), floor))
    for s in texts:
        if s not in claude:
            out.append("L11/declared: `CLAUDE.md` no longer states %r, so the numbers this "
                       "assertion enforces are no longer the numbers the project declares" % s[:90])
    return out


def L12(after_front, shard_front, shard, after_recs, shard_recs, reach_texts, sizes, prose):
    """ARITHMETIC. Every number this trim states about the SIZE of its own artifacts, derived from
    the artifacts and held against the prose that states it. New at the sixth trim; the hole it
    closes is this lineage's own — see the header for the measurement.

    Two halves, and they are independent. The NUMERIC half (headings/lines/total/cap) compares the
    declared integers against the artifacts. The PROSE half compares those same integers against
    the formatted figures printed in five texts, in two formats, because this project's prose
    writes small counts as words and large ones as digits. Neither half can be satisfied by the
    other: a wrong integer passes the prose half if the prose repeats it, and correct integers pass
    the numeric half while a stale sentence still misinforms a reader."""
    out = []
    measured = {
        "archived_headings": len(shard_recs),
        "archived_lines":    len("".join(shard_recs).splitlines()),
        "shard_total":       len(shard.splitlines()),
        "retained_records":  len(after_recs),
        # READ_CAP is a property of the agent harness, not of this repository; there is nothing
        # here to measure it against, so it is declared-only and used solely by the cap arm below.
        "read_cap":          sizes["read_cap"],
        # The mutant count lives in the self-test, which a plain run does not build; the self-test
        # asserts it against len(mutants) itself. Declared-only here for the same honest reason.
        "mutants":           sizes["mutants"],
    }
    for key in ("archived_headings", "archived_lines", "shard_total", "retained_records"):
        if sizes[key] != measured[key]:
            out.append("L12/%s: this trim declares %s = %d; the artifacts measure %d — a figure "
                       "was typed rather than derived"
                       % (key, key, sizes[key], measured[key]))
    if measured["shard_total"] >= sizes["read_cap"]:
        out.append("L12/cap: the shard is %d lines and the declared agent read cap is %d — the "
                   "banner's claim that it sits under the cap is false, and a `Read` of it "
                   "truncates in silence" % (measured["shard_total"], sizes["read_cap"]))
    texts = {"live pointer": after_front, "shard banner": shard_front}
    texts.update(reach_texts)
    for where, literal, form, keys in prose:
        text = texts.get(where)
        if text is None:
            out.append("L12/prose `%s`: unreadable, so the size figures in it cannot be checked"
                       % where)
            continue
        if literal not in text:
            out.append("L12/prose `%s`: this trim declares it states %r and it does not — the "
                       "sentence and the artifact have diverged" % (where, literal[:90]))
            continue
        for key in keys:
            want = WORDS.get(measured[key]) if form == "word" else "{:,}".format(measured[key])
            if want is None or want not in literal:
                out.append("L12/prose `%s`: %r claims %s but the artifacts measure %s (%r) — the "
                           "prose is stated in a figure nobody derived"
                           % (where, literal[:70], key, measured[key], want))
    return out


def check(before, after, shard, claude, sha, disk, reach_texts, lineage, provenance, decl=None):
    d = {"POINTER": POINTER, "BANNER": BANNER, "ROUTING": ROUTING, "POLICY": POLICY,
         "SIZES": SIZES, "SIZE_PROSE": SIZE_PROSE}
    if decl:
        d.update(decl)
    bf, br, _ = zones(before)
    af, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    fails = []
    fails += L0("before", before) + L0("after", after) + L0("shard", shard)
    fails += L1(br, ar, sr)
    fails += L2(bf, af, sf, sr, d["POINTER"])
    fails += L3(br, ar, sr)
    fails += L4(ar, sr)
    fails += L5(af, sf, claude, after, shard, sha, d["ROUTING"])
    fails += L6(sf, d["BANNER"])
    fails += L7(sha, shard, disk)
    fails += L8(reach_texts, d["ROUTING"])
    fails += L9(lineage)
    fails += L10(provenance)
    fails += L11(before, after, ar, claude, d["POLICY"])
    fails += L12(af, sf, shard, ar, sr, reach_texts, d["SIZES"], d["SIZE_PROSE"])
    return fails, (br, ar, sr)


# =====================================================================================
def artifacts():
    sha = added_at(SHARD)

    # L9's operands never depend on `sha`: each ancestor is held against ITS OWN add-commit.
    lineage = []
    for path in ANCESTORS:
        a = added_at(path)
        committed = blob("%s:%s" % (a, path)) if a else None
        try:
            on_disk = worktree(path)
        except OSError:
            on_disk = MISSING
        lineage.append((path, committed, on_disk))
    lineage = tuple(lineage)

    # L10's operands never depend on `sha` either: each ancestor proof is held against its own
    # HAND-DECLARED freeze commit, so this is applicable before the trim is committed at all.
    provenance = []
    for path, freeze in ANCESTOR_PROOFS:
        try:
            committed = blob("%s:%s" % (freeze, path))
        except SystemExit:
            committed = None
        try:
            on_disk = worktree(path)
        except OSError:
            on_disk = MISSING
        provenance.append((path, freeze, committed, on_disk))
    provenance = tuple(provenance)

    if sha:
        try:
            disk = worktree(SHARD)
        except OSError:
            disk = MISSING
        reach = {}
        for p, _r, _f in REACH:
            try:                                  # so L8's unreadable arm is live code, not dead
                reach[p] = blob("%s:%s" % (sha, p))
            except SystemExit:
                reach[p] = None
        return (blob("%s^:%s" % (sha, LIVE)), blob("%s:%s" % (sha, LIVE)),
                blob("%s:%s" % (sha, SHARD)), blob("%s:%s" % (sha, CLAUDE)),
                "the trim commit %s" % sha[:7], sha, disk, reach, lineage, provenance)
    reach = {}
    for p, _r, _f in REACH:
        try:
            reach[p] = worktree(p)
        except OSError:
            reach[p] = None
    return (blob("HEAD:%s" % LIVE), worktree(LIVE), worktree(SHARD), worktree(CLAUDE),
            "HEAD vs the working tree (trim not yet committed)", None, NA, reach, lineage,
            provenance)


def self_test(before, after, shard, claude, sha, reach, lineage, provenance):
    _, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    purpose = next(ln for ln in zones(before)[0].splitlines() if ln.startswith("**Purpose:**"))

    def sub_in_shard(o, n, count=1):
        assert o in shard, "self-test fixture missing: %r" % o[:40]
        return shard.replace(o, n, count)

    assert "−" in "".join(sr), "self-test fixture missing: no U+2212 in the archived span"
    assert "−" not in sf, "fixture broken: M9 must mutate a RECORD, not the shard banner"

    # Every clause a mutant rewrites must be unambiguous in every text that carries it.
    CL216  = "**N ≤ 216** → `SESSION_NOTES-through-S216.md`"
    CL220  = "**217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`"
    CL224  = "**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`"
    CL227  = "**225 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`"
    CL231  = "**228 ≤ N ≤ 231** → `SESSION_NOTES-S231-through-S228.md`"
    CL235  = "**232 ≤ N ≤ 235** → `SESSION_NOTES-S235-through-S232.md`"
    CLLIVE = "**N ≥ 236** → `SESSION_NOTES.md`"
    for cl in (CL216, CL220, CL224, CL227, CL231, CL235, CLLIVE):
        for name, text in (("POINTER", POINTER), ("BANNER", BANNER),
                           ("live file", after), ("shard", shard), ("CLAUDE.md", claude)):
            assert text.count(cl) == 1, ("self-test fixture %r occurs %d times in %s (want 1)"
                                         % (cl[:28], text.count(cl), name))

    def rewrite(pairs, texts):
        """Apply the same clause rewrites to every text that carries the table."""
        out = []
        for t in texts:
            for o, n in pairs:
                t = t.replace(o, n, 1)
            out.append(t)
        return out

    # --- L5 fixtures. Each rewrites the DECLARATION and the artifact together, so the assertion
    #     that pins them by equality (L2 for the pointer, L6 for the banner) stays satisfied and
    #     L5 is the only one left able to object.
    m18_b, m18_s = rewrite([(CLLIVE, "**N ≥ 232** → `SESSION_NOTES.md`")], [BANNER, shard])
    m19_b, m19_s = rewrite([(CL235, "**231 ≤ N ≤ 235** → `SESSION_NOTES-S235-through-S232.md`")],
                           [BANNER, shard])
    m20_p, m20_a = rewrite([(CLLIVE, "**N ≥ 232** → `SESSION_NOTES.md`")], [POINTER, after])
    m21_p, m21_a = rewrite([(CL235, "**233 ≤ N ≤ 235** → `SESSION_NOTES-S235-through-S232.md`")],
                           [POINTER, after])
    swap = [(CL231, "**228 ≤ N ≤ 231** → `SESSION_NOTES-S235-through-S232.md`"),
            (CL235, "**232 ≤ N ≤ 235** → `SESSION_NOTES-S231-through-S228.md`")]
    m22_b, m22_s = rewrite(swap, [BANNER, shard])
    m23_p, m23_a = rewrite(swap, [POINTER, after])

    # M24/M25/M38/M39/M47 rewrite ROUTING as well, so even the declaration is self-consistent.
    short = [(CL235, "**232 ≤ N ≤ 234** → `SESSION_NOTES-S235-through-S232.md`"),
             (CLLIVE, "**N ≥ 235** → `SESSION_NOTES.md`")]
    m24_p, m24_b, m24_a, m24_s, m24_c = rewrite(short, [POINTER, BANNER, after, shard, claude])
    m24_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 224, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, 231, "SESSION_NOTES-S231-through-S228.md"),
             (232, 234, "SESSION_NOTES-S235-through-S232.md"),
             (235, None, "SESSION_NOTES.md"))
    front = [(CL216, "**N ≤ 100** → `SESSION_NOTES-through-S216.md`"),
             (CL220, "**101 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`")]
    m25_p, m25_b, m25_a, m25_s, m25_c = rewrite(front, [POINTER, BANNER, after, shard, claude])
    m25_r = ((None, 100, "SESSION_NOTES-through-S216.md"),
             (101, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 224, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, 231, "SESSION_NOTES-S231-through-S228.md"),
             (232, 235, "SESSION_NOTES-S235-through-S232.md"),
             (236, None, "SESSION_NOTES.md"))
    gap = [(CL224, "**221 ≤ N ≤ 223** → `SESSION_NOTES-S224-through-S221.md`")]
    m38_p, m38_b, m38_a, m38_s, m38_c = rewrite(gap, [POINTER, BANNER, after, shard, claude])
    m38_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 223, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, 231, "SESSION_NOTES-S231-through-S228.md"),
             (232, 235, "SESSION_NOTES-S235-through-S232.md"),
             (236, None, "SESSION_NOTES.md"))
    over = [(CL224, "**221 ≤ N ≤ 225** → `SESSION_NOTES-S224-through-S221.md`")]
    shape = [(CL224, "**N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`")]
    m39_p, m39_b, m39_a, m39_s, m39_c = rewrite(over, [POINTER, BANNER, after, shard, claude])
    m39_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 225, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, 231, "SESSION_NOTES-S231-through-S228.md"),
             (232, 235, "SESSION_NOTES-S235-through-S232.md"),
             (236, None, "SESSION_NOTES.md"))
    m47_p, m47_b, m47_a, m47_s, m47_c = rewrite(shape, [POINTER, BANNER, after, shard, claude])
    m47_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (None, 224, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, 231, "SESSION_NOTES-S231-through-S228.md"),
             (232, 235, "SESSION_NOTES-S235-through-S232.md"),
             (236, None, "SESSION_NOTES.md"))

    # M16/M17 move ONE WHOLE RECORD across the boundary. ar[-1] is the oldest retained record and
    # sr[0] the newest archived one, so both mutants keep the newest-on-top order intact — which is
    # exactly why L1 and L3 cannot see them and L4 must.
    m16_after, m16_shard = after.replace(ar[-1], "", 1), sf + ar[-1] + "".join(sr)
    m17_after, m17_shard = after + sr[0], shard.replace(sr[0], "", 1)

    # --- L8 fixtures. Each mutates ONE of the four out-of-reach files.
    def reach_with(path, old, new, count=1):
        assert reach[path].count(old) >= 1, "self-test fixture missing in %s: %r" % (path, old[:50])
        r = dict(reach)
        r[path] = r[path].replace(old, new, count)
        return r
    m31 = reach_with(README, "older in the six shards above", "older in the five shards above")
    m32 = reach_with(README, REACH[0][1][0], "")
    m33 = reach_with(CONVENTIONS, "**Six instances so far**", "**Five instances so far**")
    m34 = reach_with(CONVENTIONS, "`SESSION_NOTES-S235-through-S232.md` (Session 239",
                     "`SESSION_NOTES-S234-through-S232.md` (Session 239")
    m41 = reach_with(BACKLOG, "there are now **six** unwatched shards",
                     "there are now **five** unwatched shards")
    # M42 removes the new shard's NAME from BACKLOG.md while leaving its size figure in place. It
    # therefore trips L8/set AND L12/prose (whose declared literal carries the name); recorded in
    # the coverage block rather than contrived into an L8-only form — M45 and M46 already give
    # L8/set mutants of its own.
    m42 = reach_with(BACKLOG, "`SESSION_NOTES-S235-through-S232.md` (1,057 lines)",
                     "the newest shard (1,057 lines)")

    # --- Sub-clause fixtures inherited from the fourth trim's adversarial review.
    m43 = dict(reach)                                    # CLAUDE.md: table intact, count words stale
    m43[CLAUDE] = (m43[CLAUDE]
                   .replace("**Trimmed six times (Sessions 222, 224, 228, 231, 235, 239):**",
                            "**Trimmed five times (Sessions 222, 224, 228, 231, 235):**", 1)
                   .replace("Retired records live in **six** write-once shards",
                            "Retired records live in **five** write-once shards", 1)
                   .replace("grep *all six*", "grep *all five*", 1)
                   .replace("there are SIX, and a lookup must consult all of them",
                            "there are FIVE, and a lookup must consult all of them", 1))
    # forbidden ALONE: the required string stays, the falsified one comes back beside it.
    m44 = reach_with(CONVENTIONS, "**Six instances so far**",
                     "**Six instances so far** — it said **Five instances so far** before this cut")
    # set ALONE: an ANCESTOR's name typo'd, so required and forbidden are both untouched.
    m45 = reach_with(CONVENTIONS, "`SESSION_NOTES-S224-through-S221.md` (Session 228",
                     "`SESSION_NOTES-S224-through-S220.md` (Session 228")
    # set, via the lookahead: drop an ancestor's own repo-map line and leave its `.verify.sh` line.
    m46 = reach_with(README,
                     "  SESSION_NOTES-S224-through-S221.md    # frozen SESSION_NOTES records, Sessions 224->221 (grep it; do not Read it)\n",
                     "")
    # L9's third arm: git knows the file but no commit that added it.
    m48 = tuple((p, None, d) if i == 0 else (p, c, d)
                for i, (p, c, d) in enumerate(lineage))
    # L8's unreadable arm.
    m49 = {k: v for k, v in reach.items() if k != README}
    m49[README] = None
    # required ALONE: a declared string reworded so no forbidden string appears and the shard
    # name set stays complete.
    m50 = reach_with(CONVENTIONS, "**Six instances so far**", "**6 instances so far**")

    # --- L9 fixtures. Same shape as L7's, one level out: the ANCESTOR shards on disk.
    def lineage_with(idx, mutate):
        out = list(lineage)
        path, committed, on_disk = out[idx]
        out[idx] = (path, committed, mutate(on_disk))
        return tuple(out)
    m35 = lineage_with(0, lambda t: t[:20000])
    m36 = lineage_with(1, lambda _t: MISSING)
    m37 = lineage_with(2, lambda t: t.replace("e", "3", 1))

    # M51 — L2/b3's narrowed form, and the only mutant that reaches it. A front-matter line is
    # COPIED into the banner (and into the declaration, so L6 is satisfied) and LEFT IN PLACE in
    # the live front matter, so b2's SURVIVAL arm has nothing to say and b1 sees an untouched
    # after_front.
    #
    # IT REPLACES A BANNER LINE RATHER THAN APPENDING ONE, and that is not cosmetic. The fifth
    # trim's M51 appended, which under THIS proof also changes the shard's line count — so L12
    # catches it, and b3 is left with no uniquely-catching mutant of its own. Measured, not
    # predicted: the neuter loop reported M51 caught with L2 disabled. A mutant must isolate the
    # arm it exists for; making it line-count-neutral is what restores that.
    LINE = "where the fifth trim had left it. Expect this at every boundary, in both directions."
    assert BANNER.count(LINE) == 1 and purpose not in BANNER, "M51 fixture broken"
    m51_b = BANNER.replace(LINE, purpose, 1)
    m51_s = m51_b + "".join(sr)

    # M52 — L5/4's UNREADABLE arm, alone. An ancestor shard's filename is typo'd in the
    # declaration AND in every prose copy AND in all four REACH texts, so L5/1-L5/3 are
    # self-consistent and L8/set sees the same (wrong) name set the routing table does.
    TYPO = ("SESSION_NOTES-S220-through-S217.md", "SESSION_NOTES-S220-through-S218.md")
    m52_p, m52_b, m52_a, m52_s, m52_c = rewrite(
        [(CL220, CL220.replace(*TYPO))], [POINTER, BANNER, after, shard, claude])
    m52_r = tuple((lo, hi, d.replace(*TYPO)) for lo, hi, d in ROUTING)
    m52_reach = {k: (v.replace(*TYPO) if v is not None else None) for k, v in reach.items()}

    # M53/M54/M55 — L10's three arms, one each.
    def provenance_with(idx, committed=..., disk=...):
        out = list(provenance)
        c, d = out[idx][2], out[idx][3]
        out[idx] = (out[idx][0], out[idx][1],
                    c if committed is ... else committed,
                    d if disk is ... else disk)
        return tuple(out)
    m53 = provenance_with(0, committed=None)                       # declared freeze holds no blob
    m54 = provenance_with(1, disk=MISSING)                         # proof deleted from the tree
    m55 = provenance_with(4, disk=provenance[4][3][:12000])        # proof truncated on disk

    # M56/M57/M58/M59 — L11's four arms, one each.
    trig, targ, floor, texts = POLICY
    m56_pol = (5000, targ, floor, texts)
    m57_pol = (trig, 500, floor, texts)
    m58_pol = (trig, targ, 9, texts)
    m59_c = claude.replace("Fire a new trim when the live file exceeds **1,500 lines**",
                           "Fire a new trim when the live file feels too long", 1)

    # --- NEW at this trim: L12's six arms, nine mutants. -------------------------------------
    # M60-M63 and M68 move ONE declared integer and leave every prose copy alone, so each numeric arm is
    # reached by itself and the prose half stays satisfied (it measures the artifacts, never the
    # declaration). M64-M67 do the opposite: they move a FIGURE IN THE PROSE together with every
    # declaration that pins that prose by equality — POINTER for the pointer block, BANNER for the
    # banner, and SIZE_PROSE's own literal — so L2/b1 and L6 are satisfied and L12/prose is the
    # only assertion left able to object. That is the real-world failure this arm exists for: a
    # number typed once, then copied consistently everywhere.
    def sizes_with(**kw):
        s = dict(SIZES)
        s.update(kw)
        return s

    def prose_with(old, new):
        assert any(old in l for _w, l, _f, _k in SIZE_PROSE), "fixture missing in SIZE_PROSE: %r" % old
        return tuple((w, l.replace(old, new, 1), f, k) for w, l, f, k in SIZE_PROSE)

    m60 = sizes_with(archived_headings=5)
    m61 = sizes_with(archived_lines=1014)
    m62 = sizes_with(shard_total=1067)
    # M63 mis-states the cap CONSISTENTLY — in the declaration, in the banner and in the
    # declared literal — so the prose half is satisfied and the cap arm is the only one left
    # able to object. Measured: the naive form (move the integer only) also trips L12/prose,
    # which left the cap arm with no mutant of its own.
    m63_sz = sizes_with(read_cap=500)
    m63_b = BANNER.replace("under the 2,000-line agent read", "under the 500-line agent read", 1)
    m63_s = shard.replace("under the 2,000-line agent read", "under the 500-line agent read", 1)
    m63_pr = prose_with("At 1,057 lines it sits under the 2,000-line agent read",
                        "At 1,057 lines it sits under the 500-line agent read")
    m64_p = POINTER.replace("4 record headings, 1,004 lines", "4 record headings, 1,014 lines", 1)
    m64_a = after.replace("4 record headings, 1,004 lines", "4 record headings, 1,014 lines", 1)
    m64_pr = prose_with("4 record headings, 1,004 lines", "4 record headings, 1,014 lines")
    m65 = reach_with(BACKLOG, "`SESSION_NOTES-S235-through-S232.md` (1,057 lines)",
                     "`SESSION_NOTES-S235-through-S232.md` (1,507 lines)")
    m66 = reach_with(README, "newest 4 sessions", "newest 5 sessions")
    m67_b = BANNER.replace("232 — four record", "232 — five record", 1)
    m67_s = shard.replace("232 — four record", "232 — five record", 1)
    m67_pr = prose_with("Sessions 235 → 232 — four record", "Sessions 235 → 232 — five record")
    m68 = sizes_with(retained_records=5)

    SAME = object()          # the mutant's own shard, i.e. an untampered working tree
    mutants = [
        ("M1  last byte of the shard's last record deleted", before, after, shard[:-1], claude, None, SAME, reach, lineage, provenance),
        ("M2  one whole archived record deleted", before, after, shard.replace(sr[1], "", 1), claude, None, SAME, reach, lineage, provenance),
        ("M3  one character flipped inside an archived record", before, after,
         sub_in_shard(sr[1], sr[1].replace("e", "3", 1)), claude, None, SAME, reach, lineage, provenance),
        ("M4  one character flipped inside a retained record", before,
         after.replace(ar[-1], ar[-1].replace("e", "3", 1), 1), shard, claude, None, SAME, reach, lineage, provenance),
        ("M5  two adjacent archived records swapped", before, after,
         sub_in_shard(sr[1] + sr[2], sr[2] + sr[1]), claude, None, SAME, reach, lineage, provenance),
        ("M6  a front-matter line MOVED from the live file into the shard banner", before,
         after.replace(purpose + "\n", "", 1),
         shard.replace("---\n\n### What Session", purpose + "\n\n---\n\n### What Session", 1),
         claude, None, SAME, reach, lineage, provenance),
        ("M7  a trailing file-scoped block appended below the shard's last record", before, after,
         shard + "\n---\n\ntrailing paragraph\n", claude, None, SAME, reach, lineage, provenance),
        ("M8  the pointer block dropped from the live front matter", before,
         after.replace(POINTER, "", 1), shard, claude, None, SAME, reach, lineage, provenance),
        ("M9  U+2212 silently normalised to ASCII '-' in an archived record", before, after,
         sub_in_shard("−", "-"), claude, None, SAME, reach, lineage, provenance),
        ("M10 declared substitution 1 not applied (stale 'holds Sessions 235 → 232 only')", before,
         after.replace(FRONT_SUBST[0][1], FRONT_SUBST[0][0], 1), shard, claude, None, SAME, reach, lineage, provenance),
        ("M11 declared substitution 2 not applied (the stale five-shard table left standing)", before,
         after.replace(FRONT_SUBST[1][1], FRONT_SUBST[1][0], 1), shard, claude, None, SAME, reach, lineage, provenance),
        ("M12 declared substitution 3 not applied (stale 'Three shard banners are stale now')", before,
         after.replace(FRONT_SUBST[2][1], FRONT_SUBST[2][0], 1), shard, claude, None, SAME, reach, lineage, provenance),
        ("M13 an UNDECLARED extra front-matter edit alongside the declared ones", before,
         after.replace("this paragraph is the only warning there is.",
                       "this paragraph is the only warning there was.", 1), shard, claude, None, SAME, reach, lineage, provenance),
        ("M14 substitution 1's anchor absent from `before` (declaration gone stale)",
         before.replace(FRONT_SUBST[0][0], "REPLACED BY AN EARLIER EDIT\n", 1), after, shard,
         claude, None, SAME, reach, lineage, provenance),
        ("M15 substitution 3's anchor absent from `before` (declaration gone stale)",
         before.replace(FRONT_SUBST[2][0], "REPLACED BY AN EARLIER EDIT\n", 1), after, shard,
         claude, None, SAME, reach, lineage, provenance),
        ("M16 cut shifted: the oldest RETAINED record moved into the shard", before,
         m16_after, m16_shard, claude, None, SAME, reach, lineage, provenance),
        ("M17 cut shifted: the newest ARCHIVED record kept in the live file", before,
         m17_after, m17_shard, claude, None, SAME, reach, lineage, provenance),
        ("M18 banner + its declaration agree on a stale `N ≥ 232`", before, after, m18_s,
         claude, {"BANNER": m18_b}, SAME, reach, lineage, provenance),
        ("M19 banner + its declaration agree on a 231-235 range (overlaps the S231 shard)", before,
         after, m19_s, claude, {"BANNER": m19_b}, SAME, reach, lineage, provenance),
        ("M20 pointer + its declaration agree on a stale `N ≥ 232`", before, m20_a, shard,
         claude, {"POINTER": m20_p}, SAME, reach, lineage, provenance),
        ("M21 pointer + its declaration agree on a 233-235 range (Session 232 unroutable)", before,
         m21_a, shard, claude, {"POINTER": m21_p}, SAME, reach, lineage, provenance),
        ("M22 banner: numbers untouched, the S231/S235 FILENAMES swapped", before, after, m22_s,
         claude, {"BANNER": m22_b}, SAME, reach, lineage, provenance),
        ("M23 pointer: numbers untouched, the S231/S235 FILENAMES swapped", before, m23_a, shard,
         claude, {"POINTER": m23_p}, SAME, reach, lineage, provenance),
        ("M24 every copy AND the declaration agree this shard holds 232-234", before, m24_a, m24_s,
         m24_c, {"POINTER": m24_p, "BANNER": m24_b, "ROUTING": m24_r}, SAME, reach, lineage, provenance),
        ("M25 every copy AND the declaration move the S216/S220 frontier to 100/101", before,
         m25_a, m25_s, m25_c, {"POINTER": m25_p, "BANNER": m25_b, "ROUTING": m25_r}, SAME, reach, lineage, provenance),
        ("M26 CLAUDE.md's copy of the table left stale", before, after, shard,
         claude.replace(CLLIVE, "**N ≥ 232** → `SESSION_NOTES.md`", 1), None, SAME, reach, lineage, provenance),
        ("M27 the shard's banner headline claims a different session range", before, after,
         sub_in_shard("archive shard: Sessions 235 → 232", "archive shard: Sessions 231 → 228"),
         claude, None, SAME, reach, lineage, provenance),
        ("M28 an extra paragraph inserted into the shard's banner", before, after,
         sub_in_shard("---\n\n### What Session", "\nInserted later by someone helpful.\n\n---\n\n### What Session"),
         claude, None, SAME, reach, lineage, provenance),
        ("M29 the shard TRUNCATED on disk after the trim commit", before, after, shard, claude,
         None, shard[:20000], reach, lineage, provenance),
        ("M30 the shard DELETED from the working tree after the trim commit", before, after, shard,
         claude, None, MISSING, reach, lineage, provenance),
        ("M31 README.md still says 'the five shards above'", before, after, shard, claude,
         None, SAME, m31, lineage, provenance),
        ("M32 README.md's repo map never names the new shard", before, after, shard, claude,
         None, SAME, m32, lineage, provenance),
        ("M33 PROJECT_CONVENTIONS.md still says 'Five instances so far'", before, after, shard,
         claude, None, SAME, m33, lineage, provenance),
        ("M34 PROJECT_CONVENTIONS.md names a phantom shard instead of the new one", before, after,
         shard, claude, None, SAME, m34, lineage, provenance),
        ("M35 an ANCESTOR shard (S216) truncated on disk", before, after, shard, claude,
         None, SAME, reach, m35, provenance),
        ("M36 an ANCESTOR shard (S220) deleted from the working tree", before, after, shard,
         claude, None, SAME, reach, m36, provenance),
        ("M37 an ANCESTOR shard (S224) edited by one character on disk", before, after, shard,
         claude, None, SAME, reach, m37, provenance),
        ("M38 every copy AND the declaration leave Session 224 unrouted (GAP)", before, m38_a,
         m38_s, m38_c, {"POINTER": m38_p, "BANNER": m38_b, "ROUTING": m38_r}, SAME, reach, lineage, provenance),
        ("M39 every copy AND the declaration route Session 225 to two files (OVERLAP)", before,
         m39_a, m39_s, m39_c, {"POINTER": m39_p, "BANNER": m39_b, "ROUTING": m39_r}, SAME, reach, lineage, provenance),
        ("M40 substitution 2's anchor absent from `before` (declaration gone stale)",
         before.replace(FRONT_SUBST[1][0], "REPLACED BY AN EARLIER EDIT\n", 1), after, shard,
         claude, None, SAME, reach, lineage, provenance),
        ("M41 BACKLOG.md's read-cap item still says 'five unwatched shards'", before, after,
         shard, claude, None, SAME, m41, lineage, provenance),
        ("M42 BACKLOG.md's read-cap item never names the new shard", before, after, shard,
         claude, None, SAME, m42, lineage, provenance),
        ("M43 CLAUDE.md: seven correct routing clauses, count words still saying five", before,
         after, shard, claude, None, SAME, m43, lineage, provenance),
        ("M44 PROJECT_CONVENTIONS.md: the falsified count restored BESIDE the correct one", before,
         after, shard, claude, None, SAME, m44, lineage, provenance),
        ("M45 PROJECT_CONVENTIONS.md: an ANCESTOR shard's filename typo'd", before, after, shard,
         claude, None, SAME, m45, lineage, provenance),
        ("M46 README.md: an ancestor's own map line dropped, its `.verify.sh` line left", before,
         after, shard, claude, None, SAME, m46, lineage, provenance),
        ("M47 every copy AND the declaration open TWO clauses below (shape)", before, m47_a,
         m47_s, m47_c, {"POINTER": m47_p, "BANNER": m47_b, "ROUTING": m47_r}, SAME, reach, lineage, provenance),
        ("M48 an ancestor shard git knows no add-commit for", before, after, shard, claude,
         None, SAME, reach, m48, provenance),
        ("M49 a file L8 must read is unreadable", before, after, shard, claude, None, SAME,
         m49, lineage, provenance),
        ("M50 a declared required string reworded, nothing else disturbed", before, after, shard,
         claude, None, SAME, m50, lineage, provenance),
        ("M51 a front-matter line COPIED into the banner and left in place upstream (b3 alone)",
         before, after, m51_s, claude, {"BANNER": m51_b}, SAME, reach, lineage, provenance),
        ("M52 an ANCESTOR shard's filename typo'd in the declaration and EVERY copy (L5/4 alone)",
         before, m52_a, m52_s, m52_c, {"POINTER": m52_p, "BANNER": m52_b, "ROUTING": m52_r},
         SAME, m52_reach, lineage, provenance),
        ("M53 an ancestor PROOF's declared freeze commit holds no such path", before, after,
         shard, claude, None, SAME, reach, lineage, m53),
        ("M54 an ancestor PROOF deleted from the working tree", before, after, shard, claude,
         None, SAME, reach, lineage, m54),
        ("M55 an ancestor PROOF truncated on disk after its session froze it", before, after,
         shard, claude, None, SAME, reach, lineage, m55),
        ("M56 the retention TRIGGER relaxed so this trim should not have fired", before, after,
         shard, claude, {"POLICY": m56_pol}, SAME, reach, lineage, provenance),
        ("M57 the retention TARGET tightened below what the cut actually achieved", before, after,
         shard, claude, {"POLICY": m57_pol}, SAME, reach, lineage, provenance),
        ("M58 the retention FLOOR raised above the number of records retained", before, after,
         shard, claude, {"POLICY": m58_pol}, SAME, reach, lineage, provenance),
        ("M59 CLAUDE.md no longer states the trigger this assertion enforces", before, after,
         shard, m59_c, None, SAME, reach, lineage, provenance),
        # --- the eight this trim adds, all L12's.
        ("M60 the declared ARCHIVED HEADING COUNT does not match the shard", before, after, shard,
         claude, {"SIZES": m60}, SAME, reach, lineage, provenance),
        ("M61 the declared ARCHIVED LINE COUNT does not match the shard", before, after, shard,
         claude, {"SIZES": m61}, SAME, reach, lineage, provenance),
        ("M62 the declared SHARD TOTAL does not match the shard", before, after, shard,
         claude, {"SIZES": m62}, SAME, reach, lineage, provenance),
        ("M63 the read cap mis-stated below the shard's size, consistently everywhere", before,
         after, m63_s, claude, {"SIZES": m63_sz, "BANNER": m63_b, "SIZE_PROSE": m63_pr}, SAME,
         reach, lineage, provenance),
        ("M64 a wrong line count typed in the POINTER and copied into its declaration", before,
         m64_a, shard, claude, {"POINTER": m64_p, "SIZE_PROSE": m64_pr}, SAME, reach, lineage, provenance),
        ("M65 BACKLOG.md states a size figure nobody derived", before, after, shard, claude,
         None, SAME, m65, lineage, provenance),
        ("M66 README.md states a retained-session count nobody derived", before, after, shard,
         claude, None, SAME, m66, lineage, provenance),
        ("M67 the banner's WORD-FORM heading count changed with its declaration", before, after,
         m67_s, claude, {"BANNER": m67_b, "SIZE_PROSE": m67_pr}, SAME, reach, lineage, provenance),
        ("M68 the declared RETAINED RECORD COUNT does not match the live file", before, after,
         shard, claude, {"SIZES": m68}, SAME, reach, lineage, provenance),
    ]
    assert SIZES["mutants"] == len(mutants), (
        "the banner tells readers this proof ships %d mutants; it ships %d. A reader who trusts "
        "that number is being misled by exactly the mechanism L12 exists to stop."
        % (SIZES["mutants"], len(mutants)))
    bad = []
    for name, b, a, s, c, decl, disk, rch, lin, prov in mutants:
        # A mutant that does not name a disk state gets an untampered one: its own shard.
        d = s if disk is SAME else disk
        # The REAL sha, never a stand-in: L5/4 reads the ancestor shards through it, and a fake
        # one makes every one of them unreadable — which would "catch" every mutant by breaking
        # the proof rather than by detecting the mutation.
        fails, _ = check(b, a, s, c, sha, d, rch, lin, prov, decl)
        if not fails:
            bad.append(name)
            print("  SURVIVED  %s" % name)
        else:
            # EVERY assertion that fires, not just the first: it must stay visible which assertion
            # is doing the work.
            codes = sorted({f.split(":")[0].split(" (")[0] for f in fails})
            print("  caught    %-74s -> %s" % (name, ", ".join(codes)))
    if bad:
        print("\nSELF-TEST FAILED: %d mutant(s) survived. This proof cannot be trusted." % len(bad))
        sys.exit(2)
    print("\nSELF-TEST OK: all %d mutants caught. Losing a byte fails this proof; so does editing"
          % len(mutants))
    print("one, skipping any declared correction, making an undeclared one, letting a declaration")
    print("go stale, sliding the cut point by one record, mis-stating where a session lives even")
    print("when every copy agrees, leaving a gap or an overlap in the routing table, editing the")
    print("shard's banner, pasting a front-matter line into it, touching ANY shard OR ANY ancestor")
    print("PROOF on disk after the commit that froze it, leaving README.md, PROJECT_CONVENTIONS.md,")
    print("BACKLOG.md or CLAUDE.md describing the shard set that existed before, relaxing the")
    print("retention rule this cut exists to satisfy, or stating ANY size figure — in digits or in")
    print("words, in the pointer, the banner, README.md, BACKLOG.md or CLAUDE.md — that the")
    print("artifacts do not actually measure.")


before, after, shard, claude, source, sha, disk, reach, lineage, provenance = artifacts()

if "--self-test" in sys.argv:
    print("--self-test: mutating the artifacts and asserting each mutation is caught.\n")
    self_test(before, after, shard, claude, sha, reach, lineage, provenance)
    sys.exit(0)

fails, (br, ar, sr) = check(before, after, shard, claude, sha, disk, reach, lineage, provenance)
have = Counter(ar) + Counter(sr)
added = len(list((have - Counter(br)).elements()))
note = noleak_note(zones(before)[0], sr)

print("source : %s" % source)
print("grammar: heading /^### What Session \\S+ Did$/ ; footer_mode=none (asserted) ; transform=none")
print("records: %d before = %d retained + %d archived; added by the trim commit: %d"
      % (len(br), len(ar), len(sr), added))
print("cut key: retained %s | archived %s   (hand-declared, checked by L4 and L5)"
      % (list(CUT_RETAINED), list(CUT_ARCHIVED)))
print("routing: %d clauses, checked in 3 copies (live pointer, shard banner, CLAUDE.md) and"
      % len(ROUTING))
print("         anchored against the record ids actually in each file it names")
print("reach  : %d copies L5 does not check (%s)"
      % (len(REACH), ", ".join(p for p, _r, _f in REACH)))
print("lineage: %d ancestor shard(s) held against their own add-commits" % len(lineage))
print("provena: %d ancestor proof(s) held against hand-declared freeze commits" % len(provenance))
print("policy : fired above %d lines, landed at %d (target %d), retained %d records (floor %d)"
      % (POLICY[0], len(after.splitlines()), POLICY[1], len(ar), POLICY[2]))
print("size   : %d archived headings, %d archived lines, shard %d lines (cap %d) — measured here,"
      % (len(sr), len("".join(sr).splitlines()), len(shard.splitlines()), SIZES["read_cap"]))
print("         held against %d declared integers and %d prose claims in %d texts"
      % (len(SIZES), len(SIZE_PROSE), len({w for w, _l, _f, _k in SIZE_PROSE})))
print("front  : pointer insertion + %d declared substitutions, all checked by exact equality"
      % len(FRONT_SUBST))
print("checked: L0, L1, L2/front-matter, L3, L4, L5, L6, L7, L8, L9, L10, L11, L12    "
      "<- L2/footer absent: inapplicable, no footer zone")
print("b3 note: narrowed to the banner at the FIFTH trim; its condition (TRANSFORM is None, L1")
print("         present) re-checked here and still holds. %d front-matter line(s) occur inside the"
      % len(note))
print("         archived RECORDS and would have been flagged by the pre-narrowing predicate.")
if any(f.startswith("L1") for f in fails):
    # The narrowing's whole justification is that L1 pins these bytes. On the one run where L1 is
    # RED that justification is void, and printing it as a fact would tell the reader the removed
    # check was redundant exactly when it was not.
    print("         *** L1 IS RED ON THIS RUN. These lines are NOT pinned, so the half the fifth")
    print("         *** trim narrowed away would have carried information here. Treat each as a")
    print("         *** CANDIDATE LEAK until L1 is green again.")
else:
    print("         L1 is green, so each is pinned byte-for-byte and none of them can be a leak.")
print("         Nothing is hidden:")
for i, s in note:
    print("           front-matter line %d: %s" % (i, s[:120]))
if not note:
    print("           (none on this cut)")
if sha is None:
    print("         L7 inapplicable: the trim is not committed yet, so there is no frozen blob to")
    print("         compare the working tree against. It becomes live at the trim commit. L9, L10")
    print("         and L12 are applicable already.")

if fails:
    print("\nFAIL for %s:" % SHARD)
    for f in fails:
        print("  " + f)
    sys.exit(1)

print("\nOK: %s hold for %s" % ("L0-L12" if sha else "L0-L6, L8-L12 (L7 inapplicable)", SHARD))
print("    Every byte of the pre-trim records zone is still present, in the right file, unedited,")
print("    in order, and on the declared side of the declared boundary; all three copies of the")
print("    routing table agree with that boundary AND with what the files they name contain; the")
print("    shard's banner is the declared text and carries no leaked front matter; README.md,")
print("    PROJECT_CONVENTIONS.md, BACKLOG.md and CLAUDE.md describe the shard set that now")
print("    exists; every earlier shard AND every earlier proof on disk is still the file its own")
print("    session froze; this cut obeyed the retention rule CLAUDE.md declares; and every size")
print("    figure any of those files states was derived from the artifacts rather than typed.")
if sha:
    print("    The shard on disk is still the shard that was committed at %s." % sha[:7])
else:
    print("    NOTHING is claimed about THIS shard on disk: L7 has no frozen blob to compare it")
    print("    against until the trim is committed. Re-run after committing.")
print("    It says NOTHING about whether the boundary was wisely chosen BEYOND the three numbers")
print("    L11 enforces, nor whether any record's content is true — a human reads that once. It")
print("    does not re-prove the S216, S220, S224, S227 or S231 cuts: each has its own proof,")
print("    pinned to its own cut key and its own commit. Run those five as well. A green proof")
print("    never --self-test'ed proves less than it appears to.")
PYEOF
