#!/usr/bin/env bash
# SESSION_NOTES-S227-through-S225.md.verify.sh — the losslessness proof for this shard.
#
# Generated by Session 231 (the FOURTH trim). Re-runnable, read-only, exits non-zero on failure.
#
#   bash <this>              prove the fourth trim was lossless AND landed where it was declared
#   bash <this> --self-test  prove this proof can FAIL (50 mutants; exit 2 if any survives)
#
# Descended from Session 228's SESSION_NOTES-S224-through-S221.md.verify.sh, itself descended from
# Session 224's and Session 222's — read those for the rationale behind L0-L3, L4 and L5-L7. Shards
# are WRITE-ONCE: this proof pins ITS OWN cut key and does not re-prove the earlier shards' cuts.
# Run all four.
#
# TWO ASSERTIONS ARE NEW HERE. Neither is speculative: each closes a hole that an earlier proof
# NAMED IN ITS OWN PROSE and then declined to check.
#
#   L8 (REACH) — the two copies of the shard set that live outside every earlier proof. The third
#      trim's pointer block says it in as many words: "Two further copies live outside every proof
#      — `README.md`'s repo map and the shard-naming rule in `docs/methodology/PROJECT_CONVENTIONS.md`
#      — and a trim that leaves either one alone ships a lie." CLAUDE.md repeats it. Both were
#      correct and both were unenforced: L5 reads three copies (live pointer, shard banner,
#      CLAUDE.md) and stops. So a trim could archive records, update every machine-checked copy,
#      pass all eight assertions green, and leave README.md telling the next reader there are three
#      shards holding everything before Session 225.
#
#      THE LIST IN THAT SENTENCE WAS ITSELF INCOMPLETE, which is the more useful half of this
#      finding. Sweeping the repo for the CLASS rather than trusting the named instances turned up
#      a THIRD unenforced copy the third trim never mentioned: BACKLOG.md's read-cap item, whose
#      whole subject is the shard set and which said "there are now **three** unwatched shards".
#      L8 covers all three. A fifth trim should sweep again rather than trust this list either —
#      `git grep -l 'SESSION_NOTES-'` is the sweep, and it takes one second.
#
#      L8 checks each of the two files two ways, because either alone is weak. (a) HAND-DECLARED
#      required and forbidden text — this catches the stale COUNT WORD ("the three shards above",
#      "Three instances so far"), which no derived check can see, because a count word is prose and
#      not a filename. (b) DERIVED FROM ROUTING — the set of shard filenames each file names must
#      equal the set ROUTING names, which catches both a shard left out and a phantom or typo'd one
#      without restating the list a second time.
#
#      DELIBERATE SCOPE WIDENING, and it has the same consequence L5's did: README.md and
#      PROJECT_CONVENTIONS.md must now be part of the trim commit, or this proof is red from the
#      first run. That is the point. And the same limit applies as to L5 — this reads them AT THE
#      TRIM COMMIT. It checks them as AUTHORED; it does not police later edits.
#
#   L9 (LINEAGE) — write-once, enforced for EVERY shard rather than only the newest. L7 was
#      introduced by the third trim as "the only enforcement `write-once` has ever had", and that
#      was true, but it guards exactly one file: the shard that shipped with it. The S216 and S220
#      shards have no L7 at all (their proofs predate it), and the S224 shard's L7 lives in the
#      S224 proof — which nothing obliges a session to run. Meanwhile every assertion here reads
#      git history, so truncating or deleting an ANCESTOR shard leaves this suite fully green.
#      Measured, not assumed: `mv` the S216 shard aside and, once this trim is committed, L0-L8 all
#      pass. L9 compares each ancestor shard on disk against the blob committed at the commit that
#      ADDED it — its own commit, never this trim's — so it is applicable from the first run,
#      before this trim is even committed, unlike L7.
#
#      L9 IS ASYMMETRIC IN THE SAME WAY L7 IS, and for the same reason: shards only. The live
#      ledger is SUPPOSED to change and is never compared this way. L9 says nothing about the
#      earlier proofs' own cuts — it says their ARTIFACTS are still the bytes those proofs were
#      written about, which is a precondition for running them at all.
#
# MEASURED COVERAGE, so the next author does not have to re-derive it, and so nobody mistakes ten
# assertions for ten independent opinions. Neuter one at a time and re-run --self-test; what then
# survives is what that assertion alone was catching:
#
#     for A in L0 L1 L2 L3 L4 L5 L6 L7 L8 L9; do sed "s|^    fails += $A(.*|    pass|" <this> > /tmp/n.sh
#       echo "$A: $(bash /tmp/n.sh --self-test | grep SURVIVED)"; done
#
#     L0 (none)  L1 (none)  L2 M10,M12-M15,M40  L3 (none)  L4 (none)  L5 M18-M26,M38,M39,M47
#     L6 M27,M28  L7 M29,M30  L8 M31-M34,M41-M46,M49,M50  L9 M35-M37,M48
#
# THAT LOOP IS NOT ENOUGH, and the ancestor's L5/2 is the proof it is not. An assertion is a
# handful of separate `if`s; neutering the whole function cannot tell you that ONE of those `if`s
# has never fired under any mutation. It looks like protection and has never been shown to work.
# So neuter one `if` at a time as well (`for s in required:` -> `for s in ():`,
# `if got_names != want_names:` -> `if False:`, and so on). The mutant each of these arms needs,
# being the only one that arm alone catches:
#
#     L5/2 shape M47   L5/2 OVERLAP M39   L8/required M50   L8/forbidden M44   L8/set M45,M46
#     L8/unreadable M49   L9/no-add-commit M48   L2/b0 M14,M15
#
# SIX of those arms had no such mutant until an adversarial review of THIS file measured it — one
# day after this same session wrote that very rule into CLAUDE.md. Writing the rule is not obeying
# it. Two footnotes a reader will otherwise trip over: neutering L5/2's shape arm CRASHES the run
# rather than surviving (with two open-below clauses the arm below it compares None to an int),
# so read a traceback as 'caught', not 'passed'; and no GAP mutant can be uniquely-L5/2, because
# the session ids are dense, so any gap wide enough to matter also strands a real record and
# trips L5/4. M38 is kept anyway — a gap and an overlap are different reader-facing mistakes.
#
# Those are MEASURED, not predicted. The first draft of this line said "L2 M10-M15" and was wrong:
# M11 leaves the third trim's stale routing table standing in the live front matter, so L5/1 sees
# it too and L2 is not the only assertion holding it. Run the loop; do not reason about it.
#
# RUNNING THAT LOOP IS HOW M38 AND M39 CAME TO EXIST, and it is the reason they are appended out of
# order at the end of the list rather than filed among the other L5 mutants. The third trim shipped
# `L5/2` — the clause that requires ROUTING to partition the session-id space with no gap and no
# overlap — and NOT ONE of its 28 mutants could reach it: the only two that mutate ROUTING itself
# (its M22, M23) both happen to stay contiguous, so the gap/overlap arm never executed under any
# mutation. That is precisely the defect the third trim caught in the second trim's `L2/b0`, one
# level further down, in the very assertion it was adding. It is not a coincidence twice: an
# assertion added late gets a mutant; a SUB-CLAUSE added inside it usually does not. M39 is the
# uniquely-L5/2 mutant (its overlap satisfies L5/1, L5/3 and L5/4 and only the partition check
# objects). M38 is a gap, and no gap mutant can be uniquely-L5/2 — the session ids are dense, so
# any gap wide enough to matter also strands a real record and trips L5/4. Said plainly rather than
# left for the next reader to discover.
#
# The other four assertions are not individually load-bearing, and saying so is the point:
#
#   * L0, L1 and L3 overlap by construction and always have — L1 is the primary byte detector and
#     L3 is per-record naming layered on top of it, so a mutant falsifies both or neither.
#   * L4 stopped being uniquely load-bearing when the third trim added L5/4, which catches a
#     whole-record boundary shift too (M16 -> the shard would hold Session 228; M17 -> the live
#     file would hold 227). It is kept anyway: it states the cut key directly instead of inferring
#     it, its failure message names the retained and archived sides, and an assertion is not
#     deadweight merely because a later, broader one happens to subsume it.
#
# This suite proves L0/L1/L3/L4 are jointly SUFFICIENT with the rest, not individually NECESSARY.
#
# The grammar is FROZEN into this file on purpose: a later change to the trim design must not
# silently change what THIS shard's proof means.
set -euo pipefail
exec python3 - "$@" <<'PYEOF'
import re, subprocess, sys
from collections import Counter

LIVE   = "SESSION_NOTES.md"
SHARD  = "docs/architecture-history/SESSION_NOTES-S227-through-S225.md"
CLAUDE = "CLAUDE.md"
ARCHIVE_DIR = "docs/architecture-history/"

# ---- the declared grammar (inherited unchanged; see the S216 shard's proof for why each clause) --
RECORD_START = re.compile(r"^### What Session (\S+) Did$")
FOOTER_MODE  = "none"     # ASSERTED by L0, not "don't look"
TRANSFORM    = None       # no rebase: the archived span is a pure byte slice
REGEN        = ()         # no regenerated front-matter fields — declared-empty, not unchecked

# `\S+` not `\d+`; `Did$` anchored; column-0 match. This cut's span contains NO duplicate heading
# and NO fenced block at all. Neither is special-cased anyway: both would ride inside the byte
# spans, and the fence-aware scan is kept because removing a clause that happens to be unexercised
# on one span is how a grammar rots. `\S+` still matters here for a second reason: L5 opens the
# S216 shard, whose ids include `20B` and `20A`, and a `\d+` grammar would merge them.

# ---- the declared CUT KEY. Hand-supplied, never read back from the artifacts (that would be
#      circular). L4 holds the records against it; L5 holds the prose routing tables against it. ----
CUT_RETAINED = ("231", "230", "229", "228")
CUT_ARCHIVED = ("227", "226", "225")

# ---- the declared ROUTING table: (lower, upper, file). None means open on that side. Every copy
#      of this table in prose must parse to exactly this, and this must agree with the cut key AND
#      with what the named files actually contain. ----
ROUTING = (
    (None, 216,  "SESSION_NOTES-through-S216.md"),
    (217,  220,  "SESSION_NOTES-S220-through-S217.md"),
    (221,  224,  "SESSION_NOTES-S224-through-S221.md"),
    (225,  227,  "SESSION_NOTES-S227-through-S225.md"),
    (228,  None, "SESSION_NOTES.md"),
)

# ---- L8's two files, and what this trim declares must (and must not) be true of each. The
#      required strings are hand-declared; the shard-name set is derived from ROUTING above. ----
README      = "README.md"
CONVENTIONS = "docs/methodology/PROJECT_CONVENTIONS.md"
BACKLOG     = "BACKLOG.md"
REACH = (
    (README,
     ("  SESSION_NOTES-S227-through-S225.md    # frozen SESSION_NOTES records, Sessions 227->225 (grep it; do not Read it)\n",
      "older in the four shards above"),
     ("older in the three shards above",)),
    (CONVENTIONS,
     ("**Four instances so far**",
      "`SESSION_NOTES-S227-through-S225.md` (Session 231, Sessions 227→225)"),
     ("**Three instances so far**",)),
    (BACKLOG,
     ("there are now **four** unwatched shards",
      "`SESSION_NOTES-S227-through-S225.md` (790 lines)"),
     ("there are now **three** unwatched shards",)),
    # CLAUDE.md is here for its PROSE only. L5 has always parsed its routing clauses; nothing has
    # ever read the count words around them, so a partial update — new table, stale "there are
    # THREE ... grep *all three*" — shipped green. Same blob, two assertions, different halves.
    (CLAUDE,
     ("there are FOUR, and a lookup must consult all of them",
      "**Trimmed four times (Sessions 222, 224, 228, 231):**",
      "Retired records live in **four** write-once shards",
      "grep *all four*"),
     ("there are THREE", "Trimmed three times", "**three** write-once shards",
      "grep *all three*")),
)
# The negative lookahead is load-bearing: without it this matches the `.md` PREFIX inside
# `...-S224-through-S221.md.verify.sh`, so README.md — which lists a shard and its proof on two
# lines — could lose a shard's own repo-map line and still yield the complete name set. Measured
# during review; M46 is the mutant that now catches it.
SHARD_NAME = re.compile(r"SESSION_NOTES-[A-Za-z0-9-]*\.md(?!\.verify)")

# ---- L9's scope: every shard OLDER than this one. Each is compared against the blob committed at
#      the commit that added IT, never at this trim's commit. ----
ANCESTORS = tuple(ARCHIVE_DIR + d for _lo, _hi, d in ROUTING
                  if d != LIVE and d != SHARD.rsplit("/", 1)[1])

POINTER = """**Fourth trim (Session 231). Archived Sessions 227 → 225 — 3 record headings, 738 lines** into
[`docs/architecture-history/SESSION_NOTES-S227-through-S225.md`](docs/architecture-history/SESSION_NOTES-S227-through-S225.md)
— same shape, same newest-on-top order, frozen and byte-for-byte unedited. **This live file now
holds Sessions 231 → 228 only** — four sessions, the floor `CLAUDE.md` sets. Its proof is
[`SESSION_NOTES-S227-through-S225.md.verify.sh`](docs/architecture-history/SESSION_NOTES-S227-through-S225.md.verify.sh):
the eight assertions inherited from the third trim plus **L8** (the three copies of the shard set
that no earlier proof could reach — `README.md`'s repo map, the shard-naming rule in
`docs/methodology/PROJECT_CONVENTIONS.md`, and `BACKLOG.md`'s read-cap item, which the third trim's
own sentence did not know was making the same claim — **and `CLAUDE.md`'s prose**, whose routing
table L5 always parsed while its *"there are THREE"* count words were read by nothing) and **L9**
(write-once enforced for
**every** shard on disk, not only the newest — L7 has only ever guarded the shard it shipped with,
so the S216 and S220 shards have never had any enforcement at all, and the S224 shard's lives only
inside its own proof, which nothing obliges a session to run).

**Four shards exist now, and none is a prefix of any other.** To place Session N, open the file
this table names. **This block is the authority**, and these five clauses are machine-checked here,
in the shard's banner, and in `CLAUDE.md`:

**N ≤ 216** → `SESSION_NOTES-through-S216.md`; **217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;
**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`; **225 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`;
**N ≥ 228** → `SESSION_NOTES.md`.

`grep` the shards; `Read` none of them. **Shards stay write-once** — a fifth trim writes a fifth
file; it never appends to one of these four.

**Two shard banners are stale now, and neither may be repaired.** The S220 shard's still says *"the
live ledger when N ≥ 221"*; the S224 shard's still routes Sessions 225 and up to this file. Both
were true at their own cut. The S220 proof predates L5 and cannot notice; the S224 proof has L5 but
reads its artifacts at its own trim commit, so it cannot notice either — and ours will join them at
the fifth trim. **A shard banner is a snapshot of its own cut; this block is the authority.** What is
no longer true is that `README.md` and `docs/methodology/PROJECT_CONVENTIONS.md` sit beyond every
proof's reach: **L8 holds them — and `BACKLOG.md` with them**, a third copy that sentence never
named, found by sweeping for the class instead of trusting the list. **Sweep again at the fifth
trim rather than trusting this list either**; `git grep -l 'SESSION_NOTES-'` is the whole sweep and
it takes a second. A fifth trim that leaves any of the four files L8 reads alone fails a proof
instead of quietly shipping a lie.

**The three blocks below are frozen at the THIRD, SECOND and FIRST trims and describe THOSE cuts.**
This trim falsified exactly four passages of the third trim's block — its claim about which sessions
this live file holds, its whole routing paragraph, the sentence putting `README.md` and
`PROJECT_CONVENTIONS.md` beyond every proof's reach, and its parenthetical calling **L7** the only
enforcement write-once has ever had, which **L9** has now made false — and rewrote all four as
declared substitutions the proof checks by exact equality. Every other byte of that block is original, and the second and first trims' blocks
are untouched. Each earlier proof reads its artifacts from the commit that added its own shard, so
this trim cannot disturb any of them; all three were re-run green at this cut, and a session that
doubts that should run them rather than reason about it.

"""

BANNER = """# Session Notes — archive shard: Sessions 227 → 225

**Frozen. Write-once. Do not edit this file.** It holds the record byte spans that the fourth trim
(Session 231, 2026-08-20) removed from `SESSION_NOTES.md`: Sessions 227 → 225 — three record
headings, 738 lines — in the same newest-on-top order, byte-for-byte unedited.

**This shard is the fourth of four, and the newest of them.** No shard is a prefix of another, and
none is authoritative alone. Session N lives in:

**N ≤ 216** → `SESSION_NOTES-through-S216.md`;
**217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;
**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`;
**225 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`;
**N ≥ 228** → `SESSION_NOTES.md`.

*(One clause per line, deliberately: the two-per-line wrap the pointer block uses puts the first
two clauses on a line that is byte-identical to the pre-trim front matter's, and the proof's
L2/b3 NO-LEAK assertion cannot tell that coincidence from a front-matter line that leaked into
this shard. It caught it on the first run. The fix belongs in the artifact, not the assertion.)*

**That table is a snapshot of the cut that wrote it.** A routing table inside a write-once file
cannot be repaired when the next trim lands, so the pointer block in `SESSION_NOTES.md` is the
authority and this is a convenience copy. Two banners already prove the hazard rather than merely
warning of it: the S220 shard's still says *"the live ledger when N ≥ 221"* and the S224 shard's
still routes Sessions 225 and up to the live ledger. Both were true when they were written. This one
joins them at the fifth trim.

**`grep` this file; do not `Read` it.** At 790 lines it sits under the 2,000-line agent read cap
today — but that cap truncates in silence, with no error and no missing-data marker, and no fleet
tooling watches this path (the dashboard's `READ_CAP_WATCHED` is an exact-path set that does not
contain it). That size is final: shards are write-once, so a fifth trim creates a fifth file rather
than growing this one.

**Provenance is proved here, not asserted.** Run `SESSION_NOTES-S227-through-S225.md.verify.sh`,
beside this file. It re-derives L0-L7 from the third trim's proof and adds the two assertions this
cut introduces: **L8**, which reaches the three copies of the shard set no earlier proof could check
— `README.md`'s repo map, the shard-naming rule in `docs/methodology/PROJECT_CONVENTIONS.md`, and
`BACKLOG.md`'s read-cap item, which no earlier trim had noticed was carrying the same count — and
`CLAUDE.md`'s prose besides, whose routing table L5 always read and whose count words nothing did;
and **L9**, which extends write-once enforcement from the
newest shard to **all four**, because L7 has only ever guarded the shard that shipped with it. Under
`--self-test` it mutates the artifacts fifty ways and fails if any mutation goes uncaught. Do
not believe this paragraph — run it.

**Cutting is by byte position, never by authorship.** Session 227's handoff evaluation is filed
inside Session 228's record, because this ledger files an evaluation under its author — so that
evaluation stayed behind in the live file while Session 227's own record came here. The same seam
brought Session 224's evaluation INTO this file, inside Session 225's record, out of the live file
where the third trim had left it. Expect this at every boundary, in both directions.

---

"""

# The ONLY edits to pre-existing front matter. Exact, uniquely anchored, checked by equality.
FRONT_SUBST = (
    ("— same shape, same newest-on-top order, frozen and byte-for-byte unedited. **This live file now\n"
     "holds Sessions 228 → 225 only** — four sessions, the floor `CLAUDE.md` sets. Its proof is\n",
     "— same shape, same newest-on-top order, frozen and byte-for-byte unedited. At that third cut\n"
     "this live file was left holding Sessions 228 → 225 — four sessions, the floor `CLAUDE.md`\n"
     "sets; the fourth trim above has since cut it again. Its proof is\n"),
    ("**Three shards exist now, and none is a prefix of any other.** To place Session N, open the file\n"
     "this table names. **This block is the authority**, and these four clauses are machine-checked here,\n"
     "in the shard's banner, and in `CLAUDE.md`:\n"
     "\n"
     "**N ≤ 216** → `SESSION_NOTES-through-S216.md`; **217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`;\n"
     "**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`; **N ≥ 225** → `SESSION_NOTES.md`.\n"
     "\n"
     "`grep` the shards; `Read` none of them. **Shards stay write-once** — a fourth trim writes a fourth\n"
     "file; it never appends to one of these three.\n",
     "**Three shards existed at that cut, and none was a prefix of any other.** The routing table that\n"
     "stood here named those three and sent every session from 225 up to this live file; the fourth trim\n"
     "falsified that last clause — Sessions 227 → 225 are in a shard now — and the table above replaces\n"
     "it. `grep` the shards; `Read` none. **Shards stay write-once** — a fourth trim wrote a fourth file;\n"
     "it did not append to one of those three.\n"),
    ("proof predates L5 and will never notice. Treat every shard banner as a snapshot of its own cut. Two\n"
     "further copies live outside every proof — `README.md`'s repo map and the shard-naming rule in\n"
     "`docs/methodology/PROJECT_CONVENTIONS.md` — and a trim that leaves either one alone ships a lie.\n",
     "proof predates L5 and will never notice. Treat every shard banner as a snapshot of its own cut. Two\n"
     "further copies were named here as outside every proof — `README.md`'s repo map and the shard-naming\n"
     "rule in `docs/methodology/PROJECT_CONVENTIONS.md` — and a trim that left either alone shipped a lie.\n"
     "There was a third nobody had named: `BACKLOG.md`'s read-cap item, carrying the same count. The\n"
     "fourth trim's **L8** checks all three.\n"),
    ("pinned byte-for-byte) and **L7** (that shard still being, on disk today, the bytes the proof was\n"
     "written about — the only enforcement `write-once` has ever had).\n",
     "pinned byte-for-byte) and **L7** (that shard still being, on disk today, the bytes the proof was\n"
     "written about — which was, until the fourth trim's **L9** extended the same check to every older\n"
     "shard, the only enforcement `write-once` had ever had).\n"),
)

MISSING = object()      # L7/L9: the file is absent from the working tree
NA      = object()      # L7: inapplicable — the trim is not committed yet

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, check=True).stdout.strip()


def blob(ref):
    r = subprocess.run(["git", "show", ref], capture_output=True, cwd=ROOT)
    if r.returncode:
        sys.exit("cannot read %s: %s" % (ref, r.stderr.decode("utf-8", "replace").strip()))
    return r.stdout.decode("utf-8")          # bytes -> str; never $(...) which eats trailing newlines


def worktree(rel):
    with open("%s/%s" % (ROOT, rel), encoding="utf-8", newline="") as fh:
        return fh.read()


def added_at(rel):
    """The commit that ADDED `rel`, or "" if git does not know of one."""
    return subprocess.run(["git", "log", "--diff-filter=A", "-1", "--format=%H", "--", rel],
                          capture_output=True, text=True, cwd=ROOT).stdout.strip()


def scan(lines):
    inside = False
    for i, raw in enumerate(lines):
        s = raw.rstrip("\r\n")
        if s.startswith("```") or s.startswith("~~~"):
            yield i, s, inside
            inside = not inside
            continue
        yield i, s, inside


def zones(text):
    """-> (front, [record, ...], lines). A record is a heading-delimited BYTE SPAN, never a session."""
    lines = text.splitlines(keepends=True)
    st = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)]
    if not st:
        return text, [], lines
    front = "".join(lines[:st[0]])
    bounds = st + [len(lines)]
    return front, ["".join(lines[a:b]) for a, b in zip(st, bounds[1:])], lines


def label(rec):
    for ln in rec.splitlines():
        if ln.strip():
            return ln.strip()[:90]
    return "(empty record)"


def ids(recs):
    """The session id captured from each record's own heading line, in order."""
    return tuple(RECORD_START.match(r.splitlines()[0]).group(1) for r in recs)


def declared(before_front):
    """The front matter this trim is ALLOWED to produce, before the pointer is inserted."""
    for old, new in FRONT_SUBST:
        before_front = before_front.replace(old, new, 1)
    return before_front


# One canonical clause shape, so all three copies of the table parse with one regex. Bounds AND
# destination in a single match: parsing them separately is what let the third trim's first draft
# of L5 check the numbers of a table whose filenames were swapped.
ROUTE_CLAUSE = re.compile(r"\*\*(?:(\d+) ≤ N ≤ (\d+)|N ≤ (\d+)|N ≥ (\d+))\*\* → `([^`]+)`")


def parse_table(text):
    out = []
    for a, b, le, ge, dest in ROUTE_CLAUSE.findall(text):
        if a:
            out.append((int(a), int(b), dest))
        elif le:
            out.append((None, int(le), dest))
        else:
            out.append((int(ge), None, dest))
    return tuple(out)


_ID_CACHE = {}


def numeric_ids(dest, after, shard, sha):
    """The numeric session ids actually present in the file `dest` names. LIVE and SHARD come from
    the artifacts already in hand so a mutant can move them; the earlier shards are read once from
    the same commit as everything else. Non-numeric ids (`20B`, `20A`) are dropped, and a
    destination that yields none is reported rather than passing vacuously."""
    if dest == LIVE:
        text = after
    elif dest == SHARD.rsplit("/", 1)[1]:
        text = shard
    else:
        key = (dest, sha)
        if key not in _ID_CACHE:
            path = ARCHIVE_DIR + dest
            try:
                _ID_CACHE[key] = blob("%s:%s" % (sha, path)) if sha else worktree(path)
            except (SystemExit, OSError):
                _ID_CACHE[key] = None
        text = _ID_CACHE[key]
        if text is None:
            return None
    return sorted(int(i) for i in ids(zones(text)[1]) if i.isdigit())


# =====================================================================================
# The assertions. Each returns a list of failure strings; empty == holds.
# =====================================================================================

def L0(name, text):
    """footer_mode='none' asserted: no standalone `---` after the last record start may carry
    content below it. In a newest-on-top ledger the footer sits exactly where an oldest-first cut
    takes from, so 'none' must mean 'I looked', not 'I did not look'."""
    front, recs, lines = zones(text)
    if not recs:
        return ["L0 %s: no records found — grammar mismatch" % name]
    last = [i for i, s, ins in scan(lines) if not ins and RECORD_START.match(s)][-1]
    out = []
    for i, s, ins in scan(lines):
        if not ins and i > last and s.strip() == "---":
            tail = "".join(lines[i + 1:])
            if tail.strip():
                out.append("L0 %s: trailing file-scoped block at line %d (%d B): %.400s"
                           % (name, i + 1, len(tail.encode()), tail))
    return out


def L1(before_recs, after_recs, shard_recs):
    """Concatenation identity scoped to the RECORDS zone. Operand order is load-bearing: this
    ledger is newest-on-top and the cut takes from the bottom, so retained precedes archived. No
    invert step — TRANSFORM is None, which makes this the strongest form. This is the PRIMARY
    byte-level detector; L3 adds per-record naming on top of it, and L4-L9 see what both are
    blind to."""
    got = "".join(after_recs) + "".join(shard_recs)
    want = "".join(before_recs)
    if got == want:
        return []
    i = next((n for n, (a, b) in enumerate(zip(got, want)) if a != b), min(len(got), len(want)))
    return ["L1: records-zone concatenation differs at character %d "
            "(retained+archived %d B vs before %d B)"
            % (i, len(got.encode()), len(want.encode()))]


def L2(before_front, after_front, shard_front, shard_recs, pointer):
    out = []
    # (a) footer half — inapplicable when FOOTER_MODE == "none"; say so, never claim it held.
    # (b) front-matter half. b1 is exact and subsumes b2; b2 and b3 still run because b1 is
    #     SKIPPED when the pointer is absent, and b3 is independent of all of it.
    for k, (old, _new) in enumerate(FRONT_SUBST, 1):
        if before_front.count(old) != 1:
            out.append("L2/b0 SUBSTITUTION %d NOT UNIQUELY ANCHORED: its source text occurs %d "
                       "times in the before front matter (want exactly 1) — the declaration has "
                       "gone stale against the file it claims to describe" % (k, before_front.count(old)))
    want_front = declared(before_front)
    if pointer not in after_front:
        out.append("L2_POINTER_MISSING: the declared pointer block is not in the live front matter "
                   "verbatim — a severed record set with no pointer to its shard")
    else:
        residue = after_front.replace(pointer, "", 1)
        if residue != want_front:
            i = next((n for n, (a, b) in enumerate(zip(residue, want_front)) if a != b),
                     min(len(residue), len(want_front)))
            out.append("L2/b1 CONFINEMENT: live front matter changed beyond the declared pointer "
                       "insertion + the %d declared substitutions; first divergence at character "
                       "%d (%d B residue vs %d B declared)"
                       % (len(FRONT_SUBST), i, len(residue.encode()), len(want_front.encode())))
    after_set = set(after_front.splitlines())
    for ln in want_front.splitlines():
        if ln.strip() and ln not in after_set:      # exact membership, never substring (BL-28)
            out.append("L2/b2 SURVIVAL: front-matter line vanished: %r" % ln[:120])
    body = shard_front + "".join(shard_recs)
    for ln in before_front.splitlines():
        s = ln.strip()
        if len(s) > 24 and s in body:
            out.append("L2/b3 NO-LEAK: front-matter line leaked into the shard: %r" % s[:120])
    return out


def L3(before_recs, after_recs, shard_recs):
    """Per-record partition by identity, ORDER and byte-equality. The injected set is MEASURED from
    record content, never baked in as a generation-time constant — that constant is why 5 of the 20
    proofs shipped across this fleet fail with zero data loss."""
    have = Counter(after_recs) + Counter(shard_recs)
    before_c = Counter(before_recs)
    absent = list((before_c - have).elements())
    added = list((have - before_c).elements())
    out = []
    for r in absent:
        out.append("L3 MISSING: a record from `before` is in neither artifact "
                   "(dropped, or edited so its original bytes exist nowhere): %s" % label(r))
    for r in added:
        # Project strengthening: this design forbids bundling any record edit into the trim commit
        # (three commits, by rule — claim, trim, close-out), so a non-zero added count means the
        # rule was broken. Deliberate divergence from the canonical tool, which downgraded this to
        # a note in v1.2.0 because the canonical repo bundles by practice.
        out.append("L3 ADDED: a record exists that was not in `before` — the trim commit "
                   "bundled a record edit: %s" % label(r))
    if not absent and not added:
        rebuilt, pool = [], Counter(added)
        for r in after_recs + shard_recs:
            if pool[r]:
                pool[r] -= 1
                continue
            rebuilt.append(r)
        bad = [i for i, (a, b) in enumerate(zip(before_recs, rebuilt)) if a != b]
        if bad or len(rebuilt) != len(before_recs):
            out.append("L3 ORDER: records out of order at indices %s" % bad[:12])
    return out


def L4(after_recs, shard_recs):
    """The cut point itself. L1 and L3 are blind to a whole-record boundary shift because it
    preserves concatenation, multiset membership and order simultaneously. This compares each side
    against the HAND-DECLARED cut key; reading the key back out of the artifacts would make it a
    restatement rather than an assertion."""
    out = []
    got_a, got_s = ids(after_recs), ids(shard_recs)
    if got_a != CUT_RETAINED:
        out.append("L4 CUT/retained: the live file holds Sessions %s; the declared cut key says %s"
                   % (list(got_a), list(CUT_RETAINED)))
    if got_s != CUT_ARCHIVED:
        out.append("L4 CUT/archived: the shard holds Sessions %s; the declared cut key says %s"
                   % (list(got_s), list(CUT_ARCHIVED)))
    return out


def L5(after_front, shard_front, claude, after, shard, sha, routing):
    """Routing coherence — see the third trim's proof for the full rationale. Everything above is
    about BYTES. This is about the sentence a human acts on: which file to open for Session N.
    Five layers, because each catches something the others cannot."""
    out = []
    lo_a, hi_a = min(map(int, CUT_ARCHIVED)), max(map(int, CUT_ARCHIVED))
    lo_r = min(map(int, CUT_RETAINED))
    shard_base = SHARD.rsplit("/", 1)[1]

    # (1) every prose copy of the table must parse to exactly the declaration — bounds AND file.
    for who, text in (("live pointer", after_front), ("shard banner", shard_front),
                      ("CLAUDE.md", claude)):
        got = parse_table(text)
        if got != routing:
            out.append("L5/1 %s: its routing table parses to %s; the declaration says %s"
                       % (who, list(got), list(routing)))

    # (2) the declaration must partition the session-id space: one open below, one open above,
    #     contiguous in between, no gap and no overlap.
    below = [c for c in routing if c[0] is None]
    above = [c for c in routing if c[1] is None]
    if len(below) != 1 or len(above) != 1 or routing[0][0] is not None or routing[-1][1] is not None:
        out.append("L5/2 shape: want exactly one open-below clause first and one open-above clause "
                   "last; got %d and %d in %s" % (len(below), len(above), list(routing)))
    else:
        edge = routing[0][1]
        for lo, hi, dest in routing[1:-1]:
            if lo != edge + 1:
                out.append("L5/2 %s at %d-%d (`%s`): the preceding clause ends at %d"
                           % ("GAP" if lo > edge + 1 else "OVERLAP", lo, hi, dest, edge))
            edge = hi
        if routing[-1][0] != edge + 1:
            out.append("L5/2 %s between the last range (ends %d) and `N >= %d` (`%s`)"
                       % ("GAP" if routing[-1][0] > edge + 1 else "OVERLAP", edge,
                          routing[-1][0], routing[-1][2]))

    # (3) the clause naming THIS shard must be exactly this cut's archived span, and the clause
    #     naming the live ledger must open exactly at this cut's retained floor.
    mine = [c for c in routing if c[2] == shard_base]
    live = [c for c in routing if c[2] == LIVE]
    if len(mine) != 1 or mine[0][:2] != (lo_a, hi_a):
        out.append("L5/3 shard clause: the table routes %s to `%s`; this cut archived Sessions "
                   "%d-%d" % ([c[:2] for c in mine], shard_base, lo_a, hi_a))
    if len(live) != 1 or live[0][:2] != (lo_r, None):
        out.append("L5/3 live clause: the table routes %s to `%s`; this cut retained Sessions "
                   "%d and up" % ([c[:2] for c in live], LIVE, lo_r))

    # (4) THE ANCHOR AGAINST REALITY. A declaration can be wrong in a way that is perfectly
    #     self-consistent — move a boundary in every copy at once and (1)-(3) all still hold. So
    #     open each file the table names and check what is actually in it.
    for lo, hi, dest in routing:
        found = numeric_ids(dest, after, shard, sha)
        if found is None:
            out.append("L5/4 `%s`: the table routes Sessions %s-%s here and the file cannot be "
                       "read" % (dest, lo, hi))
            continue
        if not found:
            out.append("L5/4 `%s`: no numeric session ids found — the check would pass vacuously"
                       % dest)
            continue
        stray = [n for n in found if (lo is not None and n < lo) or (hi is not None and n > hi)]
        if stray:
            out.append("L5/4 `%s`: routed Sessions %s-%s, but it actually contains %s (ids %d-%d)"
                       % (dest, lo, hi, stray[:8], found[0], found[-1]))
    return out


def L6(shard_front, banner):
    """The shard banner, pinned byte-for-byte — the shard-side analogue of L2/b1. Without it the
    banner is the one part of the shard that is neither frozen nor checked, while its own text says
    provenance is proved here."""
    if shard_front == banner:
        return []
    i = next((n for n, (a, b) in enumerate(zip(shard_front, banner)) if a != b),
             min(len(shard_front), len(banner)))
    return ["L6 BANNER: the shard's banner is not the declared text; first divergence at character "
            "%d (%d B in the shard vs %d B declared)"
            % (i, len(shard_front.encode()), len(banner.encode()))]


def L7(sha, shard_blob, disk):
    """Write-once, enforced, for THIS shard. Everything else reads history at the trim commit, so
    the suite stays green through any later truncation or deletion of it. Asymmetric on purpose:
    the live ledger is SUPPOSED to change and is never compared this way.

    Applicability is decided by `disk` ALONE and never by `sha` — see the third trim's proof for
    why a stand-in sha makes every mutant 'caught' for the wrong reason."""
    if disk is NA:
        return []                      # not committed yet; the run banner says so rather than
                                       # letting silence read as a pass
    if disk is MISSING:
        return ["L7 WRITE-ONCE: the shard is GONE from the working tree. Every assertion above "
                "still passes because they read git history at the trim commit — this one is the "
                "reason you found out."]
    if disk != shard_blob:
        i = next((n for n, (a, b) in enumerate(zip(disk, shard_blob)) if a != b),
                 min(len(disk), len(shard_blob)))
        return ["L7 WRITE-ONCE: the shard on disk is not the shard committed at %s; first "
                "divergence at character %d (%d B on disk vs %d B committed). Shards are "
                "write-once; this file was edited after its trim."
                % (sha[:7] if sha else "the trim commit", i,
                   len(disk.encode()), len(shard_blob.encode()))]
    return []


def L8(reach_texts):
    """The two copies that lived outside every earlier proof. Both halves matter and neither
    subsumes the other: the hand-declared strings catch a stale COUNT WORD, which is prose and
    invisible to any derived check; the ROUTING-derived set catches a shard left out or a phantom
    one, without restating the list a second time and giving it a second chance to go stale."""
    out = []
    want_names = {d for _lo, _hi, d in ROUTING if d != LIVE}
    for path, required, forbidden in REACH:
        text = reach_texts.get(path)
        if text is None:
            out.append("L8 `%s`: unreadable, so no copy of the shard set in it can be checked"
                       % path)
            continue
        for s in required:
            if s not in text:
                out.append("L8/required `%s`: this trim declares it must contain %r and it does "
                           "not — the copy no earlier proof could reach is now stale" % (path, s[:90]))
        for s in forbidden:
            if s in text:
                out.append("L8/forbidden `%s`: it still contains %r, which this trim falsified"
                           % (path, s[:90]))
        got_names = set(SHARD_NAME.findall(text))
        if got_names != want_names:
            out.append("L8/set `%s`: it names shards %s; ROUTING names %s (missing %s; unknown %s)"
                       % (path, sorted(got_names), sorted(want_names),
                          sorted(want_names - got_names) or "none",
                          sorted(got_names - want_names) or "none"))
    return out


def L9(lineage):
    """Write-once for the WHOLE lineage, not just the shard this proof shipped with. Each ancestor
    is compared against the blob committed at the commit that ADDED it — its own commit, never this
    trim's — so this is applicable from the first run, before this trim is committed at all.

    L7 has guarded exactly one file since it was introduced. Every other assertion here reads git
    history, so an ancestor shard truncated or deleted on disk leaves this suite green while the
    routing table keeps sending readers to it."""
    out = []
    for path, committed, disk in lineage:
        if committed is None:
            out.append("L9 `%s`: git knows no commit that added it, so there is nothing to hold "
                       "the working tree against" % path)
            continue
        if disk is MISSING:
            out.append("L9 WRITE-ONCE `%s`: GONE from the working tree. The routing table still "
                       "sends readers here and every byte assertion above still passes, because "
                       "they read history." % path)
            continue
        if disk != committed:
            i = next((n for n, (a, b) in enumerate(zip(disk, committed)) if a != b),
                     min(len(disk), len(committed)))
            out.append("L9 WRITE-ONCE `%s`: on disk it is not the file that was committed; first "
                       "divergence at character %d (%d B on disk vs %d B committed). Shards are "
                       "write-once — this one was edited after its own trim."
                       % (path, i, len(disk.encode()), len(committed.encode())))
    return out


def check(before, after, shard, claude, sha, disk, reach_texts, lineage, decl=None):
    d = {"POINTER": POINTER, "BANNER": BANNER, "ROUTING": ROUTING}
    if decl:
        d.update(decl)
    bf, br, _ = zones(before)
    af, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    fails = []
    fails += L0("before", before) + L0("after", after) + L0("shard", shard)
    fails += L1(br, ar, sr)
    fails += L2(bf, af, sf, sr, d["POINTER"])
    fails += L3(br, ar, sr)
    fails += L4(ar, sr)
    fails += L5(af, sf, claude, after, shard, sha, d["ROUTING"])
    fails += L6(sf, d["BANNER"])
    fails += L7(sha, shard, disk)
    fails += L8(reach_texts)
    fails += L9(lineage)
    return fails, (br, ar, sr)


# =====================================================================================
def artifacts():
    sha = added_at(SHARD)
    # L9's operands never depend on `sha`: each ancestor is held against ITS OWN add-commit.
    lineage = []
    for path in ANCESTORS:
        a = added_at(path)
        committed = blob("%s:%s" % (a, path)) if a else None
        try:
            on_disk = worktree(path)
        except OSError:
            on_disk = MISSING
        lineage.append((path, committed, on_disk))
    lineage = tuple(lineage)

    if sha:
        try:
            disk = worktree(SHARD)
        except OSError:
            disk = MISSING
        reach = {}
        for p, _r, _f in REACH:
            try:                                  # so L8's unreadable arm is live code, not dead
                reach[p] = blob("%s:%s" % (sha, p))
            except SystemExit:
                reach[p] = None
        return (blob("%s^:%s" % (sha, LIVE)), blob("%s:%s" % (sha, LIVE)),
                blob("%s:%s" % (sha, SHARD)), blob("%s:%s" % (sha, CLAUDE)),
                "the trim commit %s" % sha[:7], sha, disk, reach, lineage)
    reach = {}
    for p, _r, _f in REACH:
        try:
            reach[p] = worktree(p)
        except OSError:
            reach[p] = None
    return (blob("HEAD:%s" % LIVE), worktree(LIVE), worktree(SHARD), worktree(CLAUDE),
            "HEAD vs the working tree (trim not yet committed)", None, NA, reach, lineage)


def self_test(before, after, shard, claude, sha, reach, lineage):
    _, ar, _ = zones(after)
    sf, sr, _ = zones(shard)
    purpose = next(ln for ln in zones(before)[0].splitlines() if ln.startswith("**Purpose:**"))

    def sub_in_shard(o, n, count=1):
        assert o in shard, "self-test fixture missing: %r" % o[:40]
        return shard.replace(o, n, count)

    assert "−" in "".join(sr), "self-test fixture missing: no U+2212 in the archived span"
    assert "−" not in sf, "fixture broken: M9 must mutate a RECORD, not the shard banner"

    # Every clause a mutant rewrites must be unambiguous in every text that carries it.
    CL216  = "**N ≤ 216** → `SESSION_NOTES-through-S216.md`"
    CL220  = "**217 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`"
    CL224  = "**221 ≤ N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`"
    CL227  = "**225 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`"
    CLLIVE = "**N ≥ 228** → `SESSION_NOTES.md`"
    for cl in (CL216, CL220, CL224, CL227, CLLIVE):
        for name, text in (("POINTER", POINTER), ("BANNER", BANNER),
                           ("live file", after), ("shard", shard), ("CLAUDE.md", claude)):
            assert text.count(cl) == 1, ("self-test fixture %r occurs %d times in %s (want 1)"
                                         % (cl[:28], text.count(cl), name))

    def rewrite(pairs, texts):
        """Apply the same clause rewrites to every text that carries the table."""
        out = []
        for t in texts:
            for o, n in pairs:
                t = t.replace(o, n, 1)
            out.append(t)
        return out

    # --- L5 fixtures. Each rewrites the DECLARATION and the artifact together, so the assertion
    #     that pins them by equality (L2 for the pointer, L6 for the banner) stays satisfied and
    #     L5 is the only one left able to object.
    m18_b, m18_s = rewrite([(CLLIVE, "**N ≥ 225** → `SESSION_NOTES.md`")], [BANNER, shard])
    m19_b, m19_s = rewrite([(CL227, "**224 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`")],
                           [BANNER, shard])
    m20_p, m20_a = rewrite([(CLLIVE, "**N ≥ 225** → `SESSION_NOTES.md`")], [POINTER, after])
    m21_p, m21_a = rewrite([(CL227, "**226 ≤ N ≤ 227** → `SESSION_NOTES-S227-through-S225.md`")],
                           [POINTER, after])
    swap = [(CL224, "**221 ≤ N ≤ 224** → `SESSION_NOTES-S227-through-S225.md`"),
            (CL227, "**225 ≤ N ≤ 227** → `SESSION_NOTES-S224-through-S221.md`")]
    m22_b, m22_s = rewrite(swap, [BANNER, shard])
    m23_p, m23_a = rewrite(swap, [POINTER, after])

    # M24/M25/M38/M39 rewrite ROUTING as well, so even the declaration is self-consistent.
    short = [(CL227, "**225 ≤ N ≤ 226** → `SESSION_NOTES-S227-through-S225.md`"),
             (CLLIVE, "**N ≥ 227** → `SESSION_NOTES.md`")]
    m24_p, m24_b, m24_a, m24_s, m24_c = rewrite(short, [POINTER, BANNER, after, shard, claude])
    m24_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 224, "SESSION_NOTES-S224-through-S221.md"),
             (225, 226, "SESSION_NOTES-S227-through-S225.md"),
             (227, None, "SESSION_NOTES.md"))
    front = [(CL216, "**N ≤ 100** → `SESSION_NOTES-through-S216.md`"),
             (CL220, "**101 ≤ N ≤ 220** → `SESSION_NOTES-S220-through-S217.md`")]
    m25_p, m25_b, m25_a, m25_s, m25_c = rewrite(front, [POINTER, BANNER, after, shard, claude])
    m25_r = ((None, 100, "SESSION_NOTES-through-S216.md"),
             (101, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 224, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, None, "SESSION_NOTES.md"))
    gap = [(CL224, "**221 ≤ N ≤ 223** → `SESSION_NOTES-S224-through-S221.md`")]
    m38_p, m38_b, m38_a, m38_s, m38_c = rewrite(gap, [POINTER, BANNER, after, shard, claude])
    m38_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 223, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, None, "SESSION_NOTES.md"))
    over = [(CL224, "**221 ≤ N ≤ 225** → `SESSION_NOTES-S224-through-S221.md`")]
    shape = [(CL224, "**N ≤ 224** → `SESSION_NOTES-S224-through-S221.md`")]
    m39_p, m39_b, m39_a, m39_s, m39_c = rewrite(over, [POINTER, BANNER, after, shard, claude])
    m39_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (221, 225, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, None, "SESSION_NOTES.md"))
    m47_p, m47_b, m47_a, m47_s, m47_c = rewrite(shape, [POINTER, BANNER, after, shard, claude])
    m47_r = ((None, 216, "SESSION_NOTES-through-S216.md"),
             (217, 220, "SESSION_NOTES-S220-through-S217.md"),
             (None, 224, "SESSION_NOTES-S224-through-S221.md"),
             (225, 227, "SESSION_NOTES-S227-through-S225.md"),
             (228, None, "SESSION_NOTES.md"))

    # M16/M17 move ONE WHOLE RECORD across the boundary. ar[-1] is the oldest retained record and
    # sr[0] the newest archived one, so both mutants keep the newest-on-top order intact — which is
    # exactly why L1 and L3 cannot see them and L4 must.
    m16_after, m16_shard = after.replace(ar[-1], "", 1), sf + ar[-1] + "".join(sr)
    m17_after, m17_shard = after + sr[0], shard.replace(sr[0], "", 1)

    # --- L8 fixtures. Each mutates ONE of the two out-of-reach files; nothing else in the suite
    #     reads either of them, so these are L8's alone.
    def reach_with(path, old, new):
        assert reach[path].count(old) >= 1, "self-test fixture missing in %s: %r" % (path, old[:50])
        r = dict(reach)
        r[path] = r[path].replace(old, new, 1)
        return r
    m31 = reach_with(README, "older in the four shards above", "older in the three shards above")
    m32 = reach_with(README, REACH[0][1][0], "")
    m33 = reach_with(CONVENTIONS, "**Four instances so far**", "**Three instances so far**")
    m34 = reach_with(CONVENTIONS, "`SESSION_NOTES-S227-through-S225.md` (Session 231",
                     "`SESSION_NOTES-S226-through-S225.md` (Session 231")
    m41 = reach_with(BACKLOG, "there are now **four** unwatched shards",
                     "there are now **three** unwatched shards")
    m42 = reach_with(BACKLOG, "`SESSION_NOTES-S227-through-S225.md` (790 lines)", "")

    # --- Sub-clause fixtures. An adversarial review of THIS file measured that L8/forbidden,
    #     L8/set, L5/2's shape arm, L9's no-add-commit arm and L8's unreadable arm were each
    #     reachable by no mutant above — the defect this session had just diagnosed in its own
    #     ancestor's L5/2 and written into CLAUDE.md as a rule. These are that rule applied to me.
    m43 = dict(reach)                                    # CLAUDE.md: table intact, count words stale
    m43[CLAUDE] = (m43[CLAUDE]
                   .replace("**Trimmed four times (Sessions 222, 224, 228, 231):**",
                            "**Trimmed three times (Sessions 222, 224, 228):**", 1)
                   .replace("Retired records live in **four** write-once shards",
                            "Retired records live in **three** write-once shards", 1)
                   .replace("grep *all four*", "grep *all three*", 1)
                   .replace("there are FOUR, and a lookup must consult all of them",
                            "there are THREE, and a lookup must consult all of them", 1))
    # forbidden ALONE: the required string stays, the falsified one comes back beside it.
    m44 = reach_with(CONVENTIONS, "**Four instances so far**",
                     "**Four instances so far** — it said **Three instances so far** before this cut")
    # set ALONE: an ANCESTOR's name typo'd, so required and forbidden are both untouched.
    m45 = reach_with(CONVENTIONS, "`SESSION_NOTES-S224-through-S221.md` (Session 228",
                     "`SESSION_NOTES-S224-through-S220.md` (Session 228")
    # set, via the lookahead: drop an ancestor's own repo-map line and leave its `.verify.sh` line.
    m46 = reach_with(README,
                     "  SESSION_NOTES-S224-through-S221.md    # frozen SESSION_NOTES records, Sessions 224->221 (grep it; do not Read it)\n",
                     "")
    # L9's third arm: git knows the file but no commit that added it.
    m48 = tuple((p, None, d) if i == 0 else (p, c, d)
                for i, (p, c, d) in enumerate(lineage))
    # L8's unreadable arm.
    m49 = {k: v for k, v in reach.items() if k != README}
    m49[README] = None
    # required ALONE: a declared string reworded so no forbidden string appears and the shard
    # name set stays complete. Without this, nothing is caught by L8/required and nothing else.
    m50 = reach_with(CONVENTIONS, "**Four instances so far**", "**4 instances so far**")

    # --- L9 fixtures. Same shape as L7's, one level out: the ANCESTOR shards on disk.
    def lineage_with(idx, mutate):
        out = list(lineage)
        path, committed, on_disk = out[idx]
        out[idx] = (path, committed, mutate(on_disk))
        return tuple(out)
    m35 = lineage_with(0, lambda t: t[:20000])
    m36 = lineage_with(1, lambda _t: MISSING)
    m37 = lineage_with(2, lambda t: t.replace("e", "3", 1))

    SAME = object()          # the mutant's own shard, i.e. an untampered working tree
    mutants = [
        ("M1  last byte of the shard's last record deleted", before, after, shard[:-1], claude, None, SAME, reach, lineage),
        ("M2  one whole archived record deleted", before, after, shard.replace(sr[1], "", 1), claude, None, SAME, reach, lineage),
        ("M3  one character flipped inside an archived record", before, after,
         sub_in_shard(sr[1], sr[1].replace("e", "3", 1)), claude, None, SAME, reach, lineage),
        ("M4  one character flipped inside a retained record", before,
         after.replace(ar[-1], ar[-1].replace("e", "3", 1), 1), shard, claude, None, SAME, reach, lineage),
        ("M5  two adjacent archived records swapped", before, after,
         sub_in_shard(sr[1] + sr[2], sr[2] + sr[1]), claude, None, SAME, reach, lineage),
        ("M6  a front-matter line moved from the live file into the shard banner", before,
         after.replace(purpose + "\n", "", 1),
         shard.replace("---\n\n### What Session", purpose + "\n\n---\n\n### What Session", 1),
         claude, None, SAME, reach, lineage),
        ("M7  a trailing file-scoped block appended below the shard's last record", before, after,
         shard + "\n---\n\ntrailing paragraph\n", claude, None, SAME, reach, lineage),
        ("M8  the pointer block dropped from the live front matter", before,
         after.replace(POINTER, "", 1), shard, claude, None, SAME, reach, lineage),
        ("M9  U+2212 silently normalised to ASCII '-' in an archived record", before, after,
         sub_in_shard("−", "-"), claude, None, SAME, reach, lineage),
        ("M10 declared substitution 1 not applied (stale 'holds Sessions 228 → 225 only')", before,
         after.replace(FRONT_SUBST[0][1], FRONT_SUBST[0][0], 1), shard, claude, None, SAME, reach, lineage),
        ("M11 declared substitution 2 not applied (the stale three-shard table left standing)", before,
         after.replace(FRONT_SUBST[1][1], FRONT_SUBST[1][0], 1), shard, claude, None, SAME, reach, lineage),
        ("M12 declared substitution 3 not applied (stale 'outside every proof')", before,
         after.replace(FRONT_SUBST[2][1], FRONT_SUBST[2][0], 1), shard, claude, None, SAME, reach, lineage),
        ("M13 an UNDECLARED extra front-matter edit alongside the declared ones", before,
         after.replace("this paragraph is the only warning there is.",
                       "this paragraph is the only warning there was.", 1), shard, claude, None, SAME, reach, lineage),
        ("M14 substitution 1's anchor absent from `before` (declaration gone stale)",
         before.replace(FRONT_SUBST[0][0], "REPLACED BY AN EARLIER EDIT\n", 1), after, shard,
         claude, None, SAME, reach, lineage),
        ("M15 substitution 3's anchor absent from `before` (declaration gone stale)",
         before.replace(FRONT_SUBST[2][0], "REPLACED BY AN EARLIER EDIT\n", 1), after, shard,
         claude, None, SAME, reach, lineage),
        ("M16 cut shifted: the oldest RETAINED record moved into the shard", before,
         m16_after, m16_shard, claude, None, SAME, reach, lineage),
        ("M17 cut shifted: the newest ARCHIVED record kept in the live file", before,
         m17_after, m17_shard, claude, None, SAME, reach, lineage),
        ("M18 banner + its declaration agree on a stale `N ≥ 225`", before, after, m18_s,
         claude, {"BANNER": m18_b}, SAME, reach, lineage),
        ("M19 banner + its declaration agree on a 224-227 range (overlaps the S224 shard)", before,
         after, m19_s, claude, {"BANNER": m19_b}, SAME, reach, lineage),
        ("M20 pointer + its declaration agree on a stale `N ≥ 225`", before, m20_a, shard,
         claude, {"POINTER": m20_p}, SAME, reach, lineage),
        ("M21 pointer + its declaration agree on a 226-227 range (Session 225 unroutable)", before,
         m21_a, shard, claude, {"POINTER": m21_p}, SAME, reach, lineage),
        ("M22 banner: numbers untouched, the S224/S227 FILENAMES swapped", before, after, m22_s,
         claude, {"BANNER": m22_b}, SAME, reach, lineage),
        ("M23 pointer: numbers untouched, the S224/S227 FILENAMES swapped", before, m23_a, shard,
         claude, {"POINTER": m23_p}, SAME, reach, lineage),
        ("M24 every copy AND the declaration agree this shard holds 225-226", before, m24_a, m24_s,
         m24_c, {"POINTER": m24_p, "BANNER": m24_b, "ROUTING": m24_r}, SAME, reach, lineage),
        ("M25 every copy AND the declaration move the S216/S220 frontier to 100/101", before,
         m25_a, m25_s, m25_c, {"POINTER": m25_p, "BANNER": m25_b, "ROUTING": m25_r}, SAME, reach, lineage),
        ("M26 CLAUDE.md's copy of the table left stale", before, after, shard,
         claude.replace(CLLIVE, "**N ≥ 225** → `SESSION_NOTES.md`", 1), None, SAME, reach, lineage),
        ("M27 the shard's banner headline claims a different session range", before, after,
         sub_in_shard("archive shard: Sessions 227 → 225", "archive shard: Sessions 224 → 221"),
         claude, None, SAME, reach, lineage),
        ("M28 an extra paragraph inserted into the shard's banner", before, after,
         sub_in_shard("---\n\n### What Session", "\nInserted later by someone helpful.\n\n---\n\n### What Session"),
         claude, None, SAME, reach, lineage),
        ("M29 the shard TRUNCATED on disk after the trim commit", before, after, shard, claude,
         None, shard[:20000], reach, lineage),
        ("M30 the shard DELETED from the working tree after the trim commit", before, after, shard,
         claude, None, MISSING, reach, lineage),
        ("M31 README.md still says 'the three shards above'", before, after, shard, claude,
         None, SAME, m31, lineage),
        ("M32 README.md's repo map never names the new shard", before, after, shard, claude,
         None, SAME, m32, lineage),
        ("M33 PROJECT_CONVENTIONS.md still says 'Three instances so far'", before, after, shard,
         claude, None, SAME, m33, lineage),
        ("M34 PROJECT_CONVENTIONS.md names a phantom shard instead of the new one", before, after,
         shard, claude, None, SAME, m34, lineage),
        ("M35 an ANCESTOR shard (S216) truncated on disk", before, after, shard, claude,
         None, SAME, reach, m35),
        ("M36 an ANCESTOR shard (S220) deleted from the working tree", before, after, shard,
         claude, None, SAME, reach, m36),
        ("M37 an ANCESTOR shard (S224) edited by one character on disk", before, after, shard,
         claude, None, SAME, reach, m37),
        # Appended out of order: found by running the neuter loop in this file's header, which
        # showed L5/2 was reachable by no mutant above. See the header note.
        ("M38 every copy AND the declaration leave Session 224 unrouted (GAP)", before, m38_a,
         m38_s, m38_c, {"POINTER": m38_p, "BANNER": m38_b, "ROUTING": m38_r}, SAME, reach, lineage),
        ("M39 every copy AND the declaration route Session 225 to two files (OVERLAP)", before,
         m39_a, m39_s, m39_c, {"POINTER": m39_p, "BANNER": m39_b, "ROUTING": m39_r}, SAME, reach, lineage),
        ("M40 declared substitution 4 not applied (L7 still called the only write-once enforcement)",
         before, after.replace(FRONT_SUBST[3][1], FRONT_SUBST[3][0], 1), shard, claude, None, SAME,
         reach, lineage),
        ("M41 BACKLOG.md's read-cap item still says 'three unwatched shards'", before, after,
         shard, claude, None, SAME, m41, lineage),
        ("M42 BACKLOG.md's read-cap item never names the new shard", before, after, shard,
         claude, None, SAME, m42, lineage),
        ("M43 CLAUDE.md: five correct routing clauses, count words still saying three", before,
         after, shard, claude, None, SAME, m43, lineage),
        ("M44 PROJECT_CONVENTIONS.md: the falsified count restored BESIDE the correct one", before,
         after, shard, claude, None, SAME, m44, lineage),
        ("M45 PROJECT_CONVENTIONS.md: an ANCESTOR shard's filename typo'd", before, after, shard,
         claude, None, SAME, m45, lineage),
        ("M46 README.md: an ancestor's own map line dropped, its `.verify.sh` line left", before,
         after, shard, claude, None, SAME, m46, lineage),
        ("M47 every copy AND the declaration open TWO clauses below (shape)", before, m47_a,
         m47_s, m47_c, {"POINTER": m47_p, "BANNER": m47_b, "ROUTING": m47_r}, SAME, reach, lineage),
        ("M48 an ancestor shard git knows no add-commit for", before, after, shard, claude,
         None, SAME, reach, m48),
        ("M49 a file L8 must read is unreadable", before, after, shard, claude, None, SAME,
         m49, lineage),
        ("M50 a declared required string reworded, nothing else disturbed", before, after, shard,
         claude, None, SAME, m50, lineage),
    ]
    bad = []
    for name, b, a, s, c, decl, disk, rch, lin in mutants:
        # A mutant that does not name a disk state gets an untampered one: its own shard.
        d = s if disk is SAME else disk
        # The REAL sha, never a stand-in: L5/4 reads the ancestor shards through it, and a fake
        # one makes every one of them unreadable — which would "catch" every mutant by breaking
        # the proof rather than by detecting the mutation. L7 and L9 stay reachable regardless
        # because their applicability comes from `d` and `lin`, not from `sha`.
        fails, _ = check(b, a, s, c, sha, d, rch, lin, decl)
        if not fails:
            bad.append(name)
            print("  SURVIVED  %s" % name)
        else:
            # EVERY assertion that fires, not just the first: it must stay visible which assertion
            # is doing the work. A reader who thinks L3 is an independent second opinion on L1 is
            # mistaken — and M16-M50 are the thirty-five that prove L4-L9 are not either.
            codes = sorted({f.split(":")[0].split(" (")[0] for f in fails})
            print("  caught    %-72s -> %s" % (name, ", ".join(codes)))
    if bad:
        print("\nSELF-TEST FAILED: %d mutant(s) survived. This proof cannot be trusted." % len(bad))
        sys.exit(2)
    print("\nSELF-TEST OK: all %d mutants caught. Losing a byte fails this proof; so does editing"
          % len(mutants))
    print("one, skipping any declared correction, making an undeclared one, letting a declaration")
    print("go stale, sliding the cut point by one record, mis-stating where a session lives even")
    print("when every copy agrees, leaving a gap or an overlap in the routing table, editing the")
    print("shard's banner, touching ANY shard on disk after the commit that froze it, or leaving")
    print("README.md or PROJECT_CONVENTIONS.md describing the shard set that existed before.")


before, after, shard, claude, source, sha, disk, reach, lineage = artifacts()

if "--self-test" in sys.argv:
    print("--self-test: mutating the artifacts and asserting each mutation is caught.\n")
    self_test(before, after, shard, claude, sha, reach, lineage)
    sys.exit(0)

fails, (br, ar, sr) = check(before, after, shard, claude, sha, disk, reach, lineage)
have = Counter(ar) + Counter(sr)
added = len(list((have - Counter(br)).elements()))

print("source : %s" % source)
print("grammar: heading /^### What Session \\S+ Did$/ ; footer_mode=none (asserted) ; transform=none")
print("records: %d before = %d retained + %d archived; added by the trim commit: %d"
      % (len(br), len(ar), len(sr), added))
print("cut key: retained %s | archived %s   (hand-declared, checked by L4 and L5)"
      % (list(CUT_RETAINED), list(CUT_ARCHIVED)))
print("routing: %d clauses, checked in 3 copies (live pointer, shard banner, CLAUDE.md) and"
      % len(ROUTING))
print("         anchored against the record ids actually in each file it names")
print("reach  : %d copies L5 does not check — three no proof could see at all, plus CLAUDE.md's"
      % len(REACH))
print("         prose around the table L5 has always read (%s)"
      % ", ".join(p for p, _r, _f in REACH))
print("lineage: %d ancestor shard(s) held against their own add-commits" % len(lineage))
print("front  : pointer insertion + %d declared substitutions, all checked by exact equality"
      % len(FRONT_SUBST))
print("checked: L0, L1, L2/front-matter, L3, L4, L5, L6, L7, L8, L9    "
      "<- L2/footer absent: inapplicable, no footer zone")
if sha is None:
    print("         L7 inapplicable: the trim is not committed yet, so there is no frozen blob to")
    print("         compare the working tree against. It becomes live at the trim commit. L9 is")
    print("         applicable already — its ancestors were committed by earlier trims.")

if fails:
    print("\nFAIL for %s:" % SHARD)
    for f in fails:
        print("  " + f)
    sys.exit(1)

print("\nOK: %s hold for %s" % ("L0-L9" if sha else "L0-L6, L8, L9 (L7 inapplicable)", SHARD))
print("    Every byte of the pre-trim records zone is still present, in the right file, unedited,")
print("    in order, and on the declared side of the declared boundary; all three copies of the")
print("    routing table agree with that boundary AND with what the files they name contain; the")
print("    shard's banner is the declared text; README.md and PROJECT_CONVENTIONS.md describe the")
print("    shard set that now exists; and every earlier shard on disk is still the file its own")
print("    trim committed.")
if sha:
    print("    The shard on disk is still the shard that was committed at %s." % sha[:7])
else:
    print("    NOTHING is claimed about THIS shard on disk: L7 has no frozen blob to compare it")
    print("    against until the trim is committed. Re-run after committing.")
print("    It says NOTHING about whether the boundary was WISELY chosen, nor whether")
print("    any record's content is true — a human reads that once. It does not re-prove the S216,")
print("    S220 or S224 cuts: each has its own proof, pinned to its own cut key and its own")
print("    commit. Run those three as well. A green proof never --self-test'ed proves less than")
print("    it appears to.")
PYEOF
