#!/usr/bin/env python3
"""Assert a built MkDocs site actually contains every local file its HTML links.

**Why this exists.** ``mkdocs gh-deploy`` exits 0 whether or not the site it
publishes is complete. Between 2026-07-27 (``b27cc98``) and 2026-08-22 the
published tutorial served style-less HTML — no CSS, no search, no navigation —
because ``mkdocs.yml``'s ``exclude_docs`` allowlist also matched the Material
theme's ``assets/`` tree (MkDocs re-runs ``set_exclusions()`` *after*
``add_files_from_theme()``). The deploy dropped 43 files and reported success in
11 seconds, so four release phases landed on top of the regression unnoticed.
Session 234 found it by reading ``origin/gh-pages`` by hand; Session 237 fixed
the config and added this check so the failure can never be green again.

The check is deliberately self-calibrating: it asserts that what the built pages
*reference* is what the built site *contains*, so it needs no hard-coded file
count that would rot the next time the theme is upgraded. ``--require-css``
covers the one case reference-integrity cannot see on its own — a site that
consistently links nothing at all.

Stdlib only, on purpose: CI's test job installs ``--extra agents --extra ui
--extra dev`` and never the ``docs`` extra, so this stays unit-testable there.

Usage::

    python scripts/check_site_assets.py site --base-path /model_project_constructor/ --require-css

Exit status is 0 when every local reference resolves, 1 otherwise.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections.abc import Iterator
from pathlib import Path
from urllib.parse import unquote, urlsplit

# href="..." / src="..." in either quote style. A regex rather than an HTML
# parser because the input is machine-generated by MkDocs, and because the
# failure this guards is "the target file is absent", not "the markup is odd".
_REF = re.compile(r"""(?:href|src)\s*=\s*["']([^"']*)["']""", re.IGNORECASE)

# References that do not name a file inside the built site.
_EXTERNAL_PREFIXES = ("http://", "https://", "//", "data:", "mailto:", "tel:", "javascript:")


def iter_html(site: Path) -> Iterator[Path]:
    """Yield every HTML page in the built site, in a stable order."""
    yield from sorted(site.rglob("*.html"))


def extract_refs(html: str) -> list[str]:
    """Return every href/src value in ``html``, in document order."""
    return _REF.findall(html)


def is_local(ref: str) -> bool:
    """True when ``ref`` names a path inside the built site."""
    if not ref or ref.startswith("#"):
        return False
    return not ref.lower().startswith(_EXTERNAL_PREFIXES)


def target_path(ref: str) -> str:
    """Strip query and fragment, and percent-decode, leaving a bare path."""
    return unquote(urlsplit(ref).path)


def candidates(ref: str, page: Path, site: Path, base_path: str | None) -> list[Path]:
    """Every filesystem path ``ref`` could legitimately denote.

    Relative references resolve against the page that contains them. Root-relative
    references (MkDocs emits these in ``404.html``, which is served from the domain
    root and cannot use relative paths) resolve against the site root — after
    removing the site's base path, since a project Pages site is served under
    ``/<repo>/``. When ``base_path`` is not supplied, every leading segment is
    tried in turn so the script stays useful on a local build with no arguments;
    pass ``--base-path`` in CI, where being exact is worth the extra flag.
    """
    path = target_path(ref)
    if not path:
        return []
    if not path.startswith("/"):
        return [_normalise(page.parent / path)]

    rel = path.lstrip("/")
    if not rel:
        return [_normalise(site)]
    out = [_normalise(site / rel)]
    parts = rel.split("/")
    if base_path is not None:
        prefix = base_path.strip("/")
        if prefix and rel.startswith(f"{prefix}/"):
            out.append(_normalise(site / rel[len(prefix) + 1 :]))
    else:
        out.extend(_normalise(site / "/".join(parts[i:])) for i in range(1, len(parts)))
    return out


def _normalise(path: Path) -> Path:
    """Collapse ``.``/``..`` without touching the filesystem."""
    return Path(os.path.normpath(path))


def resolves(path: Path) -> bool:
    """True when ``path`` is a file, or a directory MkDocs would serve."""
    if path.is_dir():
        return (path / "index.html").is_file()
    return path.is_file()


def check(site: Path, base_path: str | None, require_css: bool) -> tuple[list[str], list[str]]:
    """Return ``(problems, notes)``. An empty ``problems`` list means the site is intact."""
    problems: list[str] = []
    notes: list[str] = []
    pages = list(iter_html(site))
    if not pages:
        problems.append(f"no HTML pages found under {site} — the build produced nothing to check")
        return problems, notes

    checked = 0
    css_referenced = 0
    css_present: set[str] = set()
    for page in pages:
        rel_page = page.relative_to(site)
        html = page.read_text(encoding="utf-8", errors="replace")
        for ref in extract_refs(html):
            if not is_local(ref):
                continue
            tried = candidates(ref, page, site, base_path)
            if not tried:
                continue
            checked += 1
            is_css = target_path(ref).endswith(".css")
            css_referenced += is_css
            hit = next((p for p in tried if resolves(p)), None)
            if hit is None:
                shown = ", ".join(str(p) for p in tried)
                problems.append(f"{rel_page}: references {ref!r} — no such file (tried: {shown})")
            elif is_css:
                css_present.add(str(hit))

    notes.append(f"{len(pages)} HTML page(s), {checked} local reference(s) checked")

    if require_css:
        # A dangling stylesheet is already reported above as a broken reference;
        # saying "no stylesheet is referenced" there too would be false. This
        # branch covers only the hole reference-integrity genuinely cannot see —
        # a site that is internally consistent and links no stylesheet at all.
        if css_referenced == 0:
            problems.append(
                "no stylesheet is referenced by any page — the site would render unstyled "
                "(this is the exact regression the check exists to catch)"
            )
        for path in sorted(p for p in css_present if Path(p).stat().st_size == 0):
            problems.append(f"referenced stylesheet is empty: {path}")
        if css_present:
            notes.append(f"{len(css_present)} stylesheet(s) referenced and present")

    return problems, notes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "site", nargs="?", default="site", help="built site directory (default: site)"
    )
    parser.add_argument(
        "--base-path",
        default=None,
        help="URL path the site is served under, e.g. /model_project_constructor/. "
        "Used to resolve root-relative references. Inferred by trying each leading "
        "segment when omitted.",
    )
    parser.add_argument(
        "--require-css",
        action="store_true",
        help="also fail when no page references a stylesheet, or a referenced stylesheet is empty",
    )
    args = parser.parse_args(argv)

    site = Path(args.site)
    if not site.is_dir():
        print(f"FAIL: {site} is not a directory — did the build run?", file=sys.stderr)
        return 1

    problems, notes = check(site, args.base_path, args.require_css)
    for note in notes:
        print(f"  {note}")
    sys.stdout.flush()  # keep notes above the stderr report in CI logs
    if problems:
        print(f"\nFAIL: {len(problems)} problem(s) in the built site at {site}:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    print(f"OK: every local reference in {site} resolves.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
